# Mult-VAE: исследование на marketplace-домене

Аналог `ials_research.ipynb` для **Multinomial Variational AutoEncoder**
(Liang et al. 2018). Структура повторяет IALS-ноутбук, чтобы сравнение с
SVD/iALS было воспроизводимым:

1. Загрузка событий, inverse-frequency target.
2. Temporal split 80/20.
3. Базовый прогон с типовыми гиперпараметрами.
4. Optuna на 40%-подмножестве пользователей.
5. Финальная оценка лучшей конфигурации на полных данных.
6. Сравнение Mult-VAE / iALS / SVD.

In [1]:
import os
import pyarrow as pa     # импорт необходим, чтобы не крашился ноутбук на Windows
import numpy as np
import polars as pl
import torch

import src.dataset as dts
from src.modeling.vae import run_vae_experiment
from src.modeling.train_vae import build_user_history_dataset, train_vae
from src.config import VAE_DIR

print("torch:", torch.__version__)

2026-05-10 13:40:33.870 | INFO     | src.config:<module>:12 - PROJ_ROOT path is: D:\HSE_repos\dreamteam-recsys

torch: 2.11.0+cu126

In [2]:
EVENTS_DIR = "../data/raw/dataset/small/marketplace/events"

events_df = pl.scan_parquet(f"{EVENTS_DIR}/*.pq", include_file_paths="path").sort("day")

In [3]:
# Inverse-frequency target — тот же, что в SVD/iALS-ноутбуках для конформности.
actions_count = (
    events_df.group_by("action_type")
    .agg(pl.len())
    .collect(engine="streaming")
    .with_columns(
        (pl.col("len").sum() / pl.col("len")).alias("target"),
        (pl.col("len").sum() / pl.col("len")).log1p().alias("log_target"),
        (pl.col("len").sum() / pl.col("len")).sqrt().alias("sqrt_target"),
    )
    .drop("len")
)
events_df = events_df.join(actions_count.lazy(), on="action_type")
actions_count

shape: (4, 4)
┌─────────────┬─────────────┬────────────┬─────────────┐
│ action_type ┆ target      ┆ log_target ┆ sqrt_target │
│ ---         ┆ ---         ┆ ---        ┆ ---         │
│ str         ┆ f64         ┆ f64        ┆ f64         │
╞═════════════╪═════════════╪════════════╪═════════════╡
│ click       ┆ 34.582149   ┆ 3.571844   ┆ 5.880659    │
│ like        ┆ 3121.341812 ┆ 8.046339   ┆ 55.86897    │
│ view        ┆ 1.034082    ┆ 0.710044   ┆ 1.016898    │
│ clickout    ┆ 268.714913  ┆ 5.597366   ┆ 16.392526   │
└─────────────┴─────────────┴────────────┴─────────────┘

In [11]:
train, test = dts.global_temporal_split(events_df, 0.2)
print(f"Train schema: {train.collect_schema()}")
print(f"Test schema:  {test.collect_schema()}")

Train schema: Schema({'timestamp': Duration(time_unit='us'), 'user_id': UInt64, 'item_id': String, 'subdomain': String, 'action_type': String, 'os': String, 'day': Int32, 'path': String, 'target': Float64, 'log_target': Float64, 'sqrt_target': Float64})
Test schema:  Schema({'timestamp': Duration(time_unit='us'), 'user_id': UInt64, 'item_id': String, 'subdomain': String, 'action_type': String, 'os': String, 'day': Int32, 'path': String, 'target': Float64, 'log_target': Float64, 'sqrt_target': Float64})

## Базовый прогон (OOM, GPU)

Архитектура `[600, 200]` — конфиг из оригинальной статьи Mult-VAE.
Бинаризованная история (`binary=True`) — стандартный режим для CF-VAE.

**Почему не `run_vae_experiment`?** На полном marketplace-сплите
(1.2M users × 498k items, 65M пар) `run_vae_experiment` строит
in-memory CSR + decoder ~498k → KILL'ом по VRAM на любой потребительской
карте. Поэтому baseline учим тем же OOM-стеком, что и CLI
(`python -m src.modeling.train_vae train`):

* feature-снимок `data/processed/datamart/features/events/user_id-item_id/{day}.pq`
  уже агрегирует 30-дневное окно → **20 000 selected items** и
  **~184 000 активных пользователей** (по `selected_items.pq` /
  `selected_users.pq`);
* sparse user-history стримится через `polars.sink_parquet`, дальше
  материализуется лениво HuggingFace `datasets` (Apache Arrow,
  memory-mapped);
* dense батч `(B, num_items)` собирается в коллатере **только** на текущий
  step и сразу освобождается.

**Параметры зеркалят успешный CLI-прогон**: `day=1305, epochs=30,
batch_size=256` (этот же набор стабильно работал на RTX 2080 SUPER 8GB).

> Target-leak: feature-снимок дня `D` агрегирует окно `[D-29, D]`,
> поэтому если соберётесь добавлять метрики поверх `test`, оценивать
> можно только события за дни `> D`.

In [5]:
import shutil
import tempfile
from pathlib import Path

DAY                = 1305          # снимок 30-дневного окна [1276, 1305]
EPOCHS             = 30
BATCH_SIZE         = 256
ENCODER_DIMS       = [600, 200]
DROPOUT            = 0.5
BETA               = 0.2
TOTAL_ANNEAL_STEPS = 200_000
KL_SCHEDULE        = "linear"
LR                 = 1e-3
WEIGHT_DECAY       = 0.0
BINARY             = True
MIN_USER_ITEMS     = 5
SEED               = 42

# Создаем временную папку для хранения истории
tmp_dir = Path(tempfile.mkdtemp(prefix="vae_history_"))
history_path = tmp_dir / "history.pq"
try:
    history_path, item_to_idx, user_to_idx = build_user_history_dataset(
        day=DAY,
        output_path=history_path,
        binary=BINARY,
        min_user_items=MIN_USER_ITEMS,
    )
    print(
        f"Снимок дня {DAY}: "
        f"{len(user_to_idx):,} активных users x {len(item_to_idx):,} items"
    )

    checkpoint_path = train_vae(
        history_path=history_path,
        item_to_idx=item_to_idx,
        user_to_idx=user_to_idx,
        artifacts_dir=VAE_DIR,
        encoder_dims=ENCODER_DIMS,
        dropout=DROPOUT,
        beta=BETA,
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        lr=LR,
        weight_decay=WEIGHT_DECAY,
        total_anneal_steps=TOTAL_ANNEAL_STEPS,
        kl_schedule=KL_SCHEDULE,
        use_lr_scheduler=True,
        num_workers=0,            # Windows: иначе DataLoader крашится
        seed=SEED,
    )
    print(f"Чекпоинт сохранён: {checkpoint_path}")
finally:
    shutil.rmtree(tmp_dir, ignore_errors=True)

2026-05-09 23:39:17.841 | INFO     | src.modeling.train_vae:build_user_history_dataset:142 - Сбор маппингов item/user...
2026-05-09 23:39:17.853 | INFO     | src.modeling.train_vae:build_user_history_dataset:154 - Каталог айтемов: 20000 штук
2026-05-09 23:39:17.856 | INFO     | src.modeling.train_vae:build_user_history_dataset:214 - Сохранение sparse user-history в C:\Users\Sasha\AppData\Local\Temp\vae_history_gy5h91dg\history.pq (streaming sink)...
2026-05-09 23:39:18.389 | INFO     | src.modeling.train_vae:build_user_history_dataset:223 - Активных пользователей: 184239
Снимок дня 1305: 184,239 активных users x 20,000 items
2026-05-09 23:39:18.693 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=20000, dims=[600, 200], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-09 23:39:19.194 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 184239 пользователей, 20000 items, batches per epoch ≈ 720

Сборка user_items: 100%|██████████| 184239/184239 [00:05<00:00, 32127.84user/s]
Эпохи:   3%|▎         | 1/30 [00:17<08:34, 17.74s/epoch, beta=0.001, kld=295.267, loss=164.633, lr=9.97e-04, nll=164.499]

2026-05-09 23:39:49.342 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=164.6326 nll=164.4987 kld=295.2670 beta=0.0007 lr=9.97e-04 time=17.7s

Эпохи:   7%|▋         | 2/30 [00:35<08:10, 17.51s/epoch, beta=0.001, kld=394.871, loss=143.773, lr=9.89e-04, nll=143.350]

2026-05-09 23:40:06.689 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=143.7730 nll=143.3502 kld=394.8713 beta=0.0014 lr=9.89e-04 time=17.3s

Эпохи:  10%|█         | 3/30 [00:52<07:53, 17.53s/epoch, beta=0.002, kld=350.537, loss=138.812, lr=9.76e-04, nll=138.183]

2026-05-09 23:40:24.240 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=138.8118 nll=138.1828 kld=350.5367 beta=0.0022 lr=9.76e-04 time=17.5s

Эпохи:  13%|█▎        | 4/30 [01:10<07:34, 17.48s/epoch, beta=0.003, kld=326.428, loss=136.245, lr=9.57e-04, nll=135.423]

2026-05-09 23:40:41.640 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=136.2447 nll=135.4233 kld=326.4275 beta=0.0029 lr=9.57e-04 time=17.4s

Эпохи:  17%|█▋        | 5/30 [01:27<07:19, 17.58s/epoch, beta=0.004, kld=308.598, loss=134.591, lr=9.34e-04, nll=133.592]

2026-05-09 23:40:59.404 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=134.5911 nll=133.5921 kld=308.5977 beta=0.0036 lr=9.34e-04 time=17.8s

Эпохи:  20%|██        | 6/30 [01:45<07:00, 17.51s/epoch, beta=0.004, kld=293.725, loss=133.397, lr=9.05e-04, nll=132.234]

2026-05-09 23:41:16.767 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=133.3969 nll=132.2345 kld=293.7251 beta=0.0043 lr=9.05e-04 time=17.4s

Эпохи:  23%|██▎       | 7/30 [02:02<06:42, 17.49s/epoch, beta=0.005, kld=280.832, loss=132.432, lr=8.73e-04, nll=131.119]

2026-05-09 23:41:34.216 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=132.4324 nll=131.1187 kld=280.8321 beta=0.0050 lr=8.73e-04 time=17.4s

Эпохи:  27%|██▋       | 8/30 [02:20<06:25, 17.52s/epoch, beta=0.006, kld=270.032, loss=131.752, lr=8.36e-04, nll=130.294]

2026-05-09 23:41:51.796 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=131.7517 nll=130.2941 kld=270.0322 beta=0.0058 lr=8.36e-04 time=17.6s

Эпохи:  30%|███       | 9/30 [02:37<06:06, 17.47s/epoch, beta=0.006, kld=260.116, loss=131.148, lr=7.96e-04, nll=129.556]

2026-05-09 23:42:09.174 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=131.1476 nll=129.5561 kld=260.1159 beta=0.0065 lr=7.96e-04 time=17.4s

Эпохи:  33%|███▎      | 10/30 [02:55<05:52, 17.62s/epoch, beta=0.007, kld=250.992, loss=130.555, lr=7.52e-04, nll=128.838]

2026-05-09 23:42:27.125 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=130.5546 nll=128.8383 kld=250.9920 beta=0.0072 lr=7.52e-04 time=17.9s

Эпохи:  37%|███▋      | 11/30 [03:22<06:29, 20.49s/epoch, beta=0.008, kld=242.936, loss=130.060, lr=7.06e-04, nll=128.224]

2026-05-09 23:42:54.117 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 11: loss=130.0602 nll=128.2241 kld=242.9364 beta=0.0079 lr=7.06e-04 time=27.0s

Эпохи:  40%|████      | 12/30 [03:43<06:09, 20.51s/epoch, beta=0.009, kld=235.128, loss=129.659, lr=6.58e-04, nll=127.713]

2026-05-09 23:43:14.668 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 12: loss=129.6592 nll=127.7127 kld=235.1284 beta=0.0086 lr=6.58e-04 time=20.5s

Эпохи:  43%|████▎     | 13/30 [04:00<05:32, 19.53s/epoch, beta=0.009, kld=228.969, loss=129.252, lr=6.08e-04, nll=127.192]

2026-05-09 23:43:31.951 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 13: loss=129.2520 nll=127.1916 kld=228.9687 beta=0.0094 lr=6.08e-04 time=17.3s

Эпохи:  47%|████▋     | 14/30 [04:26<05:44, 21.51s/epoch, beta=0.010, kld=222.801, loss=128.875, lr=5.57e-04, nll=126.710]

2026-05-09 23:43:58.028 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 14: loss=128.8750 nll=126.7097 kld=222.8007 beta=0.0101 lr=5.57e-04 time=26.1s

Эпохи:  50%|█████     | 15/30 [04:54<05:50, 23.38s/epoch, beta=0.011, kld=216.958, loss=128.569, lr=5.05e-04, nll=126.304]

2026-05-09 23:44:25.740 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 15: loss=128.5691 nll=126.3044 kld=216.9578 beta=0.0108 lr=5.05e-04 time=27.7s

Эпохи:  53%|█████▎    | 16/30 [05:21<05:44, 24.62s/epoch, beta=0.012, kld=211.817, loss=128.260, lr=4.53e-04, nll=125.897]

2026-05-09 23:44:53.244 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 16: loss=128.2603 nll=125.8967 kld=211.8168 beta=0.0115 lr=4.53e-04 time=27.5s

Эпохи:  57%|█████▋    | 17/30 [05:44<05:15, 24.24s/epoch, beta=0.012, kld=206.824, loss=127.984, lr=4.02e-04, nll=125.527]

2026-05-09 23:45:16.596 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 17: loss=127.9838 nll=125.5271 kld=206.8242 beta=0.0122 lr=4.02e-04 time=23.3s

Эпохи:  60%|██████    | 18/30 [06:02<04:26, 22.23s/epoch, beta=0.013, kld=202.096, loss=127.753, lr=3.52e-04, nll=125.207]

2026-05-09 23:45:34.137 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 18: loss=127.7530 nll=125.2069 kld=202.0956 beta=0.0130 lr=3.52e-04 time=17.5s

Эпохи:  63%|██████▎   | 19/30 [06:29<04:20, 23.72s/epoch, beta=0.014, kld=198.118, loss=127.571, lr=3.04e-04, nll=124.932]

2026-05-09 23:46:01.334 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 19: loss=127.5713 nll=124.9325 kld=198.1177 beta=0.0137 lr=3.04e-04 time=27.2s

Эпохи:  67%|██████▋   | 20/30 [06:56<04:07, 24.71s/epoch, beta=0.014, kld=194.110, loss=127.400, lr=2.57e-04, nll=124.675]

2026-05-09 23:46:28.351 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 20: loss=127.3999 nll=124.6746 kld=194.1103 beta=0.0144 lr=2.57e-04 time=27.0s

Эпохи:  70%|███████   | 21/30 [07:18<03:34, 23.88s/epoch, beta=0.015, kld=190.362, loss=127.213, lr=2.14e-04, nll=124.403]

2026-05-09 23:46:50.311 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 21: loss=127.2127 nll=124.4031 kld=190.3617 beta=0.0151 lr=2.14e-04 time=22.0s

Эпохи:  73%|███████▎  | 22/30 [07:46<03:19, 24.97s/epoch, beta=0.016, kld=187.069, loss=127.119, lr=1.74e-04, nll=124.223]

2026-05-09 23:47:17.825 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 22: loss=127.1189 nll=124.2232 kld=187.0686 beta=0.0158 lr=1.74e-04 time=27.5s

Эпохи:  77%|███████▋  | 23/30 [08:14<03:00, 25.85s/epoch, beta=0.017, kld=183.379, loss=127.053, lr=1.37e-04, nll=124.082]

2026-05-09 23:47:45.720 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 23: loss=127.0526 nll=124.0820 kld=183.3791 beta=0.0166 lr=1.37e-04 time=27.9s

Эпохи:  80%|████████  | 24/30 [08:42<02:38, 26.49s/epoch, beta=0.017, kld=180.304, loss=127.001, lr=1.05e-04, nll=123.951]

2026-05-09 23:48:13.715 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 24: loss=127.0014 nll=123.9508 kld=180.3040 beta=0.0173 lr=1.05e-04 time=28.0s

Эпохи:  83%|████████▎ | 25/30 [09:10<02:14, 26.98s/epoch, beta=0.018, kld=177.391, loss=126.944, lr=7.63e-05, nll=123.815]

2026-05-09 23:48:41.820 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 25: loss=126.9441 nll=123.8150 kld=177.3913 beta=0.0180 lr=7.63e-05 time=28.1s

Эпохи:  87%|████████▋ | 26/30 [09:37<01:48, 27.05s/epoch, beta=0.019, kld=174.694, loss=126.971, lr=5.28e-05, nll=123.763]

2026-05-09 23:49:09.033 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 26: loss=126.9707 nll=123.7633 kld=174.6940 beta=0.0187 lr=5.28e-05 time=27.2s

Эпохи:  90%|█████████ | 27/30 [10:05<01:21, 27.29s/epoch, beta=0.019, kld=172.300, loss=126.990, lr=3.42e-05, nll=123.702]

2026-05-09 23:49:36.890 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 27: loss=126.9896 nll=123.7022 kld=172.2998 beta=0.0194 lr=3.42e-05 time=27.9s

Эпохи:  93%|█████████▎| 28/30 [10:33<00:55, 27.57s/epoch, beta=0.020, kld=170.116, loss=127.082, lr=2.08e-05, nll=123.714]

2026-05-09 23:50:05.097 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 28: loss=127.0821 nll=123.7139 kld=170.1155 beta=0.0202 lr=2.08e-05 time=28.2s

Эпохи:  97%|█████████▋| 29/30 [11:01<00:27, 27.72s/epoch, beta=0.021, kld=167.921, loss=127.134, lr=1.27e-05, nll=123.688]

2026-05-09 23:50:33.170 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 29: loss=127.1342 nll=123.6885 kld=167.9211 beta=0.0209 lr=1.27e-05 time=28.1s

Эпохи: 100%|██████████| 30/30 [11:29<00:00, 22.99s/epoch, beta=0.022, kld=166.140, loss=127.241, lr=1.00e-05, nll=123.712]

2026-05-09 23:51:01.359 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 30: loss=127.2409 nll=123.7121 kld=166.1397 beta=0.0216 lr=1.00e-05 time=28.2s
2026-05-09 23:51:01.599 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в D:\HSE_repos\dreamteam-recsys\models\vae_artifacts\model.pt
2026-05-09 23:51:03.798 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в D:\HSE_repos\dreamteam-recsys\models\vae_artifacts
Чекпоинт сохранён: D:\HSE_repos\dreamteam-recsys\models\vae_artifacts\model.pt

## Гипероптимизация (Optuna)

Для сокращения затрат на ресурсы:
1. Берем **40% пользователей** случайной выборкой.
2. На подмножестве пользователей запускаем гипероптимизацию, целевая метрика — **NDCG@15**.
3. Лучшую конфигурацию переобучаем на полном датасете.

In [4]:
import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

SUBSET_FRACTION = 0.4
OPTUNA_TRIALS = 20
TOP_K = 15
RANDOM_SEED = 42

all_user_ids = (
    events_df.select("user_id").unique().collect(engine="streaming")["user_id"].to_list()
)
rng = np.random.default_rng(RANDOM_SEED)
subset_users = set(
    rng.choice(all_user_ids, size=int(len(all_user_ids) * SUBSET_FRACTION), replace=False).tolist()
)
print(f"Всего пользователей: {len(all_user_ids):,}")
print(f"Пользователей в подмножестве ({SUBSET_FRACTION*100:.0f}%): {len(subset_users):,}")

events_sub = events_df.filter(pl.col("user_id").is_in(subset_users))
train_sub, test_sub = dts.global_temporal_split(events_sub, 0.2)
print("Подмножество готово")

Всего пользователей: 1,616,763
Пользователей в подмножестве (40%): 646,705
Подмножество готово

In [6]:
events_df.head().collect()

shape: (5, 11)
┌────────────┬──────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ timestamp  ┆ user_id  ┆ item_id   ┆ subdomain ┆ … ┆ path      ┆ target   ┆ log_targe ┆ sqrt_targ │
│ ---        ┆ ---      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---      ┆ t         ┆ et        │
│ duration[μ ┆ u64      ┆ str       ┆ str       ┆   ┆ str       ┆ f64      ┆ ---       ┆ ---       │
│ s]         ┆          ┆           ┆           ┆   ┆           ┆          ┆ f64       ┆ f64       │
╞════════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 1082d      ┆ 59328774 ┆ nfmcg_147 ┆ u2i       ┆ … ┆ ..\data\r ┆ 1.034082 ┆ 0.710044  ┆ 1.016898  │
│ 89901µs    ┆          ┆ 77696     ┆           ┆   ┆ aw\datase ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ t\small\m ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ ark…      ┆          ┆           ┆           │
│ 1082d      ┆ 66295302 ┆ nfmcg_260 ┆ catalog   ┆ … ┆ ..\data\r ┆ 1.034082 ┆ 0.710044  ┆ 1.016898  │
│ 163483µs   ┆          ┆ 98539     ┆           ┆   ┆ aw\datase ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ t\small\m ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ ark…      ┆          ┆           ┆           │
│ 1082d      ┆ 37542104 ┆ nfmcg_108 ┆ u2i       ┆ … ┆ ..\data\r ┆ 1.034082 ┆ 0.710044  ┆ 1.016898  │
│ 864625µs   ┆          ┆ 40247     ┆           ┆   ┆ aw\datase ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ t\small\m ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ ark…      ┆          ┆           ┆           │
│ 1082d      ┆ 35193548 ┆ nfmcg_804 ┆ catalog   ┆ … ┆ ..\data\r ┆ 1.034082 ┆ 0.710044  ┆ 1.016898  │
│ 889192µs   ┆          ┆ 0572      ┆           ┆   ┆ aw\datase ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ t\small\m ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ ark…      ┆          ┆           ┆           │
│ 1082d      ┆ 27256137 ┆ nfmcg_677 ┆ catalog   ┆ … ┆ ..\data\r ┆ 1.034082 ┆ 0.710044  ┆ 1.016898  │
│ 936008µs   ┆          ┆ 0239      ┆           ┆   ┆ aw\datase ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ t\small\m ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ ark…      ┆          ┆           ┆           │
└────────────┴──────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [ ]:
ITEMS_TO_TAKE = 20_000

all_items_ids = (
    train_sub.group_by("item_id").agg(count=pl.len()).sort("count", descending=True).head(ITEMS_TO_TAKE).collect(engine="streaming")["item_id"].to_list()
)

In [6]:
train_sub = train_sub.filter(pl.col("item_id").is_in(all_items_ids))

Берем подмножество товаров для обучения:

In [7]:
import shutil
import tempfile
from pathlib import Path
from scipy.sparse import load_npz

from src.modeling.vae import MultiVAERecommender
from src.dataset import ndcg_at_k, precision_recall_at_k

DAY                = 1276          # снимок 30-дневного окна [1276, 1305]
EPOCHS             = 30
BATCH_SIZE         = 256
ENCODER_DIMS       = [600, 200]
DROPOUT            = 0.5
BETA               = 0.2
TOTAL_ANNEAL_STEPS = 200_000
KL_SCHEDULE        = "linear"
LR                 = 1e-3
WEIGHT_DECAY       = 0.0
BINARY             = True
MIN_USER_ITEMS     = 5
SEED               = 42


def build_history_from_events(
    train_lf: pl.LazyFrame,
    target_col: str,
    output_path: Path,
    binary: bool = True,
    min_interactions: int = 3,
    min_day: int | None = None,
) -> tuple[dict[str, int], dict[int, int]]:
    """Строит sparse user-history parquet из LazyFrame событий.

    Выходная схема: (user_idx: u32, user_id: u64, item_idx: list[u32], weight: list[f32]).
    train_lf должен уже быть отфильтрован по нужным item_id.

    Parameters
    ----------
    min_day : int or None
        Если задан, используются только события с ``day >= min_day``.
        Позволяет ограничить историю конкретным временным окном,
        аналогично снимку ``build_user_history_dataset(day=DAY)``.
    """
    if min_day is not None:
        train_lf = train_lf.filter(pl.col("day") >= min_day)

    df = (
        train_lf
        .select("user_id", "item_id", target_col)
        .collect(engine="streaming")
        .group_by("user_id", "item_id")
        .agg(pl.col(target_col).sum())
    )

    valid_users = (
        df.group_by("user_id").agg(pl.len().alias("cnt"))
        .filter(pl.col("cnt") >= min_interactions).select("user_id")
    )
    valid_items = (
        df.group_by("item_id").agg(pl.len().alias("cnt"))
        .filter(pl.col("cnt") >= min_interactions).select("item_id")
    )
    df = df.join(valid_users, on="user_id").join(valid_items, on="item_id")

    item_ids_sorted = df.select("item_id").unique().sort("item_id")["item_id"].to_list()
    item_to_idx: dict[str, int] = {iid: idx for idx, iid in enumerate(item_ids_sorted)}
    items_meta = pl.DataFrame(
        {"item_id": item_ids_sorted, "item_idx": list(range(len(item_ids_sorted)))},
        schema={"item_id": pl.String, "item_idx": pl.UInt32},
    )

    if binary:
        df = df.with_columns(weight=pl.lit(1.0, dtype=pl.Float32))
    else:
        df = df.with_columns(weight=pl.col(target_col).cast(pl.Float32))

    df = df.join(items_meta, on="item_id")

    user_df = (
        df.group_by("user_id")
        .agg(pl.col("item_idx"), pl.col("weight"))
        .sort("user_id")
        .with_row_index("user_idx")
        .with_columns(pl.col("user_idx").cast(pl.UInt32))
    )
    user_to_idx: dict[int, int] = dict(
        zip(user_df["user_id"].to_list(), user_df["user_idx"].to_list())
    )

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    user_df.select("user_idx", "user_id", "item_idx", "weight").write_parquet(output_path)
    return item_to_idx, user_to_idx


def evaluate_ndcg(
    rec: MultiVAERecommender,
    test_lf: pl.LazyFrame,
    target_col: str,
    top_k: int = 15,
) -> dict:
    """Считает NDCG/Precision/Recall на тестовой выборке."""
    test_df = test_lf.select("user_id", "item_id", target_col).collect(engine="streaming")
    known_users = set(rec.user_to_idx.keys())
    test_filtered = test_df.filter(pl.col("user_id").is_in(known_users))

    user_test_truth = test_filtered.group_by("user_id").agg(
        pl.col("item_id").alias("true_items"),
        pl.col(target_col).alias("relevancy"),
    )
    test_user_ids = user_test_truth["user_id"].to_numpy()
    test_user_idxs = np.array([rec.user_to_idx[uid] for uid in test_user_ids])

    BATCH = 1024
    item_idx_chunks, score_chunks = [], []
    for start in range(0, len(test_user_idxs), BATCH):
        chunk = test_user_idxs[start : start + BATCH]
        ids, scores = rec.recommend_batch(chunk, top_k=top_k)
        item_idx_chunks.append(ids)
        score_chunks.append(scores)

    item_idx_matrix = np.concatenate(item_idx_chunks, axis=0)
    score_matrix    = np.concatenate(score_chunks,    axis=0)

    predicted_items_list  = [[rec.idx_to_item[i] for i in row] for row in item_idx_matrix]
    predicted_scores_list = [row.tolist() for row in score_matrix]

    prediction_df  = pl.DataFrame({
        "user_id":          test_user_ids,
        "predicted_items":  predicted_items_list,
        "predicted_scores": predicted_scores_list,
    })
    evaluation_df = user_test_truth.join(prediction_df, on="user_id")

    ndcg_results = ndcg_at_k(
        evaluation_df,
        relevancy_col="relevancy",
        true_items_col="true_items",
        predicted_items_col="predicted_items",
        predicted_score_col="predicted_scores",
        top_k=top_k,
    )
    mean_ndcg = float(ndcg_results["ndcg"].mean())
    precision, recall = precision_recall_at_k(
        evaluation_df,
        predicted_items_col="predicted_items",
        true_items_col="true_items",
        top_k=top_k,
    )
    return {"ndcg": mean_ndcg, "precision": precision, "recall": recall}


def optuna_objective(trial: optuna.Trial) -> float:
    target_col = trial.suggest_categorical("target_col", ["log_target", "sqrt_target"])
    latent_dim = trial.suggest_categorical("latent_dim", [64, 128, 200, 256])
    hidden_dim = trial.suggest_categorical("hidden_dim", [400, 600, 800])
    dropout    = trial.suggest_float("dropout", 0.2, 0.7, step=0.1)
    beta       = trial.suggest_float("beta", 0.05, 0.5, log=True)
    epochs     = trial.suggest_int("epochs", 10, 30, step=5)
    binary     = trial.suggest_categorical("binary", [True, False])

    tmp_dir = Path(tempfile.mkdtemp(prefix="vae_optuna_"))
    try:
        history_path  = tmp_dir / "history.pq"
        artifacts_dir = tmp_dir / "artifacts"

        # Шаг 1 — OOM-совместимый history parquet из train_sub
        # DAY — конец 30-дневного окна [DAY-29, DAY], как в снимке OOM baseline
        item_to_idx, user_to_idx = build_history_from_events(
            train_sub,
            target_col=target_col,
            output_path=history_path,
            binary=binary,
            min_interactions=3,
            min_day=DAY - 29,
        )

        # Шаг 2 — OOM-обучение (HuggingFace Arrow, dense батч только на шаге)
        train_vae(
            history_path=history_path,
            item_to_idx=item_to_idx,
            user_to_idx=user_to_idx,
            artifacts_dir=artifacts_dir,
            encoder_dims=[hidden_dim, latent_dim],
            dropout=dropout,
            beta=beta,
            epochs=epochs,
            batch_size=256,
            total_anneal_steps=100_000,
            use_lr_scheduler=True,
            num_workers=0,
            seed=RANDOM_SEED,
        )

        # Шаг 3 — загрузка и оценка на test_sub
        rec = MultiVAERecommender()
        rec.load(artifacts_dir / "model.pt")
        rec.set_user_items(load_npz(artifacts_dir / "user_items.npz"))

        metrics = evaluate_ndcg(rec, test_sub, target_col=target_col, top_k=TOP_K)
        ndcg = metrics["ndcg"]
        trial.set_user_attr("precision", metrics["precision"])
        trial.set_user_attr("recall",    metrics["recall"])
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)

    print(
        f"  Trial {trial.number}: target={target_col}, dims=[{hidden_dim},{latent_dim}], "
        f"dropout={dropout:.1f}, beta={beta:.3f}, epochs={epochs}, binary={binary} "
        f"→ NDCG@{TOP_K}={ndcg:.6f}"
    )
    return ndcg


sampler = optuna.samplers.TPESampler(seed=RANDOM_SEED)
study = optuna.create_study(direction="maximize", sampler=sampler)

print(f"Запуск Optuna: {OPTUNA_TRIALS} trials на {SUBSET_FRACTION*100:.0f}% датасета...")
study.optimize(optuna_objective, n_trials=OPTUNA_TRIALS, show_progress_bar=False)

best = study.best_trial
print(f"\nЛучший trial #{best.number}:")
print(f"  NDCG@{TOP_K} = {best.value:.6f}")
for k, v in best.params.items():
    print(f"  {k} = {v}")

Запуск Optuna: 20 trials на 40% датасета...
2026-05-10 13:41:45.677 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 13:41:45.854 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:04<00:00, 41357.13user/s]
Эпохи:   3%|▎         | 1/30 [00:11<05:39, 11.69s/epoch, beta=0.000, kld=144.751, loss=77.969, lr=9.97e-04, nll=77.938]

2026-05-10 13:42:03.100 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=77.9693 nll=77.9383 kld=144.7509 beta=0.0003 lr=9.97e-04 time=11.7s

Эпохи:   7%|▋         | 2/30 [00:22<05:15, 11.26s/epoch, beta=0.001, kld=205.844, loss=67.753, lr=9.89e-04, nll=67.646]

2026-05-10 13:42:14.058 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=67.7526 nll=67.6458 kld=205.8444 beta=0.0007 lr=9.89e-04 time=11.0s

Эпохи:  10%|█         | 3/30 [00:38<06:01, 13.40s/epoch, beta=0.001, kld=184.663, loss=65.761, lr=9.76e-04, nll=65.601]

2026-05-10 13:42:30.011 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=65.7607 nll=65.6007 kld=184.6631 beta=0.0010 lr=9.76e-04 time=16.0s

Эпохи:  13%|█▎        | 4/30 [00:49<05:26, 12.55s/epoch, beta=0.001, kld=171.475, loss=64.707, lr=9.57e-04, nll=64.499]

2026-05-10 13:42:41.250 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=64.7069 nll=64.4986 kld=171.4755 beta=0.0014 lr=9.57e-04 time=11.2s

Эпохи:  17%|█▋        | 5/30 [01:01<05:04, 12.18s/epoch, beta=0.002, kld=162.623, loss=64.046, lr=9.34e-04, nll=63.791]

2026-05-10 13:42:52.780 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=64.0457 nll=63.7914 kld=162.6231 beta=0.0017 lr=9.34e-04 time=11.5s

Эпохи:  20%|██        | 6/30 [01:13<04:48, 12.03s/epoch, beta=0.002, kld=155.325, loss=63.541, lr=9.05e-04, nll=63.244]

2026-05-10 13:43:04.510 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=63.5407 nll=63.2439 kld=155.3247 beta=0.0021 lr=9.05e-04 time=11.7s

Эпохи:  23%|██▎       | 7/30 [01:25<04:42, 12.30s/epoch, beta=0.002, kld=150.105, loss=63.216, lr=8.73e-04, nll=62.877]

2026-05-10 13:43:17.370 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=63.2163 nll=62.8773 kld=150.1050 beta=0.0024 lr=8.73e-04 time=12.9s

Эпохи:  27%|██▋       | 8/30 [01:39<04:40, 12.75s/epoch, beta=0.003, kld=145.914, loss=62.925, lr=8.36e-04, nll=62.544]

2026-05-10 13:43:31.091 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=62.9248 nll=62.5445 kld=145.9135 beta=0.0028 lr=8.36e-04 time=13.7s

Эпохи:  30%|███       | 9/30 [01:59<05:13, 14.95s/epoch, beta=0.003, kld=141.682, loss=62.670, lr=7.96e-04, nll=62.251]

2026-05-10 13:43:50.868 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=62.6698 nll=62.2513 kld=141.6819 beta=0.0031 lr=7.96e-04 time=19.8s

Эпохи:  33%|███▎      | 10/30 [02:19<05:28, 16.41s/epoch, beta=0.003, kld=137.654, loss=62.457, lr=7.52e-04, nll=62.002]

2026-05-10 13:44:10.537 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=62.4567 nll=62.0022 kld=137.6538 beta=0.0035 lr=7.52e-04 time=19.7s

Эпохи:  37%|███▋      | 11/30 [02:38<05:31, 17.45s/epoch, beta=0.004, kld=134.590, loss=62.297, lr=7.06e-04, nll=61.806]

2026-05-10 13:44:30.348 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 11: loss=62.2972 nll=61.8061 kld=134.5897 beta=0.0038 lr=7.06e-04 time=19.8s

Эпохи:  40%|████      | 12/30 [02:58<05:25, 18.09s/epoch, beta=0.004, kld=131.750, loss=62.092, lr=6.58e-04, nll=61.566]

2026-05-10 13:44:49.901 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 12: loss=62.0924 nll=61.5658 kld=131.7503 beta=0.0042 lr=6.58e-04 time=19.6s

Эпохи:  43%|████▎     | 13/30 [03:18<05:16, 18.64s/epoch, beta=0.005, kld=129.208, loss=61.950, lr=6.08e-04, nll=61.388]

2026-05-10 13:45:09.820 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 13: loss=61.9498 nll=61.3884 kld=129.2083 beta=0.0045 lr=6.08e-04 time=19.9s

Эпохи:  47%|████▋     | 14/30 [03:38<05:03, 18.97s/epoch, beta=0.005, kld=126.574, loss=61.766, lr=5.57e-04, nll=61.172]

2026-05-10 13:45:29.561 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 14: loss=61.7659 nll=61.1720 kld=126.5742 beta=0.0049 lr=5.57e-04 time=19.7s

Эпохи:  50%|█████     | 15/30 [03:57<04:47, 19.20s/epoch, beta=0.005, kld=124.318, loss=61.660, lr=5.05e-04, nll=61.033]

2026-05-10 13:45:49.277 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 15: loss=61.6595 nll=61.0330 kld=124.3179 beta=0.0052 lr=5.05e-04 time=19.7s

Эпохи:  53%|█████▎    | 16/30 [04:17<04:31, 19.37s/epoch, beta=0.006, kld=122.003, loss=61.549, lr=4.53e-04, nll=60.891]

2026-05-10 13:46:09.045 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 16: loss=61.5487 nll=60.8915 kld=122.0032 beta=0.0056 lr=4.53e-04 time=19.8s

Эпохи:  57%|█████▋    | 17/30 [04:37<04:12, 19.41s/epoch, beta=0.006, kld=119.823, loss=61.442, lr=4.02e-04, nll=60.754]

2026-05-10 13:46:28.534 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 17: loss=61.4415 nll=60.7544 kld=119.8226 beta=0.0059 lr=4.02e-04 time=19.5s

Эпохи:  60%|██████    | 18/30 [04:56<03:54, 19.51s/epoch, beta=0.006, kld=117.973, loss=61.312, lr=3.52e-04, nll=60.595]

2026-05-10 13:46:48.271 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 18: loss=61.3123 nll=60.5947 kld=117.9733 beta=0.0063 lr=3.52e-04 time=19.7s

Эпохи:  63%|██████▎   | 19/30 [05:14<03:28, 18.96s/epoch, beta=0.007, kld=116.115, loss=61.185, lr=3.04e-04, nll=60.438]

2026-05-10 13:47:05.964 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 19: loss=61.1849 nll=60.4383 kld=116.1155 beta=0.0066 lr=3.04e-04 time=17.7s

Эпохи:  67%|██████▋   | 20/30 [05:26<02:48, 16.86s/epoch, beta=0.007, kld=114.677, loss=61.142, lr=2.57e-04, nll=60.365]

2026-05-10 13:47:17.913 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 20: loss=61.1423 nll=60.3650 kld=114.6767 beta=0.0070 lr=2.57e-04 time=11.9s

Эпохи:  70%|███████   | 21/30 [05:45<02:38, 17.61s/epoch, beta=0.007, kld=113.035, loss=61.041, lr=2.14e-04, nll=60.236]

2026-05-10 13:47:37.297 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 21: loss=61.0413 nll=60.2359 kld=113.0352 beta=0.0073 lr=2.14e-04 time=19.4s

Эпохи:  73%|███████▎  | 22/30 [06:05<02:26, 18.25s/epoch, beta=0.008, kld=111.578, loss=61.010, lr=1.74e-04, nll=60.176]

2026-05-10 13:47:57.043 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 22: loss=61.0102 nll=60.1763 kld=111.5783 beta=0.0076 lr=1.74e-04 time=19.7s

Эпохи:  77%|███████▋  | 23/30 [06:25<02:10, 18.70s/epoch, beta=0.008, kld=110.229, loss=60.969, lr=1.37e-04, nll=60.107]

2026-05-10 13:48:16.781 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 23: loss=60.9693 nll=60.1072 kld=110.2293 beta=0.0080 lr=1.37e-04 time=19.7s

Эпохи:  80%|████████  | 24/30 [06:45<01:53, 19.00s/epoch, beta=0.008, kld=108.671, loss=60.894, lr=1.05e-04, nll=60.006]

2026-05-10 13:48:36.473 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 24: loss=60.8937 nll=60.0060 kld=108.6708 beta=0.0083 lr=1.05e-04 time=19.7s

Эпохи:  83%|████████▎ | 25/30 [07:04<01:36, 19.21s/epoch, beta=0.009, kld=107.496, loss=60.887, lr=7.63e-05, nll=59.971]

2026-05-10 13:48:56.177 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 25: loss=60.8869 nll=59.9715 kld=107.4956 beta=0.0087 lr=7.63e-05 time=19.7s

Эпохи:  87%|████████▋ | 26/30 [07:24<01:17, 19.32s/epoch, beta=0.009, kld=106.414, loss=60.885, lr=5.28e-05, nll=59.942]

2026-05-10 13:49:15.739 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 26: loss=60.8852 nll=59.9420 kld=106.4142 beta=0.0090 lr=5.28e-05 time=19.6s

Эпохи:  90%|█████████ | 27/30 [07:43<00:57, 19.14s/epoch, beta=0.009, kld=105.141, loss=60.867, lr=3.42e-05, nll=59.899]

2026-05-10 13:49:34.480 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 27: loss=60.8674 nll=59.8989 kld=105.1408 beta=0.0094 lr=3.42e-05 time=18.7s

Эпохи:  93%|█████████▎| 28/30 [07:55<00:34, 17.12s/epoch, beta=0.010, kld=104.218, loss=60.892, lr=2.08e-05, nll=59.895]

2026-05-10 13:49:46.870 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 28: loss=60.8915 nll=59.8953 kld=104.2181 beta=0.0097 lr=2.08e-05 time=12.4s

Эпохи:  97%|█████████▋| 29/30 [08:14<00:17, 17.69s/epoch, beta=0.010, kld=103.542, loss=60.864, lr=1.27e-05, nll=59.839]

2026-05-10 13:50:05.896 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 29: loss=60.8643 nll=59.8386 kld=103.5423 beta=0.0101 lr=1.27e-05 time=19.0s

Эпохи: 100%|██████████| 30/30 [08:34<00:00, 17.14s/epoch, beta=0.010, kld=102.639, loss=60.895, lr=1.00e-05, nll=59.842]

2026-05-10 13:50:25.567 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 30: loss=60.8946 nll=59.8421 kld=102.6388 beta=0.0104 lr=1.00e-05 time=19.7s
2026-05-10 13:50:25.740 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_3cgwfyz2\artifacts\model.pt
2026-05-10 13:50:26.678 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_3cgwfyz2\artifacts
2026-05-10 13:50:27.028 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda
2026-05-10 13:50:27.038 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_3cgwfyz2\artifacts\model.pt
  Trial 0: target=sqrt_target, dims=[600,64], dropout=0.6, beta=0.052, epochs=30, binary=True → NDCG@15=0.202504
2026-05-10 13:50:58.908 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[400, 128], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 13:50:59.017 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:11<00:00, 14928.24user/s]
Эпохи:   4%|▍         | 1/25 [00:18<07:32, 18.86s/epoch, beta=0.001, kld=170.867, loss=139.855, lr=9.96e-04, nll=139.752]

2026-05-10 13:51:29.622 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=139.8553 nll=139.7519 kld=170.8666 beta=0.0009 lr=9.96e-04 time=18.9s

Эпохи:   8%|▊         | 2/25 [00:38<07:21, 19.21s/epoch, beta=0.002, kld=296.530, loss=117.541, lr=9.84e-04, nll=117.121]

2026-05-10 13:51:49.086 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=117.5406 nll=117.1215 kld=296.5302 beta=0.0019 lr=9.84e-04 time=19.5s

Эпохи:  12%|█▏        | 3/25 [00:57<07:03, 19.23s/epoch, beta=0.003, kld=262.309, loss=112.055, lr=9.65e-04, nll=111.436]

2026-05-10 13:52:08.333 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=112.0551 nll=111.4362 kld=262.3088 beta=0.0028 lr=9.65e-04 time=19.2s

Эпохи:  16%|█▌        | 4/25 [01:17<06:45, 19.31s/epoch, beta=0.004, kld=238.029, loss=109.016, lr=9.39e-04, nll=108.228]

2026-05-10 13:52:27.776 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=109.0163 nll=108.2284 kld=238.0290 beta=0.0038 lr=9.39e-04 time=19.4s

Эпохи:  20%|██        | 5/25 [01:36<06:27, 19.35s/epoch, beta=0.005, kld=223.005, loss=107.083, lr=9.05e-04, nll=106.132]

2026-05-10 13:52:47.192 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=107.0825 nll=106.1324 kld=223.0050 beta=0.0047 lr=9.05e-04 time=19.4s

Эпохи:  24%|██▍       | 6/25 [01:55<06:07, 19.36s/epoch, beta=0.006, kld=211.903, loss=105.840, lr=8.66e-04, nll=104.736]

2026-05-10 13:53:06.579 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=105.8402 nll=104.7364 kld=211.9031 beta=0.0057 lr=8.66e-04 time=19.4s

Эпохи:  28%|██▊       | 7/25 [02:15<05:49, 19.39s/epoch, beta=0.007, kld=203.043, loss=105.118, lr=8.21e-04, nll=103.868]

2026-05-10 13:53:26.035 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=105.1179 nll=103.8682 kld=203.0429 beta=0.0066 lr=8.21e-04 time=19.5s

Эпохи:  32%|███▏      | 8/25 [02:34<05:29, 19.40s/epoch, beta=0.008, kld=194.983, loss=104.545, lr=7.70e-04, nll=103.160]

2026-05-10 13:53:45.455 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=104.5449 nll=103.1598 kld=194.9835 beta=0.0076 lr=7.70e-04 time=19.4s

Эпохи:  36%|███▌      | 9/25 [02:54<05:10, 19.42s/epoch, beta=0.009, kld=187.506, loss=104.020, lr=7.16e-04, nll=102.511]

2026-05-10 13:54:04.914 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=104.0205 nll=102.5109 kld=187.5059 beta=0.0085 lr=7.16e-04 time=19.5s

Эпохи:  40%|████      | 10/25 [03:13<04:51, 19.41s/epoch, beta=0.009, kld=181.159, loss=103.602, lr=6.58e-04, nll=101.972]

2026-05-10 13:54:24.302 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=103.6020 nll=101.9717 kld=181.1590 beta=0.0095 lr=6.58e-04 time=19.4s

Эпохи:  44%|████▍     | 11/25 [03:32<04:28, 19.17s/epoch, beta=0.010, kld=176.140, loss=103.146, lr=5.98e-04, nll=101.394]

2026-05-10 13:54:42.945 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 11: loss=103.1460 nll=101.3941 kld=176.1405 beta=0.0104 lr=5.98e-04 time=18.6s

Эпохи:  48%|████▊     | 12/25 [03:51<04:08, 19.15s/epoch, beta=0.011, kld=171.108, loss=102.772, lr=5.36e-04, nll=100.908]

2026-05-10 13:55:02.027 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 12: loss=102.7715 nll=100.9075 kld=171.1076 beta=0.0114 lr=5.36e-04 time=19.1s

Эпохи:  52%|█████▏    | 13/25 [04:10<03:50, 19.21s/epoch, beta=0.012, kld=166.302, loss=102.455, lr=4.74e-04, nll=100.486]

2026-05-10 13:55:21.370 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 13: loss=102.4553 nll=100.4861 kld=166.3020 beta=0.0123 lr=4.74e-04 time=19.3s

Эпохи:  56%|█████▌    | 14/25 [04:29<03:31, 19.26s/epoch, beta=0.013, kld=161.985, loss=102.153, lr=4.12e-04, nll=100.082]

2026-05-10 13:55:40.752 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 14: loss=102.1533 nll=100.0818 kld=161.9851 beta=0.0133 lr=4.12e-04 time=19.4s

Эпохи:  60%|██████    | 15/25 [04:49<03:13, 19.31s/epoch, beta=0.014, kld=157.505, loss=101.812, lr=3.52e-04, nll=99.649]

2026-05-10 13:56:00.163 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 15: loss=101.8123 nll=99.6487 kld=157.5048 beta=0.0142 lr=3.52e-04 time=19.4s

Эпохи:  64%|██████▍   | 16/25 [05:08<02:54, 19.34s/epoch, beta=0.015, kld=153.891, loss=101.772, lr=2.94e-04, nll=99.512]

2026-05-10 13:56:19.571 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 16: loss=101.7722 nll=99.5123 kld=153.8912 beta=0.0152 lr=2.94e-04 time=19.4s

Эпохи:  68%|██████▊   | 17/25 [05:25<02:28, 18.58s/epoch, beta=0.016, kld=150.672, loss=101.511, lr=2.40e-04, nll=99.156]

2026-05-10 13:56:36.399 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 17: loss=101.5109 nll=99.1556 kld=150.6719 beta=0.0161 lr=2.40e-04 time=16.8s

Эпохи:  72%|███████▏  | 18/25 [05:39<01:59, 17.06s/epoch, beta=0.017, kld=146.699, loss=101.375, lr=1.89e-04, nll=98.942]

2026-05-10 13:56:49.904 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 18: loss=101.3745 nll=98.9423 kld=146.6992 beta=0.0171 lr=1.89e-04 time=13.5s

Эпохи:  76%|███████▌  | 19/25 [05:50<01:31, 15.23s/epoch, beta=0.018, kld=144.084, loss=101.253, lr=1.44e-04, nll=98.728]

2026-05-10 13:57:00.886 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 19: loss=101.2531 nll=98.7278 kld=144.0841 beta=0.0180 lr=1.44e-04 time=11.0s

Эпохи:  80%|████████  | 20/25 [06:02<01:11, 14.23s/epoch, beta=0.019, kld=140.839, loss=101.207, lr=1.05e-04, nll=98.605]

2026-05-10 13:57:12.795 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 20: loss=101.2072 nll=98.6053 kld=140.8391 beta=0.0189 lr=1.05e-04 time=11.9s

Эпохи:  84%|████████▍ | 21/25 [06:20<01:02, 15.63s/epoch, beta=0.020, kld=138.526, loss=101.263, lr=7.12e-05, nll=98.573]

2026-05-10 13:57:31.666 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 21: loss=101.2629 nll=98.5726 kld=138.5263 beta=0.0199 lr=7.12e-05 time=18.9s

Эпохи:  88%|████████▊ | 22/25 [06:40<00:50, 16.69s/epoch, beta=0.021, kld=135.869, loss=101.211, lr=4.48e-05, nll=98.444]

2026-05-10 13:57:50.829 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 22: loss=101.2112 nll=98.4435 kld=135.8694 beta=0.0208 lr=4.48e-05 time=19.2s

Эпохи:  92%|█████████▏| 23/25 [06:59<00:35, 17.51s/epoch, beta=0.022, kld=133.928, loss=101.316, lr=2.56e-05, nll=98.461]

2026-05-10 13:58:10.244 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 23: loss=101.3162 nll=98.4613 kld=133.9281 beta=0.0218 lr=2.56e-05 time=19.4s

Эпохи:  96%|█████████▌| 24/25 [07:18<00:18, 18.10s/epoch, beta=0.023, kld=132.124, loss=101.321, lr=1.39e-05, nll=98.379]

2026-05-10 13:58:29.729 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 24: loss=101.3209 nll=98.3791 kld=132.1242 beta=0.0227 lr=1.39e-05 time=19.5s

Эпохи: 100%|██████████| 25/25 [07:38<00:00, 18.33s/epoch, beta=0.024, kld=130.553, loss=101.417, lr=1.00e-05, nll=98.387]

2026-05-10 13:58:49.137 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 25: loss=101.4171 nll=98.3867 kld=130.5526 beta=0.0237 lr=1.00e-05 time=19.4s
2026-05-10 13:58:49.282 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_o67xubjz\artifacts\model.pt
2026-05-10 13:58:50.455 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_o67xubjz\artifacts
2026-05-10 13:58:50.746 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[400, 128], device=cuda
2026-05-10 13:58:50.754 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_o67xubjz\artifacts\model.pt
  Trial 1: target=sqrt_target, dims=[400,128], dropout=0.4, beta=0.143, epochs=25, binary=False → NDCG@15=0.206498
2026-05-10 13:59:21.866 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[400, 256], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 13:59:21.969 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:10<00:00, 15639.92user/s]
Эпохи:   5%|▌         | 1/20 [00:18<05:58, 18.88s/epoch, beta=0.002, kld=187.884, loss=93.767, lr=9.94e-04, nll=93.587]

2026-05-10 13:59:52.086 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=93.7673 nll=93.5872 kld=187.8836 beta=0.0016 lr=9.94e-04 time=18.9s

Эпохи:  10%|█         | 2/20 [00:38<05:45, 19.20s/epoch, beta=0.003, kld=268.728, loss=76.753, lr=9.76e-04, nll=76.113]

2026-05-10 14:00:11.504 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=76.7525 nll=76.1134 kld=268.7283 beta=0.0032 lr=9.76e-04 time=19.4s

Эпохи:  15%|█▌        | 3/20 [00:56<05:21, 18.91s/epoch, beta=0.005, kld=227.921, loss=72.527, lr=9.46e-04, nll=71.619]

2026-05-10 14:00:30.064 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=72.5274 nll=71.6187 kld=227.9209 beta=0.0048 lr=9.46e-04 time=18.6s

Эпохи:  20%|██        | 4/20 [01:16<05:04, 19.03s/epoch, beta=0.006, kld=203.259, loss=70.495, lr=9.05e-04, nll=69.358]

2026-05-10 14:00:49.288 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=70.4948 nll=69.3578 kld=203.2591 beta=0.0064 lr=9.05e-04 time=19.2s

Эпохи:  25%|██▌       | 5/20 [01:35<04:47, 19.18s/epoch, beta=0.008, kld=185.711, loss=69.266, lr=8.55e-04, nll=67.929]

2026-05-10 14:01:08.717 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=69.2658 nll=67.9285 kld=185.7107 beta=0.0080 lr=8.55e-04 time=19.4s

Эпохи:  30%|███       | 6/20 [01:54<04:29, 19.25s/epoch, beta=0.010, kld=171.668, loss=68.487, lr=7.96e-04, nll=66.976]

2026-05-10 14:01:28.114 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=68.4873 nll=66.9759 kld=171.6676 beta=0.0096 lr=7.96e-04 time=19.4s

Эпохи:  35%|███▌      | 7/20 [02:14<04:10, 19.30s/epoch, beta=0.011, kld=159.645, loss=68.011, lr=7.30e-04, nll=66.349]

2026-05-10 14:01:47.509 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=68.0106 nll=66.3495 kld=159.6447 beta=0.0112 lr=7.30e-04 time=19.4s

Эпохи:  40%|████      | 8/20 [02:33<03:51, 19.30s/epoch, beta=0.013, kld=149.106, loss=67.647, lr=6.58e-04, nll=65.856]

2026-05-10 14:02:06.829 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=67.6467 nll=65.8562 kld=149.1062 beta=0.0128 lr=6.58e-04 time=19.3s

Эпохи:  45%|████▌     | 9/20 [02:53<03:32, 19.34s/epoch, beta=0.014, kld=140.528, loss=67.390, lr=5.82e-04, nll=65.477]

2026-05-10 14:02:26.246 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=67.3905 nll=65.4775 kld=140.5282 beta=0.0144 lr=5.82e-04 time=19.4s

Эпохи:  50%|█████     | 10/20 [03:12<03:13, 19.35s/epoch, beta=0.016, kld=132.831, loss=67.085, lr=5.05e-04, nll=65.064]

2026-05-10 14:02:45.609 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=67.0850 nll=65.0641 kld=132.8307 beta=0.0160 lr=5.05e-04 time=19.4s

Эпохи:  55%|█████▌    | 11/20 [03:31<02:54, 19.37s/epoch, beta=0.018, kld=126.193, loss=66.859, lr=4.28e-04, nll=64.737]

2026-05-10 14:03:05.045 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 11: loss=66.8590 nll=64.7366 kld=126.1928 beta=0.0176 lr=4.28e-04 time=19.4s

Эпохи:  60%|██████    | 12/20 [03:51<02:34, 19.36s/epoch, beta=0.019, kld=120.239, loss=66.644, lr=3.52e-04, nll=64.429]

2026-05-10 14:03:24.375 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 12: loss=66.6440 nll=64.4292 kld=120.2387 beta=0.0192 lr=3.52e-04 time=19.3s

Эпохи:  65%|██████▌   | 13/20 [04:09<02:13, 19.10s/epoch, beta=0.021, kld=114.847, loss=66.527, lr=2.80e-04, nll=64.227]

2026-05-10 14:03:42.876 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 13: loss=66.5268 nll=64.2273 kld=114.8472 beta=0.0208 lr=2.80e-04 time=18.5s

Эпохи:  70%|███████   | 14/20 [04:29<01:55, 19.20s/epoch, beta=0.022, kld=110.279, loss=66.385, lr=2.14e-04, nll=64.000]

2026-05-10 14:04:02.318 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 14: loss=66.3852 nll=64.0002 kld=110.2789 beta=0.0224 lr=2.14e-04 time=19.4s

Эпохи:  75%|███████▌  | 15/20 [04:48<01:36, 19.24s/epoch, beta=0.024, kld=106.465, loss=66.373, lr=1.55e-04, nll=63.900]

2026-05-10 14:04:21.654 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 15: loss=66.3728 nll=63.8999 kld=106.4648 beta=0.0240 lr=1.55e-04 time=19.3s

Эпохи:  80%|████████  | 16/20 [05:07<01:17, 19.31s/epoch, beta=0.026, kld=102.918, loss=66.405, lr=1.05e-04, nll=63.849]

2026-05-10 14:04:41.102 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 16: loss=66.4046 nll=63.8490 kld=102.9176 beta=0.0256 lr=1.05e-04 time=19.4s

Эпохи:  85%|████████▌ | 17/20 [05:27<00:58, 19.35s/epoch, beta=0.027, kld=99.939, loss=66.398, lr=6.40e-05, nll=63.756]

2026-05-10 14:05:00.568 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 17: loss=66.3977 nll=63.7560 kld=99.9388 beta=0.0272 lr=6.40e-05 time=19.5s

Эпохи:  90%|█████████ | 18/20 [05:46<00:38, 19.37s/epoch, beta=0.029, kld=97.123, loss=66.466, lr=3.42e-05, nll=63.743]

2026-05-10 14:05:19.972 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 18: loss=66.4660 nll=63.7430 kld=97.1225 beta=0.0288 lr=3.42e-05 time=19.4s

Эпохи:  95%|█████████▌| 19/20 [06:04<00:18, 18.96s/epoch, beta=0.030, kld=95.301, loss=66.521, lr=1.61e-05, nll=63.696]

2026-05-10 14:05:37.976 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 19: loss=66.5206 nll=63.6959 kld=95.3010 beta=0.0304 lr=1.61e-05 time=18.0s

Эпохи: 100%|██████████| 20/20 [06:18<00:00, 18.92s/epoch, beta=0.032, kld=93.360, loss=66.660, lr=1.00e-05, nll=63.743]

2026-05-10 14:05:51.526 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 20: loss=66.6600 nll=63.7432 kld=93.3601 beta=0.0320 lr=1.00e-05 time=13.5s
2026-05-10 14:05:51.624 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_lf7wgjbm\artifacts\model.pt
2026-05-10 14:05:52.405 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_lf7wgjbm\artifacts
2026-05-10 14:05:52.575 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[400, 256], device=cuda
2026-05-10 14:05:52.581 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_lf7wgjbm\artifacts\model.pt
  Trial 2: target=log_target, dims=[400,256], dropout=0.2, beta=0.242, epochs=20, binary=False → NDCG@15=0.201925
2026-05-10 14:06:14.802 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[800, 128], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 14:06:14.873 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:04<00:00, 38816.83user/s]
Эпохи:   3%|▎         | 1/30 [00:13<06:29, 13.42s/epoch, beta=0.003, kld=179.905, loss=136.956, lr=9.97e-04, nll=136.638]

2026-05-10 14:06:32.884 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=136.9564 nll=136.6380 kld=179.9046 beta=0.0029 lr=9.97e-04 time=13.4s

Эпохи:   7%|▋         | 2/30 [00:26<06:13, 13.32s/epoch, beta=0.006, kld=212.416, loss=120.794, lr=9.89e-04, nll=119.887]

2026-05-10 14:06:46.140 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=120.7938 nll=119.8875 kld=212.4163 beta=0.0058 lr=9.89e-04 time=13.3s

Эпохи:  10%|█         | 3/30 [00:39<05:58, 13.29s/epoch, beta=0.009, kld=175.145, loss=117.461, lr=9.76e-04, nll=116.204]

2026-05-10 14:06:59.396 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=117.4607 nll=116.2041 kld=175.1451 beta=0.0087 lr=9.76e-04 time=13.3s

Эпохи:  13%|█▎        | 4/30 [00:53<05:46, 13.34s/epoch, beta=0.012, kld=154.420, loss=115.739, lr=9.57e-04, nll=114.184]

2026-05-10 14:07:12.816 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=115.7387 nll=114.1843 kld=154.4198 beta=0.0115 lr=9.57e-04 time=13.4s

Эпохи:  17%|█▋        | 5/30 [01:06<05:33, 13.33s/epoch, beta=0.014, kld=140.293, loss=114.958, lr=9.34e-04, nll=113.140]

2026-05-10 14:07:26.111 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=114.9579 nll=113.1397 kld=140.2925 beta=0.0144 lr=9.34e-04 time=13.3s

Эпохи:  20%|██        | 6/30 [01:19<05:19, 13.32s/epoch, beta=0.017, kld=128.172, loss=114.259, lr=9.05e-04, nll=112.228]

2026-05-10 14:07:39.426 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=114.2593 nll=112.2284 kld=128.1716 beta=0.0173 lr=9.05e-04 time=13.3s

Эпохи:  23%|██▎       | 7/30 [01:33<05:06, 13.31s/epoch, beta=0.020, kld=119.598, loss=113.944, lr=8.73e-04, nll=111.705]

2026-05-10 14:07:52.712 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=113.9445 nll=111.7048 kld=119.5982 beta=0.0202 lr=8.73e-04 time=13.3s

Эпохи:  27%|██▋       | 8/30 [01:46<04:54, 13.39s/epoch, beta=0.023, kld=111.533, loss=113.752, lr=8.36e-04, nll=111.341]

2026-05-10 14:08:06.271 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=113.7520 nll=111.3409 kld=111.5326 beta=0.0231 lr=8.36e-04 time=13.6s

Эпохи:  30%|███       | 9/30 [02:00<04:41, 13.40s/epoch, beta=0.026, kld=104.462, loss=113.343, lr=7.96e-04, nll=110.784]

2026-05-10 14:08:19.683 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=113.3432 nll=110.7838 kld=104.4618 beta=0.0260 lr=7.96e-04 time=13.4s

Эпохи:  33%|███▎      | 10/30 [02:13<04:29, 13.46s/epoch, beta=0.029, kld=97.971, loss=113.156, lr=7.52e-04, nll=110.472]

2026-05-10 14:08:33.273 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=113.1556 nll=110.4723 kld=97.9705 beta=0.0288 lr=7.52e-04 time=13.6s

Эпохи:  37%|███▋      | 11/30 [02:27<04:15, 13.45s/epoch, beta=0.032, kld=93.229, loss=112.787, lr=7.06e-04, nll=109.965]

2026-05-10 14:08:46.722 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 11: loss=112.7873 nll=109.9650 kld=93.2291 beta=0.0317 lr=7.06e-04 time=13.4s

Эпохи:  40%|████      | 12/30 [02:40<04:01, 13.44s/epoch, beta=0.035, kld=88.987, loss=112.524, lr=6.58e-04, nll=109.574]

2026-05-10 14:09:00.129 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 12: loss=112.5245 nll=109.5740 kld=88.9867 beta=0.0346 lr=6.58e-04 time=13.4s

Эпохи:  43%|████▎     | 13/30 [02:54<03:48, 13.45s/epoch, beta=0.037, kld=84.446, loss=112.249, lr=6.08e-04, nll=109.206]

2026-05-10 14:09:13.587 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 13: loss=112.2490 nll=109.2058 kld=84.4457 beta=0.0375 lr=6.08e-04 time=13.5s

Эпохи:  47%|████▋     | 14/30 [03:07<03:34, 13.43s/epoch, beta=0.040, kld=80.967, loss=111.977, lr=5.57e-04, nll=108.825]

2026-05-10 14:09:26.985 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 14: loss=111.9772 nll=108.8253 kld=80.9667 beta=0.0404 lr=5.57e-04 time=13.4s

Эпохи:  50%|█████     | 15/30 [03:20<03:21, 13.42s/epoch, beta=0.043, kld=77.498, loss=111.701, lr=5.05e-04, nll=108.461]

2026-05-10 14:09:40.391 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 15: loss=111.7005 nll=108.4608 kld=77.4982 beta=0.0433 lr=5.05e-04 time=13.4s

Эпохи:  53%|█████▎    | 16/30 [03:34<03:08, 13.46s/epoch, beta=0.046, kld=74.787, loss=111.464, lr=4.53e-04, nll=108.121]

2026-05-10 14:09:53.928 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 16: loss=111.4639 nll=108.1212 kld=74.7871 beta=0.0461 lr=4.53e-04 time=13.5s

Эпохи:  57%|█████▋    | 17/30 [03:48<02:55, 13.54s/epoch, beta=0.049, kld=72.373, loss=111.264, lr=4.02e-04, nll=107.820]

2026-05-10 14:10:07.643 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 17: loss=111.2636 nll=107.8202 kld=72.3728 beta=0.0490 lr=4.02e-04 time=13.7s

Эпохи:  60%|██████    | 18/30 [04:01<02:42, 13.53s/epoch, beta=0.052, kld=70.387, loss=111.063, lr=3.52e-04, nll=107.511]

2026-05-10 14:10:21.162 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 18: loss=111.0634 nll=107.5113 kld=70.3867 beta=0.0519 lr=3.52e-04 time=13.5s

Эпохи:  63%|██████▎   | 19/30 [04:15<02:29, 13.58s/epoch, beta=0.055, kld=68.285, loss=110.808, lr=3.04e-04, nll=107.165]

2026-05-10 14:10:34.845 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 19: loss=110.8078 nll=107.1652 kld=68.2850 beta=0.0548 lr=3.04e-04 time=13.7s

Эпохи:  67%|██████▋   | 20/30 [04:28<02:15, 13.59s/epoch, beta=0.058, kld=65.929, loss=110.654, lr=2.57e-04, nll=106.947]

2026-05-10 14:10:48.456 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 20: loss=110.6540 nll=106.9465 kld=65.9293 beta=0.0577 lr=2.57e-04 time=13.6s

Эпохи:  70%|███████   | 21/30 [04:42<02:02, 13.60s/epoch, beta=0.061, kld=64.444, loss=110.547, lr=2.14e-04, nll=106.738]

2026-05-10 14:11:02.078 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 21: loss=110.5475 nll=106.7380 kld=64.4438 beta=0.0606 lr=2.14e-04 time=13.6s

Эпохи:  73%|███████▎  | 22/30 [04:56<01:48, 13.58s/epoch, beta=0.063, kld=62.748, loss=110.459, lr=1.74e-04, nll=106.568]

2026-05-10 14:11:15.607 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 22: loss=110.4587 nll=106.5682 kld=62.7484 beta=0.0634 lr=1.74e-04 time=13.5s

Эпохи:  77%|███████▋  | 23/30 [05:09<01:34, 13.56s/epoch, beta=0.066, kld=61.323, loss=110.359, lr=1.37e-04, nll=106.380]

2026-05-10 14:11:29.120 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 23: loss=110.3591 nll=106.3803 kld=61.3230 beta=0.0663 lr=1.37e-04 time=13.5s

Эпохи:  80%|████████  | 24/30 [05:23<01:21, 13.56s/epoch, beta=0.069, kld=60.126, loss=110.345, lr=1.05e-04, nll=106.271]

2026-05-10 14:11:42.691 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 24: loss=110.3454 nll=106.2705 kld=60.1257 beta=0.0692 lr=1.05e-04 time=13.6s

Эпохи:  83%|████████▎ | 25/30 [05:36<01:07, 13.57s/epoch, beta=0.072, kld=58.766, loss=110.261, lr=7.63e-05, nll=106.109]

2026-05-10 14:11:56.276 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 25: loss=110.2606 nll=106.1086 kld=58.7661 beta=0.0721 lr=7.63e-05 time=13.6s

Эпохи:  87%|████████▋ | 26/30 [05:50<00:54, 13.56s/epoch, beta=0.075, kld=57.510, loss=110.436, lr=5.28e-05, nll=106.207]

2026-05-10 14:12:09.828 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 26: loss=110.4358 nll=106.2067 kld=57.5103 beta=0.0750 lr=5.28e-05 time=13.5s

Эпохи:  90%|█████████ | 27/30 [06:03<00:40, 13.54s/epoch, beta=0.078, kld=56.629, loss=110.423, lr=3.42e-05, nll=106.095]

2026-05-10 14:12:23.308 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 27: loss=110.4230 nll=106.0952 kld=56.6285 beta=0.0779 lr=3.42e-05 time=13.5s

Эпохи:  93%|█████████▎| 28/30 [06:17<00:27, 13.60s/epoch, beta=0.081, kld=55.726, loss=110.416, lr=2.08e-05, nll=105.997]

2026-05-10 14:12:37.052 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 28: loss=110.4164 nll=105.9967 kld=55.7260 beta=0.0807 lr=2.08e-05 time=13.7s

Эпохи:  97%|█████████▋| 29/30 [06:31<00:13, 13.58s/epoch, beta=0.084, kld=54.859, loss=110.530, lr=1.27e-05, nll=106.021]

2026-05-10 14:12:50.593 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 29: loss=110.5302 nll=106.0212 kld=54.8591 beta=0.0836 lr=1.27e-05 time=13.5s

Эпохи: 100%|██████████| 30/30 [06:44<00:00, 13.49s/epoch, beta=0.087, kld=54.311, loss=110.611, lr=1.00e-05, nll=105.990]

2026-05-10 14:13:04.181 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 30: loss=110.6105 nll=105.9899 kld=54.3109 beta=0.0865 lr=1.00e-05 time=13.6s
2026-05-10 14:13:04.344 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_c__ulltz\artifacts\model.pt
2026-05-10 14:13:05.112 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_c__ulltz\artifacts
2026-05-10 14:13:05.370 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[800, 128], device=cuda
2026-05-10 14:13:05.382 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_c__ulltz\artifacts\model.pt
  Trial 3: target=sqrt_target, dims=[800,128], dropout=0.6, beta=0.435, epochs=30, binary=False → NDCG@15=0.206266
2026-05-10 14:13:30.041 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[400, 200], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 14:13:30.118 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:04<00:00, 38536.55user/s]
Эпохи:   3%|▎         | 1/30 [00:12<05:49, 12.05s/epoch, beta=0.000, kld=222.369, loss=142.238, lr=9.97e-04, nll=142.173]

2026-05-10 14:13:46.793 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=142.2378 nll=142.1732 kld=222.3686 beta=0.0005 lr=9.97e-04 time=12.1s

Эпохи:   7%|▋         | 2/30 [00:23<05:33, 11.92s/epoch, beta=0.001, kld=441.050, loss=120.651, lr=9.89e-04, nll=120.347]

2026-05-10 14:13:58.616 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=120.6511 nll=120.3468 kld=441.0498 beta=0.0009 lr=9.89e-04 time=11.8s

Эпохи:  10%|█         | 3/30 [00:35<05:17, 11.76s/epoch, beta=0.001, kld=409.359, loss=115.050, lr=9.76e-04, nll=114.583]

2026-05-10 14:14:10.198 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=115.0501 nll=114.5829 kld=409.3595 beta=0.0014 lr=9.76e-04 time=11.6s

Эпохи:  13%|█▎        | 4/30 [00:46<05:02, 11.63s/epoch, beta=0.002, kld=370.598, loss=112.148, lr=9.57e-04, nll=111.554]

2026-05-10 14:14:21.632 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=112.1482 nll=111.5545 kld=370.5981 beta=0.0018 lr=9.57e-04 time=11.4s

Эпохи:  17%|█▋        | 5/30 [00:58<04:52, 11.70s/epoch, beta=0.002, kld=343.534, loss=110.264, lr=9.34e-04, nll=109.555]

2026-05-10 14:14:33.459 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=110.2640 nll=109.5554 kld=343.5343 beta=0.0023 lr=9.34e-04 time=11.8s

Эпохи:  20%|██        | 6/30 [01:10<04:41, 11.72s/epoch, beta=0.003, kld=324.692, loss=108.936, lr=9.05e-04, nll=108.118]

2026-05-10 14:14:45.199 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=108.9361 nll=108.1178 kld=324.6916 beta=0.0028 lr=9.05e-04 time=11.7s

Эпохи:  23%|██▎       | 7/30 [01:21<04:27, 11.64s/epoch, beta=0.003, kld=311.050, loss=108.123, lr=8.73e-04, nll=107.196]

2026-05-10 14:14:56.691 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=108.1230 nll=107.1962 kld=311.0498 beta=0.0032 lr=8.73e-04 time=11.5s

Эпохи:  27%|██▋       | 8/30 [01:33<04:15, 11.60s/epoch, beta=0.004, kld=297.462, loss=107.476, lr=8.36e-04, nll=106.454]

2026-05-10 14:15:08.210 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=107.4764 nll=106.4536 kld=297.4619 beta=0.0037 lr=8.36e-04 time=11.5s

Эпохи:  30%|███       | 9/30 [01:45<04:03, 11.58s/epoch, beta=0.004, kld=288.320, loss=106.986, lr=7.96e-04, nll=105.863]

2026-05-10 14:15:19.753 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=106.9862 nll=105.8627 kld=288.3204 beta=0.0041 lr=7.96e-04 time=11.5s

Эпохи:  33%|███▎      | 10/30 [01:56<03:50, 11.55s/epoch, beta=0.005, kld=278.779, loss=106.578, lr=7.52e-04, nll=105.364]

2026-05-10 14:15:31.223 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=106.5781 nll=105.3639 kld=278.7793 beta=0.0046 lr=7.52e-04 time=11.5s

Эпохи:  37%|███▋      | 11/30 [02:07<03:38, 11.51s/epoch, beta=0.005, kld=269.549, loss=106.130, lr=7.06e-04, nll=104.832]

2026-05-10 14:15:42.643 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 11: loss=106.1296 nll=104.8319 kld=269.5490 beta=0.0050 lr=7.06e-04 time=11.4s

Эпохи:  40%|████      | 12/30 [02:19<03:27, 11.52s/epoch, beta=0.006, kld=262.731, loss=105.774, lr=6.58e-04, nll=104.389]

2026-05-10 14:15:54.200 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 12: loss=105.7740 nll=104.3886 kld=262.7305 beta=0.0055 lr=6.58e-04 time=11.6s

Эпохи:  43%|████▎     | 13/30 [02:31<03:16, 11.59s/epoch, beta=0.006, kld=256.687, loss=105.483, lr=6.08e-04, nll=104.012]

2026-05-10 14:16:05.934 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 13: loss=105.4833 nll=104.0122 kld=256.6870 beta=0.0060 lr=6.08e-04 time=11.7s

Эпохи:  47%|████▋     | 14/30 [02:42<03:04, 11.54s/epoch, beta=0.006, kld=249.863, loss=105.052, lr=5.57e-04, nll=103.505]

2026-05-10 14:16:17.380 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 14: loss=105.0516 nll=103.5049 kld=249.8630 beta=0.0064 lr=5.57e-04 time=11.4s

Эпохи:  50%|█████     | 15/30 [02:54<02:54, 11.62s/epoch, beta=0.007, kld=243.021, loss=104.748, lr=5.05e-04, nll=103.132]

2026-05-10 14:16:29.161 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 15: loss=104.7478 nll=103.1321 kld=243.0206 beta=0.0069 lr=5.05e-04 time=11.8s

Эпохи:  53%|█████▎    | 16/30 [03:06<02:42, 11.63s/epoch, beta=0.007, kld=236.695, loss=104.554, lr=4.53e-04, nll=102.871]

2026-05-10 14:16:40.826 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 16: loss=104.5535 nll=102.8713 kld=236.6954 beta=0.0073 lr=4.53e-04 time=11.7s

Эпохи:  57%|█████▋    | 17/30 [03:17<02:30, 11.55s/epoch, beta=0.008, kld=232.556, loss=104.281, lr=4.02e-04, nll=102.522]

2026-05-10 14:16:52.200 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 17: loss=104.2813 nll=102.5218 kld=232.5559 beta=0.0078 lr=4.02e-04 time=11.4s

Эпохи:  60%|██████    | 18/30 [03:29<02:18, 11.56s/epoch, beta=0.008, kld=227.630, loss=104.058, lr=3.52e-04, nll=102.232]

2026-05-10 14:17:03.781 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 18: loss=104.0584 nll=102.2318 kld=227.6300 beta=0.0083 lr=3.52e-04 time=11.6s

Эпохи:  63%|██████▎   | 19/30 [03:40<02:06, 11.54s/epoch, beta=0.009, kld=222.728, loss=103.802, lr=3.04e-04, nll=101.912]

2026-05-10 14:17:15.267 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 19: loss=103.8018 nll=101.9124 kld=222.7277 beta=0.0087 lr=3.04e-04 time=11.5s

Эпохи:  67%|██████▋   | 20/30 [03:51<01:54, 11.49s/epoch, beta=0.009, kld=216.955, loss=103.619, lr=2.57e-04, nll=101.679]

2026-05-10 14:17:26.658 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 20: loss=103.6190 nll=101.6790 kld=216.9546 beta=0.0092 lr=2.57e-04 time=11.4s

Эпохи:  70%|███████   | 21/30 [04:03<01:43, 11.51s/epoch, beta=0.010, kld=213.165, loss=103.545, lr=2.14e-04, nll=101.541]

2026-05-10 14:17:38.201 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 21: loss=103.5452 nll=101.5415 kld=213.1648 beta=0.0096 lr=2.14e-04 time=11.5s

Эпохи:  73%|███████▎  | 22/30 [04:14<01:31, 11.49s/epoch, beta=0.010, kld=208.730, loss=103.414, lr=1.74e-04, nll=101.356]

2026-05-10 14:17:49.657 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 22: loss=103.4139 nll=101.3559 kld=208.7302 beta=0.0101 lr=1.74e-04 time=11.5s

Эпохи:  77%|███████▋  | 23/30 [04:26<01:21, 11.60s/epoch, beta=0.011, kld=205.167, loss=103.328, lr=1.37e-04, nll=101.211]

2026-05-10 14:18:01.503 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 23: loss=103.3280 nll=101.2112 kld=205.1666 beta=0.0105 lr=1.37e-04 time=11.8s

Эпохи:  80%|████████  | 24/30 [04:38<01:09, 11.58s/epoch, beta=0.011, kld=201.359, loss=103.255, lr=1.05e-04, nll=101.085]

2026-05-10 14:18:13.030 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 24: loss=103.2547 nll=101.0847 kld=201.3585 beta=0.0110 lr=1.05e-04 time=11.5s

Эпохи:  83%|████████▎ | 25/30 [04:49<00:57, 11.58s/epoch, beta=0.011, kld=197.461, loss=103.127, lr=7.63e-05, nll=100.908]

2026-05-10 14:18:24.617 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 25: loss=103.1267 nll=100.9084 kld=197.4613 beta=0.0115 lr=7.63e-05 time=11.6s

Эпохи:  87%|████████▋ | 26/30 [05:01<00:46, 11.65s/epoch, beta=0.012, kld=194.734, loss=103.238, lr=5.28e-05, nll=100.960]

2026-05-10 14:18:36.436 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 26: loss=103.2376 nll=100.9605 kld=194.7344 beta=0.0119 lr=5.28e-05 time=11.8s

Эпохи:  90%|█████████ | 27/30 [05:13<00:34, 11.63s/epoch, beta=0.012, kld=192.548, loss=103.211, lr=3.42e-05, nll=100.871]

2026-05-10 14:18:48.002 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 27: loss=103.2110 nll=100.8711 kld=192.5477 beta=0.0124 lr=3.42e-05 time=11.6s

Эпохи:  93%|█████████▎| 28/30 [05:24<00:23, 11.60s/epoch, beta=0.013, kld=189.939, loss=103.193, lr=2.08e-05, nll=100.798]

2026-05-10 14:18:59.529 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 28: loss=103.1929 nll=100.7976 kld=189.9388 beta=0.0128 lr=2.08e-05 time=11.5s

Эпохи:  97%|█████████▋| 29/30 [05:36<00:11, 11.61s/epoch, beta=0.013, kld=187.761, loss=103.306, lr=1.27e-05, nll=100.852]

2026-05-10 14:19:11.182 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 29: loss=103.3059 nll=100.8519 kld=187.7613 beta=0.0133 lr=1.27e-05 time=11.7s

Эпохи: 100%|██████████| 30/30 [05:47<00:00, 11.60s/epoch, beta=0.014, kld=186.196, loss=103.317, lr=1.00e-05, nll=100.798]

2026-05-10 14:19:22.652 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 30: loss=103.3167 nll=100.7978 kld=186.1965 beta=0.0138 lr=1.00e-05 time=11.5s
2026-05-10 14:19:22.755 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_cwrc3ml4\artifacts\model.pt
2026-05-10 14:19:23.536 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_cwrc3ml4\artifacts
2026-05-10 14:19:23.695 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[400, 200], device=cuda
2026-05-10 14:19:23.701 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_cwrc3ml4\artifacts\model.pt
  Trial 4: target=sqrt_target, dims=[400,200], dropout=0.5, beta=0.069, epochs=30, binary=False → NDCG@15=0.203279
2026-05-10 14:19:47.986 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[400, 128], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 14:19:48.062 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:04<00:00, 38571.28user/s]
Эпохи:   4%|▍         | 1/25 [00:12<04:48, 12.03s/epoch, beta=0.002, kld=135.319, loss=78.758, lr=9.96e-04, nll=78.563]

2026-05-10 14:20:04.713 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=78.7576 nll=78.5626 kld=135.3193 beta=0.0024 lr=9.96e-04 time=12.0s

Эпохи:   8%|▊         | 2/25 [00:23<04:28, 11.69s/epoch, beta=0.005, kld=170.986, loss=64.702, lr=9.84e-04, nll=64.086]

2026-05-10 14:20:16.168 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=64.7016 nll=64.0861 kld=170.9862 beta=0.0048 lr=9.84e-04 time=11.5s

Эпохи:  12%|█▏        | 3/25 [00:35<04:16, 11.66s/epoch, beta=0.007, kld=151.328, loss=61.511, lr=9.65e-04, nll=60.599]

2026-05-10 14:20:27.798 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=61.5107 nll=60.5987 kld=151.3281 beta=0.0073 lr=9.65e-04 time=11.6s

Эпохи:  16%|█▌        | 4/25 [00:46<04:05, 11.69s/epoch, beta=0.010, kld=137.617, loss=60.028, lr=9.39e-04, nll=58.866]

2026-05-10 14:20:39.521 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=60.0282 nll=58.8656 kld=137.6168 beta=0.0097 lr=9.39e-04 time=11.7s

Эпохи:  20%|██        | 5/25 [00:58<03:52, 11.62s/epoch, beta=0.012, kld=127.107, loss=59.154, lr=9.05e-04, nll=57.773]

2026-05-10 14:20:51.034 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=59.1543 nll=57.7727 kld=127.1075 beta=0.0121 lr=9.05e-04 time=11.5s

Эпохи:  24%|██▍       | 6/25 [01:09<03:40, 11.61s/epoch, beta=0.015, kld=118.257, loss=58.595, lr=8.66e-04, nll=57.024]

2026-05-10 14:21:02.625 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=58.5951 nll=57.0235 kld=118.2575 beta=0.0145 lr=8.66e-04 time=11.6s

Эпохи:  28%|██▊       | 7/25 [01:21<03:27, 11.55s/epoch, beta=0.017, kld=110.689, loss=58.207, lr=8.21e-04, nll=56.468]

2026-05-10 14:21:14.047 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=58.2071 nll=56.4682 kld=110.6894 beta=0.0169 lr=8.21e-04 time=11.4s

Эпохи:  32%|███▏      | 8/25 [01:32<03:15, 11.50s/epoch, beta=0.019, kld=104.108, loss=57.897, lr=7.70e-04, nll=56.010]

2026-05-10 14:21:25.451 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=57.8971 nll=56.0097 kld=104.1082 beta=0.0193 lr=7.70e-04 time=11.4s

Эпохи:  36%|███▌      | 9/25 [01:44<03:04, 11.51s/epoch, beta=0.022, kld=98.490, loss=57.668, lr=7.16e-04, nll=55.644]

2026-05-10 14:21:36.976 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=57.6680 nll=55.6439 kld=98.4899 beta=0.0218 lr=7.16e-04 time=11.5s

Эпохи:  40%|████      | 10/25 [01:55<02:52, 11.52s/epoch, beta=0.024, kld=93.583, loss=57.491, lr=6.58e-04, nll=55.342]

2026-05-10 14:21:48.527 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=57.4915 nll=55.3421 kld=93.5829 beta=0.0242 lr=6.58e-04 time=11.5s

Эпохи:  44%|████▍     | 11/25 [02:07<02:42, 11.64s/epoch, beta=0.027, kld=89.082, loss=57.361, lr=5.98e-04, nll=55.100]

2026-05-10 14:22:00.424 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 11: loss=57.3613 nll=55.0996 kld=89.0823 beta=0.0266 lr=5.98e-04 time=11.9s

Эпохи:  48%|████▊     | 12/25 [02:19<02:30, 11.58s/epoch, beta=0.029, kld=85.027, loss=57.248, lr=5.36e-04, nll=54.884]

2026-05-10 14:22:11.877 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 12: loss=57.2484 nll=54.8839 kld=85.0267 beta=0.0290 lr=5.36e-04 time=11.5s

Эпохи:  52%|█████▏    | 13/25 [02:30<02:18, 11.54s/epoch, beta=0.031, kld=81.502, loss=57.170, lr=4.74e-04, nll=54.707]

2026-05-10 14:22:23.326 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 13: loss=57.1704 nll=54.7068 kld=81.5022 beta=0.0314 lr=4.74e-04 time=11.4s

Эпохи:  56%|█████▌    | 14/25 [02:42<02:07, 11.62s/epoch, beta=0.034, kld=78.417, loss=57.116, lr=4.12e-04, nll=54.555]

2026-05-10 14:22:35.126 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 14: loss=57.1156 nll=54.5554 kld=78.4168 beta=0.0339 lr=4.12e-04 time=11.8s

Эпохи:  60%|██████    | 15/25 [02:53<01:55, 11.58s/epoch, beta=0.036, kld=75.605, loss=57.089, lr=3.52e-04, nll=54.438]

2026-05-10 14:22:46.619 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 15: loss=57.0892 nll=54.4381 kld=75.6046 beta=0.0363 lr=3.52e-04 time=11.5s

Эпохи:  64%|██████▍   | 16/25 [03:05<01:44, 11.56s/epoch, beta=0.039, kld=73.085, loss=57.093, lr=2.94e-04, nll=54.353]

2026-05-10 14:22:58.121 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 16: loss=57.0928 nll=54.3532 kld=73.0846 beta=0.0387 lr=2.94e-04 time=11.5s

Эпохи:  68%|██████▊   | 17/25 [03:17<01:32, 11.57s/epoch, beta=0.041, kld=70.767, loss=57.079, lr=2.40e-04, nll=54.255]

2026-05-10 14:23:09.728 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 17: loss=57.0786 nll=54.2547 kld=70.7669 beta=0.0411 lr=2.40e-04 time=11.6s

Эпохи:  72%|███████▏  | 18/25 [03:28<01:20, 11.57s/epoch, beta=0.044, kld=68.805, loss=57.130, lr=1.89e-04, nll=54.218]

2026-05-10 14:23:21.291 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 18: loss=57.1301 nll=54.2179 kld=68.8046 beta=0.0435 lr=1.89e-04 time=11.6s

Эпохи:  76%|███████▌  | 19/25 [03:40<01:09, 11.54s/epoch, beta=0.046, kld=67.039, loss=57.151, lr=1.44e-04, nll=54.151]

2026-05-10 14:23:32.749 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 19: loss=57.1506 nll=54.1511 kld=67.0393 beta=0.0460 lr=1.44e-04 time=11.5s

Эпохи:  80%|████████  | 20/25 [03:51<00:57, 11.51s/epoch, beta=0.048, kld=65.324, loss=57.243, lr=1.05e-04, nll=54.162]

2026-05-10 14:23:44.209 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 20: loss=57.2429 nll=54.1620 kld=65.3237 beta=0.0484 lr=1.05e-04 time=11.5s

Эпохи:  84%|████████▍ | 21/25 [04:03<00:46, 11.58s/epoch, beta=0.051, kld=63.902, loss=57.294, lr=7.12e-05, nll=54.126]

2026-05-10 14:23:55.957 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 21: loss=57.2941 nll=54.1260 kld=63.9016 beta=0.0508 lr=7.12e-05 time=11.7s

Эпохи:  88%|████████▊ | 22/25 [04:14<00:34, 11.57s/epoch, beta=0.053, kld=62.533, loss=57.408, lr=4.48e-05, nll=54.156]

2026-05-10 14:24:07.496 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 22: loss=57.4077 nll=54.1559 kld=62.5331 beta=0.0532 lr=4.48e-05 time=11.5s

Эпохи:  92%|█████████▏| 23/25 [04:26<00:23, 11.57s/epoch, beta=0.056, kld=61.384, loss=57.515, lr=2.56e-05, nll=54.174]

2026-05-10 14:24:19.053 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 23: loss=57.5146 nll=54.1741 kld=61.3842 beta=0.0556 lr=2.56e-05 time=11.6s

Эпохи:  96%|█████████▌| 24/25 [04:38<00:11, 11.66s/epoch, beta=0.058, kld=60.403, loss=57.617, lr=1.39e-05, nll=54.183]

2026-05-10 14:24:30.924 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 24: loss=57.6166 nll=54.1833 kld=60.4028 beta=0.0580 lr=1.39e-05 time=11.9s

Эпохи: 100%|██████████| 25/25 [04:49<00:00, 11.60s/epoch, beta=0.060, kld=59.530, loss=57.755, lr=1.00e-05, nll=54.228]

2026-05-10 14:24:42.576 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 25: loss=57.7555 nll=54.2278 kld=59.5304 beta=0.0605 lr=1.00e-05 time=11.6s
2026-05-10 14:24:42.679 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_b43w0tjz\artifacts\model.pt
2026-05-10 14:24:43.272 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_b43w0tjz\artifacts
2026-05-10 14:24:43.437 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[400, 128], device=cuda
2026-05-10 14:24:43.444 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_b43w0tjz\artifacts\model.pt
  Trial 5: target=log_target, dims=[400,128], dropout=0.2, beta=0.365, epochs=25, binary=True → NDCG@15=0.201903
2026-05-10 14:25:07.870 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[800, 200], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 14:25:07.943 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:04<00:00, 39101.33user/s]
Эпохи:   5%|▌         | 1/20 [00:13<04:20, 13.69s/epoch, beta=0.002, kld=220.723, loss=75.837, lr=9.94e-04, nll=75.580]

2026-05-10 14:25:26.199 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=75.8367 nll=75.5804 kld=220.7234 beta=0.0020 lr=9.94e-04 time=13.7s

Эпохи:  10%|█         | 2/20 [00:27<04:03, 13.53s/epoch, beta=0.004, kld=220.658, loss=66.093, lr=9.76e-04, nll=65.456]

2026-05-10 14:25:39.611 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=66.0931 nll=65.4558 kld=220.6579 beta=0.0039 lr=9.76e-04 time=13.4s

Эпохи:  15%|█▌        | 3/20 [00:40<03:49, 13.48s/epoch, beta=0.006, kld=176.065, loss=64.478, lr=9.46e-04, nll=63.621]

2026-05-10 14:25:53.034 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=64.4778 nll=63.6215 kld=176.0647 beta=0.0059 lr=9.46e-04 time=13.4s

Эпохи:  20%|██        | 4/20 [00:54<03:37, 13.60s/epoch, beta=0.008, kld=151.676, loss=63.704, lr=9.05e-04, nll=62.668]

2026-05-10 14:26:06.807 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=63.7037 nll=62.6681 kld=151.6762 beta=0.0078 lr=9.05e-04 time=13.8s

Эпохи:  25%|██▌       | 5/20 [01:07<03:23, 13.55s/epoch, beta=0.010, kld=135.969, loss=63.208, lr=8.55e-04, nll=62.012]

2026-05-10 14:26:20.285 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=63.2075 nll=62.0123 kld=135.9688 beta=0.0098 lr=8.55e-04 time=13.5s

Эпохи:  30%|███       | 6/20 [01:21<03:10, 13.62s/epoch, beta=0.012, kld=124.449, loss=62.830, lr=7.96e-04, nll=61.493]

2026-05-10 14:26:34.048 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=62.8302 nll=61.4927 kld=124.4489 beta=0.0117 lr=7.96e-04 time=13.8s

Эпохи:  35%|███▌      | 7/20 [01:35<02:56, 13.59s/epoch, beta=0.014, kld=115.434, loss=62.573, lr=7.30e-04, nll=61.106]

2026-05-10 14:26:47.580 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=62.5726 nll=61.1061 kld=115.4343 beta=0.0137 lr=7.30e-04 time=13.5s

Эпохи:  40%|████      | 8/20 [01:48<02:43, 13.60s/epoch, beta=0.016, kld=107.271, loss=62.282, lr=6.58e-04, nll=60.709]

2026-05-10 14:27:01.177 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=62.2822 nll=60.7093 kld=107.2711 beta=0.0157 lr=6.58e-04 time=13.6s

Эпохи:  45%|████▌     | 9/20 [02:02<02:29, 13.61s/epoch, beta=0.018, kld=100.769, loss=62.026, lr=5.82e-04, nll=60.351]

2026-05-10 14:27:14.827 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=62.0262 nll=60.3513 kld=100.7688 beta=0.0176 lr=5.82e-04 time=13.6s

Эпохи:  50%|█████     | 10/20 [02:15<02:15, 13.59s/epoch, beta=0.020, kld=95.246, loss=61.805, lr=5.05e-04, nll=60.036]

2026-05-10 14:27:28.377 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=61.8052 nll=60.0358 kld=95.2460 beta=0.0196 lr=5.05e-04 time=13.5s

Эпохи:  55%|█████▌    | 11/20 [02:29<02:02, 13.58s/epoch, beta=0.022, kld=90.397, loss=61.653, lr=4.28e-04, nll=59.797]

2026-05-10 14:27:41.928 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 11: loss=61.6534 nll=59.7970 kld=90.3973 beta=0.0215 lr=4.28e-04 time=13.5s

Эпохи:  60%|██████    | 12/20 [02:43<01:49, 13.64s/epoch, beta=0.023, kld=86.561, loss=61.448, lr=3.52e-04, nll=59.501]

2026-05-10 14:27:55.690 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 12: loss=61.4478 nll=59.5007 kld=86.5607 beta=0.0235 lr=3.52e-04 time=13.8s

Эпохи:  65%|██████▌   | 13/20 [02:56<01:35, 13.65s/epoch, beta=0.025, kld=82.764, loss=61.334, lr=2.80e-04, nll=59.310]

2026-05-10 14:28:09.377 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 13: loss=61.3338 nll=59.3103 kld=82.7642 beta=0.0254 lr=2.80e-04 time=13.7s

Эпохи:  70%|███████   | 14/20 [03:10<01:21, 13.64s/epoch, beta=0.027, kld=79.649, loss=61.230, lr=2.14e-04, nll=59.126]

2026-05-10 14:28:22.976 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 14: loss=61.2297 nll=59.1264 kld=79.6488 beta=0.0274 lr=2.14e-04 time=13.6s

Эпохи:  75%|███████▌  | 15/20 [03:24<01:08, 13.71s/epoch, beta=0.029, kld=77.018, loss=61.184, lr=1.55e-04, nll=59.000]

2026-05-10 14:28:36.846 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 15: loss=61.1845 nll=59.0001 kld=77.0184 beta=0.0293 lr=1.55e-04 time=13.9s

Эпохи:  80%|████████  | 16/20 [03:38<00:55, 13.76s/epoch, beta=0.031, kld=74.431, loss=61.156, lr=1.05e-04, nll=58.899]

2026-05-10 14:28:50.739 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 16: loss=61.1562 nll=58.8995 kld=74.4309 beta=0.0313 lr=1.05e-04 time=13.9s

Эпохи:  85%|████████▌ | 17/20 [03:51<00:41, 13.75s/epoch, beta=0.033, kld=72.470, loss=61.196, lr=6.40e-05, nll=58.857]

2026-05-10 14:29:04.458 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 17: loss=61.1959 nll=58.8568 kld=72.4698 beta=0.0333 lr=6.40e-05 time=13.7s

Эпохи:  90%|█████████ | 18/20 [04:05<00:27, 13.71s/epoch, beta=0.035, kld=70.760, loss=61.232, lr=3.42e-05, nll=58.809]

2026-05-10 14:29:18.067 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 18: loss=61.2319 nll=58.8094 kld=70.7597 beta=0.0352 lr=3.42e-05 time=13.6s

Эпохи:  95%|█████████▌| 19/20 [04:19<00:13, 13.70s/epoch, beta=0.037, kld=69.316, loss=61.262, lr=1.61e-05, nll=58.754]

2026-05-10 14:29:31.741 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 19: loss=61.2625 nll=58.7539 kld=69.3162 beta=0.0372 lr=1.61e-05 time=13.7s

Эпохи: 100%|██████████| 20/20 [04:32<00:00, 13.64s/epoch, beta=0.039, kld=68.110, loss=61.402, lr=1.00e-05, nll=58.803]

2026-05-10 14:29:45.385 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 20: loss=61.4018 nll=58.8034 kld=68.1104 beta=0.0391 lr=1.00e-05 time=13.6s
2026-05-10 14:29:45.541 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_l48ii_sc\artifacts\model.pt
2026-05-10 14:29:46.135 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_l48ii_sc\artifacts
2026-05-10 14:29:46.365 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[800, 200], device=cuda
2026-05-10 14:29:46.378 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_l48ii_sc\artifacts\model.pt
  Trial 6: target=sqrt_target, dims=[800,200], dropout=0.5, beta=0.295, epochs=20, binary=True → NDCG@15=0.204295
2026-05-10 14:30:11.154 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[400, 128], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 14:30:11.233 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:04<00:00, 39788.18user/s]
Эпохи:  10%|█         | 1/10 [00:11<01:47, 11.91s/epoch, beta=0.001, kld=172.345, loss=81.217, lr=9.76e-04, nll=81.157]

2026-05-10 14:30:27.637 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=81.2167 nll=81.1575 kld=172.3446 beta=0.0006 lr=9.76e-04 time=11.9s

Эпохи:  20%|██        | 2/10 [00:23<01:34, 11.86s/epoch, beta=0.001, kld=264.107, loss=69.271, lr=9.05e-04, nll=69.050]

2026-05-10 14:30:39.461 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=69.2713 nll=69.0502 kld=264.1068 beta=0.0011 lr=9.05e-04 time=11.8s

Эпохи:  30%|███       | 3/10 [00:35<01:21, 11.67s/epoch, beta=0.002, kld=229.356, loss=66.714, lr=7.96e-04, nll=66.393]

2026-05-10 14:30:50.912 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=66.7135 nll=66.3929 kld=229.3556 beta=0.0017 lr=7.96e-04 time=11.4s

Эпохи:  40%|████      | 4/10 [00:46<01:10, 11.69s/epoch, beta=0.002, kld=207.392, loss=65.447, lr=6.58e-04, nll=65.040]

2026-05-10 14:31:02.638 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=65.4469 nll=65.0402 kld=207.3918 beta=0.0022 lr=6.58e-04 time=11.7s

Эпохи:  50%|█████     | 5/10 [00:58<00:58, 11.64s/epoch, beta=0.003, kld=193.115, loss=64.681, lr=5.05e-04, nll=64.193]

2026-05-10 14:31:14.179 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=64.6807 nll=64.1932 kld=193.1153 beta=0.0028 lr=5.05e-04 time=11.5s

Эпохи:  60%|██████    | 6/10 [01:09<00:46, 11.59s/epoch, beta=0.003, kld=182.012, loss=64.136, lr=3.52e-04, nll=63.574]

2026-05-10 14:31:25.678 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=64.1362 nll=63.5744 kld=182.0117 beta=0.0034 lr=3.52e-04 time=11.5s

Эпохи:  70%|███████   | 7/10 [01:21<00:34, 11.57s/epoch, beta=0.004, kld=173.860, loss=63.788, lr=2.14e-04, nll=63.153]

2026-05-10 14:31:37.212 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=63.7875 nll=63.1534 kld=173.8599 beta=0.0039 lr=2.14e-04 time=11.5s

Эпохи:  80%|████████  | 8/10 [01:32<00:23, 11.53s/epoch, beta=0.004, kld=166.189, loss=63.564, lr=1.05e-04, nll=62.864]

2026-05-10 14:31:48.642 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=63.5639 nll=62.8645 kld=166.1895 beta=0.0045 lr=1.05e-04 time=11.4s

Эпохи:  90%|█████████ | 9/10 [01:44<00:11, 11.59s/epoch, beta=0.005, kld=160.174, loss=63.453, lr=3.42e-05, nll=62.688]

2026-05-10 14:32:00.378 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=63.4527 nll=62.6884 kld=160.1739 beta=0.0051 lr=3.42e-05 time=11.7s

Эпохи: 100%|██████████| 10/10 [01:56<00:00, 11.63s/epoch, beta=0.006, kld=156.424, loss=63.437, lr=1.00e-05, nll=62.602]

2026-05-10 14:32:11.992 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=63.4366 nll=62.6024 kld=156.4239 beta=0.0056 lr=1.00e-05 time=11.6s
2026-05-10 14:32:12.095 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_3w1cm78s\artifacts\model.pt
2026-05-10 14:32:12.676 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_3w1cm78s\artifacts
2026-05-10 14:32:12.838 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[400, 128], device=cuda
2026-05-10 14:32:12.845 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_3w1cm78s\artifacts\model.pt
  Trial 7: target=sqrt_target, dims=[400,128], dropout=0.6, beta=0.085, epochs=10, binary=True → NDCG@15=0.205491
2026-05-10 14:32:36.930 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[400, 128], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 14:32:37.007 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:04<00:00, 39090.85user/s]
Эпохи:  10%|█         | 1/10 [00:11<01:44, 11.56s/epoch, beta=0.001, kld=154.834, loss=96.179, lr=9.76e-04, nll=96.115]

2026-05-10 14:32:53.133 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=96.1793 nll=96.1146 kld=154.8336 beta=0.0007 lr=9.76e-04 time=11.6s

Эпохи:  20%|██        | 2/10 [00:23<01:32, 11.54s/epoch, beta=0.001, kld=268.180, loss=83.854, lr=9.05e-04, nll=83.577]

2026-05-10 14:33:04.666 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=83.8540 nll=83.5770 kld=268.1802 beta=0.0014 lr=9.05e-04 time=11.5s

Эпохи:  30%|███       | 3/10 [00:34<01:20, 11.54s/epoch, beta=0.002, kld=239.180, loss=80.873, lr=7.96e-04, nll=80.462]

2026-05-10 14:33:16.208 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=80.8727 nll=80.4621 kld=239.1799 beta=0.0021 lr=7.96e-04 time=11.5s

Эпохи:  40%|████      | 4/10 [00:46<01:09, 11.52s/epoch, beta=0.003, kld=213.051, loss=79.315, lr=6.58e-04, nll=78.802]

2026-05-10 14:33:27.686 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=79.3149 nll=78.8021 kld=213.0509 beta=0.0028 lr=6.58e-04 time=11.5s

Эпохи:  50%|█████     | 5/10 [00:57<00:57, 11.49s/epoch, beta=0.003, kld=196.275, loss=78.294, lr=5.05e-04, nll=77.686]

2026-05-10 14:33:39.121 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=78.2941 nll=77.6858 kld=196.2754 beta=0.0034 lr=5.05e-04 time=11.4s

Эпохи:  60%|██████    | 6/10 [01:09<00:45, 11.50s/epoch, beta=0.004, kld=185.254, loss=77.582, lr=3.52e-04, nll=76.879]

2026-05-10 14:33:50.643 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=77.5816 nll=76.8794 kld=185.2541 beta=0.0041 lr=3.52e-04 time=11.5s

Эпохи:  70%|███████   | 7/10 [01:20<00:34, 11.61s/epoch, beta=0.005, kld=177.106, loss=77.088, lr=2.14e-04, nll=76.295]

2026-05-10 14:34:02.479 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=77.0879 nll=76.2948 kld=177.1057 beta=0.0048 lr=2.14e-04 time=11.8s

Эпохи:  80%|████████  | 8/10 [01:32<00:23, 11.57s/epoch, beta=0.006, kld=168.224, loss=76.733, lr=1.05e-04, nll=75.864]

2026-05-10 14:34:13.958 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=76.7335 nll=75.8640 kld=168.2242 beta=0.0055 lr=1.05e-04 time=11.5s

Эпохи:  90%|█████████ | 9/10 [01:43<00:11, 11.56s/epoch, beta=0.006, kld=162.851, loss=76.650, lr=3.42e-05, nll=75.696]

2026-05-10 14:34:25.494 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=76.6503 nll=75.6961 kld=162.8510 beta=0.0062 lr=3.42e-05 time=11.5s

Эпохи: 100%|██████████| 10/10 [01:55<00:00, 11.57s/epoch, beta=0.007, kld=159.738, loss=76.558, lr=1.00e-05, nll=75.512]

2026-05-10 14:34:37.241 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=76.5580 nll=75.5119 kld=159.7379 beta=0.0069 lr=1.00e-05 time=11.7s
2026-05-10 14:34:37.343 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_ck24rqbm\artifacts\model.pt
2026-05-10 14:34:38.119 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_ck24rqbm\artifacts
2026-05-10 14:34:38.278 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[400, 128], device=cuda
2026-05-10 14:34:38.284 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_ck24rqbm\artifacts\model.pt
  Trial 8: target=log_target, dims=[400,128], dropout=0.7, beta=0.104, epochs=10, binary=False → NDCG@15=0.209065
2026-05-10 14:35:02.262 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[800, 128], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 14:35:02.339 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:04<00:00, 38698.97user/s]
Эпохи:   4%|▍         | 1/25 [00:13<05:25, 13.56s/epoch, beta=0.001, kld=220.726, loss=131.080, lr=9.96e-04, nll=130.927]

2026-05-10 14:35:20.494 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=131.0796 nll=130.9273 kld=220.7263 beta=0.0011 lr=9.96e-04 time=13.6s

Эпохи:   8%|▊         | 2/25 [00:26<05:07, 13.38s/epoch, beta=0.002, kld=296.205, loss=111.561, lr=9.84e-04, nll=111.079]

2026-05-10 14:35:33.755 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=111.5606 nll=111.0787 kld=296.2049 beta=0.0022 lr=9.84e-04 time=13.3s

Эпохи:  12%|█▏        | 3/25 [00:40<04:54, 13.40s/epoch, beta=0.003, kld=259.925, loss=107.066, lr=9.65e-04, nll=106.357]

2026-05-10 14:35:47.179 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=107.0658 nll=106.3571 kld=259.9253 beta=0.0033 lr=9.65e-04 time=13.4s

Эпохи:  16%|█▌        | 4/25 [00:53<04:44, 13.53s/epoch, beta=0.004, kld=236.885, loss=104.648, lr=9.39e-04, nll=103.743]

2026-05-10 14:36:00.910 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=104.6484 nll=103.7426 kld=236.8850 beta=0.0044 lr=9.39e-04 time=13.7s

Эпохи:  20%|██        | 5/25 [01:07<04:29, 13.48s/epoch, beta=0.005, kld=220.481, loss=103.750, lr=9.05e-04, nll=102.665]

2026-05-10 14:36:14.296 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=103.7499 nll=102.6645 kld=220.4814 beta=0.0055 lr=9.05e-04 time=13.4s

Эпохи:  24%|██▍       | 6/25 [01:20<04:16, 13.50s/epoch, beta=0.007, kld=209.425, loss=102.848, lr=8.66e-04, nll=101.588]

2026-05-10 14:36:27.842 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=102.8483 nll=101.5881 kld=209.4249 beta=0.0066 lr=8.66e-04 time=13.5s

Эпохи:  28%|██▊       | 7/25 [01:34<04:04, 13.57s/epoch, beta=0.008, kld=200.132, loss=102.366, lr=8.21e-04, nll=100.942]

2026-05-10 14:36:41.563 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=102.3658 nll=100.9424 kld=200.1323 beta=0.0077 lr=8.21e-04 time=13.7s

Эпохи:  32%|███▏      | 8/25 [01:48<03:50, 13.54s/epoch, beta=0.009, kld=192.437, loss=101.630, lr=7.70e-04, nll=100.051]

2026-05-10 14:36:55.021 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=101.6302 nll=100.0506 kld=192.4367 beta=0.0088 lr=7.70e-04 time=13.5s

Эпохи:  36%|███▌      | 9/25 [02:01<03:36, 13.56s/epoch, beta=0.010, kld=185.447, loss=101.025, lr=7.16e-04, nll=99.300]

2026-05-10 14:37:08.627 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=101.0247 nll=99.2996 kld=185.4469 beta=0.0099 lr=7.16e-04 time=13.6s

Эпохи:  40%|████      | 10/25 [02:15<03:23, 13.54s/epoch, beta=0.011, kld=178.508, loss=100.432, lr=6.58e-04, nll=98.576]

2026-05-10 14:37:22.115 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=100.4316 nll=98.5757 kld=178.5082 beta=0.0109 lr=6.58e-04 time=13.5s

Эпохи:  44%|████▍     | 11/25 [02:28<03:09, 13.53s/epoch, beta=0.012, kld=173.230, loss=99.967, lr=5.98e-04, nll=97.976]

2026-05-10 14:37:35.629 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 11: loss=99.9669 nll=97.9760 kld=173.2295 beta=0.0120 lr=5.98e-04 time=13.5s

Эпохи:  48%|████▊     | 12/25 [02:42<02:56, 13.54s/epoch, beta=0.013, kld=167.991, loss=99.415, lr=5.36e-04, nll=97.301]

2026-05-10 14:37:49.192 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 12: loss=99.4154 nll=97.3011 kld=167.9912 beta=0.0131 lr=5.36e-04 time=13.6s

Эпохи:  52%|█████▏    | 13/25 [02:56<02:43, 13.63s/epoch, beta=0.014, kld=163.383, loss=98.945, lr=4.74e-04, nll=96.710]

2026-05-10 14:38:03.014 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 13: loss=98.9452 nll=96.7100 kld=163.3833 beta=0.0142 lr=4.74e-04 time=13.8s

Эпохи:  56%|█████▌    | 14/25 [03:09<02:29, 13.61s/epoch, beta=0.015, kld=158.435, loss=98.455, lr=4.12e-04, nll=96.114]

2026-05-10 14:38:16.578 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 14: loss=98.4555 nll=96.1144 kld=158.4348 beta=0.0153 lr=4.12e-04 time=13.6s

Эпохи:  60%|██████    | 15/25 [03:23<02:16, 13.67s/epoch, beta=0.016, kld=154.359, loss=98.078, lr=3.52e-04, nll=95.628]

2026-05-10 14:38:30.383 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 15: loss=98.0782 nll=95.6284 kld=154.3592 beta=0.0164 lr=3.52e-04 time=13.8s

Эпохи:  64%|██████▍   | 16/25 [03:37<02:03, 13.70s/epoch, beta=0.018, kld=151.199, loss=97.861, lr=2.94e-04, nll=95.296]

2026-05-10 14:38:44.169 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 16: loss=97.8611 nll=95.2956 kld=151.1990 beta=0.0175 lr=2.94e-04 time=13.8s

Эпохи:  68%|██████▊   | 17/25 [03:50<01:49, 13.67s/epoch, beta=0.019, kld=148.199, loss=97.453, lr=2.40e-04, nll=94.777]

2026-05-10 14:38:57.748 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 17: loss=97.4535 nll=94.7770 kld=148.1995 beta=0.0186 lr=2.40e-04 time=13.6s

Эпохи:  72%|███████▏  | 18/25 [04:04<01:35, 13.66s/epoch, beta=0.020, kld=144.146, loss=97.237, lr=1.89e-04, nll=94.476]

2026-05-10 14:39:11.385 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 18: loss=97.2368 nll=94.4756 kld=144.1460 beta=0.0197 lr=1.89e-04 time=13.6s

Эпохи:  76%|███████▌  | 19/25 [04:17<01:21, 13.62s/epoch, beta=0.021, kld=141.578, loss=96.988, lr=1.44e-04, nll=94.121]

2026-05-10 14:39:24.905 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 19: loss=96.9879 nll=94.1210 kld=141.5775 beta=0.0208 lr=1.44e-04 time=13.5s

Эпохи:  80%|████████  | 20/25 [04:31<01:07, 13.59s/epoch, beta=0.022, kld=138.108, loss=96.871, lr=1.05e-04, nll=93.924]

2026-05-10 14:39:38.433 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 20: loss=96.8714 nll=93.9235 kld=138.1078 beta=0.0219 lr=1.05e-04 time=13.5s

Эпохи:  84%|████████▍ | 21/25 [04:45<00:54, 13.60s/epoch, beta=0.023, kld=136.021, loss=96.894, lr=7.12e-05, nll=93.842]

2026-05-10 14:39:52.044 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 21: loss=96.8940 nll=93.8419 kld=136.0211 beta=0.0230 lr=7.12e-05 time=13.6s

Эпохи:  88%|████████▊ | 22/25 [04:58<00:41, 13.67s/epoch, beta=0.024, kld=133.456, loss=96.801, lr=4.48e-05, nll=93.661]

2026-05-10 14:40:05.889 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 22: loss=96.8014 nll=93.6607 kld=133.4558 beta=0.0241 lr=4.48e-05 time=13.8s

Эпохи:  92%|█████████▏| 23/25 [05:12<00:27, 13.65s/epoch, beta=0.025, kld=131.408, loss=96.874, lr=2.56e-05, nll=93.637]

2026-05-10 14:40:19.476 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 23: loss=96.8738 nll=93.6374 kld=131.4077 beta=0.0252 lr=2.56e-05 time=13.6s

Эпохи:  96%|█████████▌| 24/25 [05:26<00:13, 13.71s/epoch, beta=0.026, kld=129.480, loss=96.852, lr=1.39e-05, nll=93.521]

2026-05-10 14:40:33.343 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 24: loss=96.8517 nll=93.5208 kld=129.4796 beta=0.0263 lr=1.39e-05 time=13.9s

Эпохи: 100%|██████████| 25/25 [05:39<00:00, 13.60s/epoch, beta=0.027, kld=127.601, loss=96.987, lr=1.00e-05, nll=93.565]

2026-05-10 14:40:46.929 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 25: loss=96.9869 nll=93.5648 kld=127.6006 beta=0.0274 lr=1.00e-05 time=13.6s
2026-05-10 14:40:47.082 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_a338xhlj\artifacts\model.pt
2026-05-10 14:40:47.846 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_a338xhlj\artifacts
2026-05-10 14:40:48.080 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[800, 128], device=cuda
2026-05-10 14:40:48.091 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_a338xhlj\artifacts\model.pt
  Trial 9: target=sqrt_target, dims=[800,128], dropout=0.3, beta=0.165, epochs=25, binary=False → NDCG@15=0.206819
2026-05-10 14:41:12.588 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 14:41:12.665 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:04<00:00, 39154.81user/s]
Эпохи:  10%|█         | 1/10 [00:12<01:53, 12.62s/epoch, beta=0.001, kld=123.661, loss=93.537, lr=9.76e-04, nll=93.478]

2026-05-10 14:41:29.841 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=93.5371 nll=93.4775 kld=123.6612 beta=0.0008 lr=9.76e-04 time=12.6s

Эпохи:  20%|██        | 2/10 [00:24<01:39, 12.38s/epoch, beta=0.002, kld=182.291, loss=82.439, lr=9.05e-04, nll=82.226]

2026-05-10 14:41:42.061 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=82.4389 nll=82.2262 kld=182.2912 beta=0.0016 lr=9.05e-04 time=12.2s

Эпохи:  30%|███       | 3/10 [00:37<01:26, 12.34s/epoch, beta=0.002, kld=163.164, loss=79.890, lr=7.96e-04, nll=79.572]

2026-05-10 14:41:54.349 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=79.8896 nll=79.5716 kld=163.1643 beta=0.0023 lr=7.96e-04 time=12.3s

Эпохи:  40%|████      | 4/10 [00:49<01:14, 12.41s/epoch, beta=0.003, kld=149.663, loss=78.427, lr=6.58e-04, nll=78.018]

2026-05-10 14:42:06.866 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=78.4271 nll=78.0182 kld=149.6632 beta=0.0031 lr=6.58e-04 time=12.5s

Эпохи:  50%|█████     | 5/10 [01:01<01:01, 12.35s/epoch, beta=0.004, kld=140.892, loss=77.394, lr=5.05e-04, nll=76.898]

2026-05-10 14:42:19.096 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=77.3935 nll=76.8980 kld=140.8923 beta=0.0039 lr=5.05e-04 time=12.2s

Эпохи:  60%|██████    | 6/10 [01:14<00:49, 12.45s/epoch, beta=0.005, kld=135.311, loss=76.626, lr=3.52e-04, nll=76.045]

2026-05-10 14:42:31.762 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=76.6264 nll=76.0447 kld=135.3110 beta=0.0047 lr=3.52e-04 time=12.7s

Эпохи:  70%|███████   | 7/10 [01:26<00:37, 12.42s/epoch, beta=0.005, kld=130.727, loss=76.089, lr=2.14e-04, nll=75.425]

2026-05-10 14:42:44.124 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=76.0893 nll=75.4251 kld=130.7271 beta=0.0055 lr=2.14e-04 time=12.4s

Эпохи:  80%|████████  | 8/10 [01:39<00:24, 12.39s/epoch, beta=0.006, kld=126.343, loss=75.693, lr=1.05e-04, nll=74.952]

2026-05-10 14:42:56.449 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=75.6929 nll=74.9521 kld=126.3430 beta=0.0063 lr=1.05e-04 time=12.3s

Эпохи:  90%|█████████ | 9/10 [01:51<00:12, 12.38s/epoch, beta=0.007, kld=123.435, loss=75.513, lr=3.42e-05, nll=74.692]

2026-05-10 14:43:08.791 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=75.5127 nll=74.6923 kld=123.4349 beta=0.0070 lr=3.42e-05 time=12.3s

Эпохи: 100%|██████████| 10/10 [02:03<00:00, 12.38s/epoch, beta=0.008, kld=121.432, loss=75.427, lr=1.00e-05, nll=74.525]

2026-05-10 14:43:21.068 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=75.4271 nll=74.5252 kld=121.4319 beta=0.0078 lr=1.00e-05 time=12.3s
2026-05-10 14:43:21.192 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna__t3_w80h\artifacts\model.pt
2026-05-10 14:43:21.969 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna__t3_w80h\artifacts
2026-05-10 14:43:22.172 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda
2026-05-10 14:43:22.181 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna__t3_w80h\artifacts\model.pt
  Trial 10: target=log_target, dims=[600,64], dropout=0.7, beta=0.118, epochs=10, binary=False → NDCG@15=0.210690
2026-05-10 14:43:46.087 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 14:43:46.163 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:04<00:00, 39255.18user/s]
Эпохи:  10%|█         | 1/10 [00:12<01:54, 12.70s/epoch, beta=0.001, kld=123.959, loss=93.535, lr=9.76e-04, nll=93.477]

2026-05-10 14:44:03.410 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=93.5347 nll=93.4771 kld=123.9587 beta=0.0008 lr=9.76e-04 time=12.7s

Эпохи:  20%|██        | 2/10 [00:24<01:39, 12.38s/epoch, beta=0.002, kld=183.711, loss=82.431, lr=9.05e-04, nll=82.225]

2026-05-10 14:44:15.566 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=82.4315 nll=82.2247 kld=183.7106 beta=0.0015 lr=9.05e-04 time=12.2s

Эпохи:  30%|███       | 3/10 [00:37<01:26, 12.35s/epoch, beta=0.002, kld=164.791, loss=79.879, lr=7.96e-04, nll=79.569]

2026-05-10 14:44:27.884 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=79.8787 nll=79.5690 kld=164.7910 beta=0.0023 lr=7.96e-04 time=12.3s

Эпохи:  40%|████      | 4/10 [00:49<01:14, 12.38s/epoch, beta=0.003, kld=151.224, loss=78.413, lr=6.58e-04, nll=78.015]

2026-05-10 14:44:40.317 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=78.4133 nll=78.0149 kld=151.2242 beta=0.0030 lr=6.58e-04 time=12.4s

Эпохи:  50%|█████     | 5/10 [01:01<01:01, 12.33s/epoch, beta=0.004, kld=142.403, loss=77.376, lr=5.05e-04, nll=76.894]

2026-05-10 14:44:52.563 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=77.3765 nll=76.8936 kld=142.4026 beta=0.0038 lr=5.05e-04 time=12.2s

Эпохи:  60%|██████    | 6/10 [01:14<00:49, 12.30s/epoch, beta=0.005, kld=136.834, loss=76.606, lr=3.52e-04, nll=76.039]

2026-05-10 14:45:04.807 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=76.6063 nll=76.0391 kld=136.8337 beta=0.0045 lr=3.52e-04 time=12.2s

Эпохи:  70%|███████   | 7/10 [01:26<00:36, 12.29s/epoch, beta=0.005, kld=132.247, loss=76.066, lr=2.14e-04, nll=75.418]

2026-05-10 14:45:17.060 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=76.0663 nll=75.4184 kld=132.2467 beta=0.0053 lr=2.14e-04 time=12.3s

Эпохи:  80%|████████  | 8/10 [01:38<00:24, 12.28s/epoch, beta=0.006, kld=127.863, loss=75.667, lr=1.05e-04, nll=74.944]

2026-05-10 14:45:29.337 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=75.6671 nll=74.9443 kld=127.8628 beta=0.0060 lr=1.05e-04 time=12.3s

Эпохи:  90%|█████████ | 9/10 [01:50<00:12, 12.27s/epoch, beta=0.007, kld=124.959, loss=75.484, lr=3.42e-05, nll=74.684]

2026-05-10 14:45:41.587 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=75.4844 nll=74.6836 kld=124.9591 beta=0.0068 lr=3.42e-05 time=12.2s

Эпохи: 100%|██████████| 10/10 [02:03<00:00, 12.32s/epoch, beta=0.008, kld=122.969, loss=75.396, lr=1.00e-05, nll=74.516]

2026-05-10 14:45:53.922 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=75.3964 nll=74.5157 kld=122.9693 beta=0.0075 lr=1.00e-05 time=12.3s
2026-05-10 14:45:54.055 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_6rtkowf5\artifacts\model.pt
2026-05-10 14:45:54.829 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_6rtkowf5\artifacts
2026-05-10 14:45:55.036 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda
2026-05-10 14:45:55.047 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_6rtkowf5\artifacts\model.pt
  Trial 11: target=log_target, dims=[600,64], dropout=0.7, beta=0.114, epochs=10, binary=False → NDCG@15=0.210711
2026-05-10 14:46:18.898 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 14:46:18.983 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:04<00:00, 39410.50user/s]
Эпохи:   7%|▋         | 1/15 [00:12<02:59, 12.83s/epoch, beta=0.001, kld=122.518, loss=93.542, lr=9.89e-04, nll=93.475]

2026-05-10 14:46:36.343 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=93.5423 nll=93.4747 kld=122.5184 beta=0.0009 lr=9.89e-04 time=12.8s

Эпохи:  13%|█▎        | 2/15 [00:25<02:41, 12.45s/epoch, beta=0.002, kld=176.624, loss=82.484, lr=9.57e-04, nll=82.248]

2026-05-10 14:46:48.528 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=82.4837 nll=82.2475 kld=176.6236 beta=0.0018 lr=9.57e-04 time=12.2s

Эпохи:  20%|██        | 3/15 [00:37<02:28, 12.36s/epoch, beta=0.003, kld=156.539, loss=80.026, lr=9.05e-04, nll=79.676]

2026-05-10 14:47:00.783 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=80.0264 nll=79.6764 kld=156.5395 beta=0.0027 lr=9.05e-04 time=12.3s

Эпохи:  27%|██▋       | 4/15 [00:49<02:15, 12.35s/epoch, beta=0.004, kld=142.789, loss=78.695, lr=8.36e-04, nll=78.247]

2026-05-10 14:47:13.107 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=78.6946 nll=78.2471 kld=142.7895 beta=0.0036 lr=8.36e-04 time=12.3s

Эпохи:  33%|███▎      | 5/15 [01:01<02:03, 12.31s/epoch, beta=0.004, kld=133.810, loss=77.801, lr=7.52e-04, nll=77.261]

2026-05-10 14:47:25.341 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=77.8006 nll=77.2607 kld=133.8101 beta=0.0045 lr=7.52e-04 time=12.2s

Эпохи:  40%|████      | 6/15 [01:14<01:50, 12.29s/epoch, beta=0.005, kld=127.952, loss=77.124, lr=6.58e-04, nll=76.492]

2026-05-10 14:47:37.597 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=77.1235 nll=76.4925 kld=127.9517 beta=0.0054 lr=6.58e-04 time=12.3s

Эпохи:  47%|████▋     | 7/15 [01:26<01:38, 12.27s/epoch, beta=0.006, kld=123.359, loss=76.616, lr=5.57e-04, nll=75.896]

2026-05-10 14:47:49.814 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=76.6155 nll=75.8963 kld=123.3593 beta=0.0063 lr=5.57e-04 time=12.2s

Эпохи:  53%|█████▎    | 8/15 [01:38<01:26, 12.36s/epoch, beta=0.007, kld=118.583, loss=76.166, lr=4.53e-04, nll=75.368]

2026-05-10 14:48:02.386 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=76.1657 nll=75.3680 kld=118.5828 beta=0.0072 lr=4.53e-04 time=12.6s

Эпохи:  60%|██████    | 9/15 [01:51<01:14, 12.34s/epoch, beta=0.008, kld=115.372, loss=75.818, lr=3.52e-04, nll=74.938]

2026-05-10 14:48:14.672 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=75.8182 nll=74.9385 kld=115.3724 beta=0.0081 lr=3.52e-04 time=12.3s

Эпохи:  67%|██████▋   | 10/15 [02:03<01:01, 12.34s/epoch, beta=0.009, kld=112.008, loss=75.484, lr=2.57e-04, nll=74.529]

2026-05-10 14:48:27.022 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=75.4837 nll=74.5292 kld=112.0084 beta=0.0090 lr=2.57e-04 time=12.3s

Эпохи:  73%|███████▎  | 11/15 [02:16<00:49, 12.44s/epoch, beta=0.010, kld=109.293, loss=75.260, lr=1.74e-04, nll=74.230]

2026-05-10 14:48:39.677 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 11: loss=75.2596 nll=74.2301 kld=109.2932 beta=0.0099 lr=1.74e-04 time=12.7s

Эпохи:  80%|████████  | 12/15 [02:28<00:37, 12.43s/epoch, beta=0.011, kld=106.746, loss=75.071, lr=1.05e-04, nll=73.969]

2026-05-10 14:48:52.086 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 12: loss=75.0707 nll=73.9694 kld=106.7458 beta=0.0108 lr=1.05e-04 time=12.4s

Эпохи:  87%|████████▋ | 13/15 [02:40<00:24, 12.42s/epoch, beta=0.012, kld=104.368, loss=74.973, lr=5.28e-05, nll=73.803]

2026-05-10 14:49:04.497 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 13: loss=74.9733 nll=73.8029 kld=104.3676 beta=0.0117 lr=5.28e-05 time=12.4s

Эпохи:  93%|█████████▎| 14/15 [02:53<00:12, 12.38s/epoch, beta=0.013, kld=102.341, loss=74.919, lr=2.08e-05, nll=73.679]

2026-05-10 14:49:16.790 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 14: loss=74.9187 nll=73.6792 kld=102.3405 beta=0.0126 lr=2.08e-05 time=12.3s

Эпохи: 100%|██████████| 15/15 [03:05<00:00, 12.38s/epoch, beta=0.013, kld=101.020, loss=74.925, lr=1.00e-05, nll=73.610]

2026-05-10 14:49:29.133 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 15: loss=74.9246 nll=73.6104 kld=101.0199 beta=0.0135 lr=1.00e-05 time=12.3s
2026-05-10 14:49:29.262 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_rd3oa79r\artifacts\model.pt
2026-05-10 14:49:30.039 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_rd3oa79r\artifacts
2026-05-10 14:49:30.238 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda
2026-05-10 14:49:30.246 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_rd3oa79r\artifacts\model.pt
  Trial 12: target=log_target, dims=[600,64], dropout=0.7, beta=0.135, epochs=15, binary=False → NDCG@15=0.208776
2026-05-10 14:49:54.250 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 14:49:54.334 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:04<00:00, 38596.71user/s]
Эпохи:   7%|▋         | 1/15 [00:12<02:55, 12.57s/epoch, beta=0.001, kld=117.508, loss=93.585, lr=9.89e-04, nll=93.483]

2026-05-10 14:50:11.522 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=93.5847 nll=93.4830 kld=117.5084 beta=0.0014 lr=9.89e-04 time=12.6s

Эпохи:  13%|█▎        | 2/15 [00:24<02:40, 12.33s/epoch, beta=0.003, kld=157.421, loss=82.610, lr=9.57e-04, nll=82.278]

2026-05-10 14:50:23.684 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=82.6103 nll=82.2778 kld=157.4208 beta=0.0028 lr=9.57e-04 time=12.2s

Эпохи:  20%|██        | 3/15 [00:37<02:28, 12.41s/epoch, beta=0.004, kld=136.800, loss=80.208, lr=9.05e-04, nll=79.724]

2026-05-10 14:50:36.188 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=80.2081 nll=79.7238 kld=136.7998 beta=0.0043 lr=9.05e-04 time=12.5s

Эпохи:  27%|██▋       | 4/15 [00:49<02:16, 12.41s/epoch, beta=0.006, kld=123.920, loss=78.925, lr=8.36e-04, nll=78.310]

2026-05-10 14:50:48.592 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=78.9246 nll=78.3097 kld=123.9196 beta=0.0057 lr=8.36e-04 time=12.4s

Эпохи:  33%|███▎      | 5/15 [01:02<02:03, 12.39s/epoch, beta=0.007, kld=115.529, loss=78.080, lr=7.52e-04, nll=77.342]

2026-05-10 14:51:00.958 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=78.0796 nll=77.3416 kld=115.5292 beta=0.0071 lr=7.52e-04 time=12.4s

Эпохи:  40%|████      | 6/15 [01:14<01:51, 12.41s/epoch, beta=0.009, kld=109.710, loss=77.454, lr=6.58e-04, nll=76.597]

2026-05-10 14:51:13.397 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=77.4543 nll=76.5975 kld=109.7097 beta=0.0085 lr=6.58e-04 time=12.4s

Эпохи:  47%|████▋     | 7/15 [01:26<01:38, 12.35s/epoch, beta=0.010, kld=105.181, loss=76.993, lr=5.57e-04, nll=76.022]

2026-05-10 14:51:25.627 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=76.9927 nll=76.0218 kld=105.1815 beta=0.0099 lr=5.57e-04 time=12.2s

Эпохи:  53%|█████▎    | 8/15 [01:38<01:26, 12.33s/epoch, beta=0.011, kld=100.343, loss=76.580, lr=4.53e-04, nll=75.511]

2026-05-10 14:51:37.911 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=76.5798 nll=75.5111 kld=100.3427 beta=0.0114 lr=4.53e-04 time=12.3s

Эпохи:  60%|██████    | 9/15 [01:51<01:14, 12.33s/epoch, beta=0.013, kld=96.965, loss=76.277, lr=3.52e-04, nll=75.106]

2026-05-10 14:51:50.259 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=76.2772 nll=75.1065 kld=96.9649 beta=0.0128 lr=3.52e-04 time=12.3s

Эпохи:  67%|██████▋   | 10/15 [02:03<01:01, 12.40s/epoch, beta=0.014, kld=93.550, loss=75.979, lr=2.57e-04, nll=74.717]

2026-05-10 14:52:02.795 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=75.9791 nll=74.7167 kld=93.5504 beta=0.0142 lr=2.57e-04 time=12.5s

Эпохи:  73%|███████▎  | 11/15 [02:16<00:49, 12.38s/epoch, beta=0.016, kld=90.732, loss=75.791, lr=1.74e-04, nll=74.438]

2026-05-10 14:52:15.144 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 11: loss=75.7914 nll=74.4381 kld=90.7319 beta=0.0156 lr=1.74e-04 time=12.3s

Эпохи:  80%|████████  | 12/15 [02:28<00:37, 12.39s/epoch, beta=0.017, kld=88.175, loss=75.635, lr=1.05e-04, nll=74.195]

2026-05-10 14:52:27.562 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 12: loss=75.6355 nll=74.1950 kld=88.1755 beta=0.0170 lr=1.05e-04 time=12.4s

Эпохи:  87%|████████▋ | 13/15 [02:41<00:24, 12.43s/epoch, beta=0.018, kld=85.803, loss=75.568, lr=5.28e-05, nll=74.045]

2026-05-10 14:52:40.065 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 13: loss=75.5685 nll=74.0449 kld=85.8027 beta=0.0185 lr=5.28e-05 time=12.5s

Эпохи:  93%|█████████▎| 14/15 [02:53<00:12, 12.39s/epoch, beta=0.020, kld=83.800, loss=75.542, lr=2.08e-05, nll=73.935]

2026-05-10 14:52:52.384 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 14: loss=75.5419 nll=73.9346 kld=83.8004 beta=0.0199 lr=2.08e-05 time=12.3s

Эпохи: 100%|██████████| 15/15 [03:05<00:00, 12.39s/epoch, beta=0.021, kld=82.494, loss=75.577, lr=1.00e-05, nll=73.878]

2026-05-10 14:53:04.818 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 15: loss=75.5770 nll=73.8776 kld=82.4935 beta=0.0213 lr=1.00e-05 time=12.4s
2026-05-10 14:53:04.946 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_jh02qbkc\artifacts\model.pt
2026-05-10 14:53:05.729 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_jh02qbkc\artifacts
2026-05-10 14:53:05.924 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda
2026-05-10 14:53:05.932 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_jh02qbkc\artifacts\model.pt
  Trial 13: target=log_target, dims=[600,64], dropout=0.7, beta=0.214, epochs=15, binary=False → NDCG@15=0.208378
2026-05-10 14:53:29.492 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 14:53:29.566 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:04<00:00, 38507.23user/s]
Эпохи:  10%|█         | 1/10 [00:12<01:52, 12.50s/epoch, beta=0.001, kld=124.684, loss=93.529, lr=9.76e-04, nll=93.476]

2026-05-10 14:53:46.698 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=93.5289 nll=93.4761 kld=124.6845 beta=0.0007 lr=9.76e-04 time=12.5s

Эпохи:  20%|██        | 2/10 [00:25<01:40, 12.57s/epoch, beta=0.001, kld=187.278, loss=82.413, lr=9.05e-04, nll=82.221]

2026-05-10 14:53:59.316 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=82.4134 nll=82.2212 kld=187.2784 beta=0.0014 lr=9.05e-04 time=12.6s

Эпохи:  30%|███       | 3/10 [00:37<01:26, 12.41s/epoch, beta=0.002, kld=168.975, loss=79.852, lr=7.96e-04, nll=79.563]

2026-05-10 14:54:11.539 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=79.8521 nll=79.5628 kld=168.9751 beta=0.0021 lr=7.96e-04 time=12.2s

Эпохи:  40%|████      | 4/10 [00:49<01:14, 12.39s/epoch, beta=0.003, kld=155.244, loss=78.380, lr=6.58e-04, nll=78.007]

2026-05-10 14:54:23.907 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=78.3797 nll=78.0071 kld=155.2439 beta=0.0027 lr=6.58e-04 time=12.4s

Эпохи:  50%|█████     | 5/10 [01:02<01:02, 12.46s/epoch, beta=0.003, kld=146.284, loss=77.335, lr=5.05e-04, nll=76.883]

2026-05-10 14:54:36.496 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=77.3350 nll=76.8832 kld=146.2836 beta=0.0034 lr=5.05e-04 time=12.6s

Эпохи:  60%|██████    | 6/10 [01:14<00:49, 12.47s/epoch, beta=0.004, kld=140.752, loss=76.557, lr=3.52e-04, nll=76.026]

2026-05-10 14:54:48.971 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=76.5571 nll=76.0257 kld=140.7515 beta=0.0041 lr=3.52e-04 time=12.5s

Эпохи:  70%|███████   | 7/10 [01:27<00:37, 12.43s/epoch, beta=0.005, kld=136.158, loss=76.010, lr=2.14e-04, nll=75.402]

2026-05-10 14:55:01.316 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=76.0098 nll=75.4021 kld=136.1583 beta=0.0048 lr=2.14e-04 time=12.3s

Эпохи:  80%|████████  | 8/10 [01:39<00:24, 12.39s/epoch, beta=0.005, kld=131.772, loss=75.604, lr=1.05e-04, nll=74.925]

2026-05-10 14:55:13.638 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=75.6041 nll=74.9255 kld=131.7724 beta=0.0055 lr=1.05e-04 time=12.3s

Эпохи:  90%|█████████ | 9/10 [01:51<00:12, 12.35s/epoch, beta=0.006, kld=128.881, loss=75.415, lr=3.42e-05, nll=74.663]

2026-05-10 14:55:25.900 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=75.4151 nll=74.6627 kld=128.8806 beta=0.0062 lr=3.42e-05 time=12.3s

Эпохи: 100%|██████████| 10/10 [02:03<00:00, 12.40s/epoch, beta=0.007, kld=126.924, loss=75.321, lr=1.00e-05, nll=74.493]

2026-05-10 14:55:38.195 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=75.3212 nll=74.4930 kld=126.9243 beta=0.0069 lr=1.00e-05 time=12.3s
2026-05-10 14:55:38.327 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_kmr_0xpi\artifacts\model.pt
2026-05-10 14:55:39.107 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_kmr_0xpi\artifacts
2026-05-10 14:55:39.303 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda
2026-05-10 14:55:39.311 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_kmr_0xpi\artifacts\model.pt
  Trial 14: target=log_target, dims=[600,64], dropout=0.7, beta=0.104, epochs=10, binary=False → NDCG@15=0.210775
2026-05-10 14:56:03.578 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 14:56:03.653 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:04<00:00, 38214.70user/s]
Эпохи:   7%|▋         | 1/15 [00:12<02:52, 12.35s/epoch, beta=0.001, kld=131.047, loss=91.885, lr=9.89e-04, nll=91.842]

2026-05-10 14:56:20.671 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=91.8855 nll=91.8416 kld=131.0465 beta=0.0005 lr=9.89e-04 time=12.4s

Эпохи:  13%|█▎        | 2/15 [00:24<02:41, 12.42s/epoch, beta=0.001, kld=200.698, loss=79.935, lr=9.57e-04, nll=79.773]

2026-05-10 14:56:33.133 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=79.9348 nll=79.7734 kld=200.6984 beta=0.0011 lr=9.57e-04 time=12.5s

Эпохи:  20%|██        | 3/15 [00:37<02:27, 12.33s/epoch, beta=0.002, kld=183.897, loss=77.275, lr=9.05e-04, nll=77.029]

2026-05-10 14:56:45.351 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=77.2754 nll=77.0286 kld=183.8972 beta=0.0016 lr=9.05e-04 time=12.2s

Эпохи:  27%|██▋       | 4/15 [00:49<02:15, 12.28s/epoch, beta=0.002, kld=168.634, loss=75.744, lr=8.36e-04, nll=75.427]

2026-05-10 14:56:57.567 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=75.7439 nll=75.4268 kld=168.6341 beta=0.0022 lr=8.36e-04 time=12.2s

Эпохи:  33%|███▎      | 5/15 [01:01<02:02, 12.29s/epoch, beta=0.003, kld=159.076, loss=74.806, lr=7.52e-04, nll=74.421]

2026-05-10 14:57:09.877 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=74.8058 nll=74.4207 kld=159.0762 beta=0.0027 lr=7.52e-04 time=12.3s

Эпохи:  40%|████      | 6/15 [01:13<01:50, 12.27s/epoch, beta=0.003, kld=153.064, loss=74.072, lr=6.58e-04, nll=73.619]

2026-05-10 14:57:22.099 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=74.0717 nll=73.6188 kld=153.0644 beta=0.0032 lr=6.58e-04 time=12.2s

Эпохи:  47%|████▋     | 7/15 [01:26<01:38, 12.27s/epoch, beta=0.004, kld=148.331, loss=73.491, lr=5.57e-04, nll=72.972]

2026-05-10 14:57:34.371 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=73.4907 nll=72.9720 kld=148.3307 beta=0.0038 lr=5.57e-04 time=12.3s

Эпохи:  53%|█████▎    | 8/15 [01:38<01:25, 12.27s/epoch, beta=0.004, kld=143.608, loss=72.979, lr=4.53e-04, nll=72.400]

2026-05-10 14:57:46.632 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=72.9790 nll=72.3996 kld=143.6085 beta=0.0043 lr=4.53e-04 time=12.3s

Эпохи:  60%|██████    | 9/15 [01:50<01:14, 12.35s/epoch, beta=0.005, kld=140.359, loss=72.584, lr=3.52e-04, nll=71.942]

2026-05-10 14:57:59.149 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=72.5835 nll=71.9415 kld=140.3590 beta=0.0048 lr=3.52e-04 time=12.5s

Эпохи:  67%|██████▋   | 10/15 [02:03<01:01, 12.34s/epoch, beta=0.005, kld=136.888, loss=72.221, lr=2.57e-04, nll=71.521]

2026-05-10 14:58:11.479 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=72.2208 nll=71.5211 kld=136.8883 beta=0.0054 lr=2.57e-04 time=12.3s

Эпохи:  73%|███████▎  | 11/15 [02:15<00:49, 12.33s/epoch, beta=0.006, kld=134.200, loss=71.942, lr=1.74e-04, nll=71.184]

2026-05-10 14:58:23.772 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 11: loss=71.9421 nll=71.1838 kld=134.1997 beta=0.0059 lr=1.74e-04 time=12.3s

Эпохи:  80%|████████  | 12/15 [02:28<00:37, 12.41s/epoch, beta=0.006, kld=132.115, loss=71.702, lr=1.05e-04, nll=70.884]

2026-05-10 14:58:36.383 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 12: loss=71.7020 nll=70.8844 kld=132.1146 beta=0.0065 lr=1.05e-04 time=12.6s

Эпохи:  87%|████████▋ | 13/15 [02:40<00:24, 12.39s/epoch, beta=0.007, kld=129.715, loss=71.608, lr=5.28e-05, nll=70.736]

2026-05-10 14:58:48.732 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 13: loss=71.6083 nll=70.7358 kld=129.7152 beta=0.0070 lr=5.28e-05 time=12.3s

Эпохи:  93%|█████████▎| 14/15 [02:52<00:12, 12.39s/epoch, beta=0.008, kld=128.025, loss=71.521, lr=2.08e-05, nll=70.591]

2026-05-10 14:59:01.118 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 14: loss=71.5210 nll=70.5909 kld=128.0255 beta=0.0075 lr=2.08e-05 time=12.4s

Эпохи: 100%|██████████| 15/15 [03:05<00:00, 12.34s/epoch, beta=0.008, kld=126.569, loss=71.530, lr=1.00e-05, nll=70.542]

2026-05-10 14:59:13.478 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 15: loss=71.5299 nll=70.5423 kld=126.5693 beta=0.0081 lr=1.00e-05 time=12.4s
2026-05-10 14:59:13.617 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_37vpk711\artifacts\model.pt
2026-05-10 14:59:14.387 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_37vpk711\artifacts
2026-05-10 14:59:14.591 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda
2026-05-10 14:59:14.600 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_37vpk711\artifacts\model.pt
  Trial 15: target=log_target, dims=[600,64], dropout=0.6, beta=0.081, epochs=15, binary=False → NDCG@15=0.209448
2026-05-10 14:59:38.257 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 256], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 14:59:38.333 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:04<00:00, 38763.57user/s]
Эпохи:  10%|█         | 1/10 [00:12<01:55, 12.85s/epoch, beta=0.001, kld=248.480, loss=90.612, lr=9.76e-04, nll=90.417]

2026-05-10 14:59:55.791 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=90.6118 nll=90.4167 kld=248.4802 beta=0.0013 lr=9.76e-04 time=12.9s

Эпохи:  20%|██        | 2/10 [00:25<01:40, 12.59s/epoch, beta=0.003, kld=319.948, loss=76.846, lr=9.05e-04, nll=76.251]

2026-05-10 15:00:08.191 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=76.8458 nll=76.2509 kld=319.9481 beta=0.0025 lr=9.05e-04 time=12.4s

Эпохи:  30%|███       | 3/10 [00:37<01:27, 12.48s/epoch, beta=0.004, kld=260.262, loss=73.892, lr=7.96e-04, nll=73.078]

2026-05-10 15:00:20.552 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=73.8921 nll=73.0779 kld=260.2619 beta=0.0038 lr=7.96e-04 time=12.4s

Эпохи:  40%|████      | 4/10 [00:50<01:15, 12.57s/epoch, beta=0.005, kld=226.696, loss=72.222, lr=6.58e-04, nll=71.226]

2026-05-10 15:00:33.259 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=72.2221 nll=71.2259 kld=226.6962 beta=0.0050 lr=6.58e-04 time=12.7s

Эпохи:  50%|█████     | 5/10 [01:02<01:02, 12.56s/epoch, beta=0.006, kld=205.452, loss=71.158, lr=5.05e-04, nll=69.995]

2026-05-10 15:00:45.794 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=71.1576 nll=69.9952 kld=205.4517 beta=0.0063 lr=5.05e-04 time=12.5s

Эпохи:  60%|██████    | 6/10 [01:15<00:49, 12.50s/epoch, beta=0.008, kld=189.116, loss=70.408, lr=3.52e-04, nll=69.099]

2026-05-10 15:00:58.179 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=70.4076 nll=69.0993 kld=189.1159 beta=0.0076 lr=3.52e-04 time=12.4s

Эпохи:  70%|███████   | 7/10 [01:27<00:37, 12.49s/epoch, beta=0.009, kld=175.254, loss=69.887, lr=2.14e-04, nll=68.454]

2026-05-10 15:01:10.662 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=69.8867 nll=68.4536 kld=175.2536 beta=0.0088 lr=2.14e-04 time=12.5s

Эпохи:  80%|████████  | 8/10 [01:40<00:24, 12.47s/epoch, beta=0.010, kld=164.998, loss=69.561, lr=1.05e-04, nll=68.004]

2026-05-10 15:01:23.067 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=69.5611 nll=68.0040 kld=164.9983 beta=0.0101 lr=1.05e-04 time=12.4s

Эпохи:  90%|█████████ | 9/10 [01:52<00:12, 12.44s/epoch, beta=0.011, kld=157.177, loss=69.434, lr=3.42e-05, nll=67.752]

2026-05-10 15:01:35.449 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=69.4340 nll=67.7524 kld=157.1772 beta=0.0113 lr=3.42e-05 time=12.4s

Эпохи: 100%|██████████| 10/10 [02:04<00:00, 12.49s/epoch, beta=0.013, kld=151.924, loss=69.435, lr=1.00e-05, nll=67.618]

2026-05-10 15:01:47.866 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=69.4351 nll=67.6183 kld=151.9239 beta=0.0126 lr=1.00e-05 time=12.4s
2026-05-10 15:01:47.994 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_a8st26rk\artifacts\model.pt
2026-05-10 15:01:48.777 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_a8st26rk\artifacts
2026-05-10 15:01:48.972 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 256], device=cuda
2026-05-10 15:01:48.981 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_a8st26rk\artifacts\model.pt
  Trial 16: target=log_target, dims=[600,256], dropout=0.4, beta=0.190, epochs=10, binary=False → NDCG@15=0.206617
2026-05-10 15:02:13.095 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 15:02:13.174 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:04<00:00, 39020.94user/s]
Эпохи:   7%|▋         | 1/15 [00:12<02:59, 12.82s/epoch, beta=0.001, kld=134.612, loss=90.703, lr=9.89e-04, nll=90.648]

2026-05-10 15:02:30.560 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=90.7027 nll=90.6476 kld=134.6120 beta=0.0007 lr=9.89e-04 time=12.8s

Эпохи:  13%|█▎        | 2/15 [00:25<02:42, 12.47s/epoch, beta=0.001, kld=194.885, loss=78.049, lr=9.57e-04, nll=77.858]

2026-05-10 15:02:42.787 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=78.0491 nll=77.8582 kld=194.8852 beta=0.0013 lr=9.57e-04 time=12.2s

Эпохи:  20%|██        | 3/15 [00:37<02:28, 12.35s/epoch, beta=0.002, kld=175.511, loss=75.172, lr=9.05e-04, nll=74.885]

2026-05-10 15:02:54.985 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=75.1724 nll=74.8851 kld=175.5107 beta=0.0020 lr=9.05e-04 time=12.2s

Эпохи:  27%|██▋       | 4/15 [00:49<02:15, 12.33s/epoch, beta=0.003, kld=162.236, loss=73.611, lr=8.36e-04, nll=73.239]

2026-05-10 15:03:07.287 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=73.6111 nll=73.2388 kld=162.2360 beta=0.0026 lr=8.36e-04 time=12.3s

Эпохи:  33%|███▎      | 5/15 [01:01<02:02, 12.29s/epoch, beta=0.003, kld=153.641, loss=72.616, lr=7.52e-04, nll=72.162]

2026-05-10 15:03:19.515 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=72.6158 nll=72.1619 kld=153.6409 beta=0.0033 lr=7.52e-04 time=12.2s

Эпохи:  40%|████      | 6/15 [01:14<01:50, 12.32s/epoch, beta=0.004, kld=147.754, loss=71.863, lr=6.58e-04, nll=71.329]

2026-05-10 15:03:31.889 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=71.8628 nll=71.3293 kld=147.7544 beta=0.0039 lr=6.58e-04 time=12.4s

Эпохи:  47%|████▋     | 7/15 [01:26<01:38, 12.30s/epoch, beta=0.005, kld=143.298, loss=71.322, lr=5.57e-04, nll=70.710]

2026-05-10 15:03:44.136 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=71.3216 nll=70.7101 kld=143.2976 beta=0.0046 lr=5.57e-04 time=12.2s

Эпохи:  53%|█████▎    | 8/15 [01:38<01:26, 12.33s/epoch, beta=0.005, kld=138.784, loss=70.777, lr=4.53e-04, nll=70.094]

2026-05-10 15:03:56.553 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=70.7774 nll=70.0940 kld=138.7841 beta=0.0053 lr=4.53e-04 time=12.4s

Эпохи:  60%|██████    | 9/15 [01:51<01:14, 12.35s/epoch, beta=0.006, kld=135.370, loss=70.364, lr=3.52e-04, nll=69.608]

2026-05-10 15:04:08.923 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=70.3636 nll=69.6079 kld=135.3699 beta=0.0059 lr=3.52e-04 time=12.4s

Эпохи:  67%|██████▋   | 10/15 [02:03<01:01, 12.33s/epoch, beta=0.007, kld=132.241, loss=69.977, lr=2.57e-04, nll=69.152]

2026-05-10 15:04:21.225 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=69.9774 nll=69.1524 kld=132.2406 beta=0.0066 lr=2.57e-04 time=12.3s

Эпохи:  73%|███████▎  | 11/15 [02:15<00:49, 12.38s/epoch, beta=0.007, kld=129.287, loss=69.741, lr=1.74e-04, nll=68.850]

2026-05-10 15:04:33.715 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 11: loss=69.7413 nll=68.8498 kld=129.2865 beta=0.0072 lr=1.74e-04 time=12.5s

Эпохи:  80%|████████  | 12/15 [02:28<00:37, 12.40s/epoch, beta=0.008, kld=127.151, loss=69.495, lr=1.05e-04, nll=68.535]

2026-05-10 15:04:46.167 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 12: loss=69.4949 nll=68.5346 kld=127.1508 beta=0.0079 lr=1.05e-04 time=12.4s

Эпохи:  87%|████████▋ | 13/15 [02:40<00:24, 12.37s/epoch, beta=0.009, kld=124.744, loss=69.411, lr=5.28e-05, nll=68.387]

2026-05-10 15:04:58.447 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 13: loss=69.4110 nll=68.3869 kld=124.7438 beta=0.0085 lr=5.28e-05 time=12.3s

Эпохи:  93%|█████████▎| 14/15 [02:53<00:12, 12.35s/epoch, beta=0.009, kld=122.784, loss=69.334, lr=2.08e-05, nll=68.245]

2026-05-10 15:05:10.749 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 14: loss=69.3335 nll=68.2448 kld=122.7839 beta=0.0092 lr=2.08e-05 time=12.3s

Эпохи: 100%|██████████| 15/15 [03:05<00:00, 12.35s/epoch, beta=0.010, kld=121.324, loss=69.342, lr=1.00e-05, nll=68.187]

2026-05-10 15:05:23.051 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 15: loss=69.3421 nll=68.1867 kld=121.3240 beta=0.0099 lr=1.00e-05 time=12.3s
2026-05-10 15:05:23.175 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_mkgmng3i\artifacts\model.pt
2026-05-10 15:05:23.955 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_mkgmng3i\artifacts
2026-05-10 15:05:24.152 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda
2026-05-10 15:05:24.160 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_mkgmng3i\artifacts\model.pt
  Trial 17: target=log_target, dims=[600,64], dropout=0.5, beta=0.099, epochs=15, binary=False → NDCG@15=0.210578
2026-05-10 15:05:47.968 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 15:05:48.042 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:04<00:00, 38469.95user/s]
Эпохи:  10%|█         | 1/10 [00:12<01:56, 12.91s/epoch, beta=0.000, kld=137.352, loss=79.327, lr=9.76e-04, nll=79.295]

2026-05-10 15:06:05.588 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=79.3268 nll=79.2948 kld=137.3518 beta=0.0004 lr=9.76e-04 time=12.9s

Эпохи:  20%|██        | 2/10 [00:25<01:39, 12.46s/epoch, beta=0.001, kld=198.198, loss=69.780, lr=9.05e-04, nll=69.668]

2026-05-10 15:06:17.731 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=69.7800 nll=69.6678 kld=198.1982 beta=0.0008 lr=9.05e-04 time=12.1s

Эпохи:  30%|███       | 3/10 [00:37<01:27, 12.48s/epoch, beta=0.001, kld=176.849, loss=67.894, lr=7.96e-04, nll=67.727]

2026-05-10 15:06:30.231 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=67.8941 nll=67.7268 kld=176.8493 beta=0.0011 lr=7.96e-04 time=12.5s

Эпохи:  40%|████      | 4/10 [00:49<01:14, 12.40s/epoch, beta=0.002, kld=163.246, loss=66.797, lr=6.58e-04, nll=66.580]

2026-05-10 15:06:42.513 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=66.7969 nll=66.5805 kld=163.2459 beta=0.0015 lr=6.58e-04 time=12.3s

Эпохи:  50%|█████     | 5/10 [01:02<01:01, 12.35s/epoch, beta=0.002, kld=154.550, loss=66.022, lr=5.05e-04, nll=65.759]

2026-05-10 15:06:54.772 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=66.0224 nll=65.7586 kld=154.5499 beta=0.0019 lr=5.05e-04 time=12.3s

Эпохи:  60%|██████    | 6/10 [01:14<00:49, 12.37s/epoch, beta=0.002, kld=148.662, loss=65.446, lr=3.52e-04, nll=65.136]

2026-05-10 15:07:07.179 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=65.4463 nll=65.1363 kld=148.6624 beta=0.0023 lr=3.52e-04 time=12.4s

Эпохи:  70%|███████   | 7/10 [01:26<00:36, 12.30s/epoch, beta=0.003, kld=143.237, loss=65.041, lr=2.14e-04, nll=64.688]

2026-05-10 15:07:19.353 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=65.0408 nll=64.6877 kld=143.2371 beta=0.0027 lr=2.14e-04 time=12.2s

Эпохи:  80%|████████  | 8/10 [01:38<00:24, 12.29s/epoch, beta=0.003, kld=139.816, loss=64.744, lr=1.05e-04, nll=64.347]

2026-05-10 15:07:31.605 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=64.7443 nll=64.3465 kld=139.8157 beta=0.0030 lr=1.05e-04 time=12.3s

Эпохи:  90%|█████████ | 9/10 [01:51<00:12, 12.31s/epoch, beta=0.003, kld=136.748, loss=64.578, lr=3.42e-05, nll=64.137]

2026-05-10 15:07:43.955 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=64.5783 nll=64.1374 kld=136.7476 beta=0.0034 lr=3.42e-05 time=12.3s

Эпохи: 100%|██████████| 10/10 [02:03<00:00, 12.38s/epoch, beta=0.004, kld=134.598, loss=64.491, lr=1.00e-05, nll=64.006]

2026-05-10 15:07:56.472 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=64.4912 nll=64.0062 kld=134.5982 beta=0.0038 lr=1.00e-05 time=12.5s
2026-05-10 15:07:56.602 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_z8wxp9rp\artifacts\model.pt
2026-05-10 15:07:57.194 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_z8wxp9rp\artifacts
2026-05-10 15:07:57.399 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda
2026-05-10 15:07:57.407 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_z8wxp9rp\artifacts\model.pt
  Trial 18: target=log_target, dims=[600,64], dropout=0.7, beta=0.057, epochs=10, binary=True → NDCG@15=0.206561
2026-05-10 15:08:21.152 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 15:08:21.229 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 169596 пользователей, 12148 items, batches per epoch ≈ 663

Сборка user_items: 100%|██████████| 169596/169596 [00:04<00:00, 38873.12user/s]
Эпохи:   5%|▌         | 1/20 [00:12<04:01, 12.70s/epoch, beta=0.000, kld=132.161, loss=91.875, lr=9.94e-04, nll=91.838]

2026-05-10 15:08:38.520 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=91.8754 nll=91.8383 kld=132.1608 beta=0.0004 lr=9.94e-04 time=12.7s

Эпохи:  10%|█         | 2/20 [00:25<03:44, 12.47s/epoch, beta=0.001, kld=206.906, loss=79.914, lr=9.76e-04, nll=79.775]

2026-05-10 15:08:50.823 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=79.9137 nll=79.7746 kld=206.9059 beta=0.0009 lr=9.76e-04 time=12.3s

Эпохи:  15%|█▌        | 3/20 [00:37<03:31, 12.42s/epoch, beta=0.001, kld=191.864, loss=77.274, lr=9.46e-04, nll=77.059]

2026-05-10 15:09:03.178 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=77.2744 nll=77.0594 kld=191.8645 beta=0.0013 lr=9.46e-04 time=12.4s

Эпохи:  20%|██        | 4/20 [00:49<03:17, 12.33s/epoch, beta=0.002, kld=176.003, loss=75.786, lr=9.05e-04, nll=75.510]

2026-05-10 15:09:15.365 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=75.7859 nll=75.5095 kld=176.0032 beta=0.0018 lr=9.05e-04 time=12.2s

Эпохи:  25%|██▌       | 5/20 [01:01<03:04, 12.29s/epoch, beta=0.002, kld=165.824, loss=74.907, lr=8.55e-04, nll=74.572]

2026-05-10 15:09:27.588 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=74.9070 nll=74.5718 kld=165.8235 beta=0.0022 lr=8.55e-04 time=12.2s

Эпохи:  30%|███       | 6/20 [01:13<02:51, 12.27s/epoch, beta=0.003, kld=159.535, loss=74.221, lr=7.96e-04, nll=73.827]

2026-05-10 15:09:39.814 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=74.2212 nll=73.8271 kld=159.5351 beta=0.0027 lr=7.96e-04 time=12.2s

Эпохи:  35%|███▌      | 7/20 [01:26<02:39, 12.27s/epoch, beta=0.003, kld=154.500, loss=73.721, lr=7.30e-04, nll=73.270]

2026-05-10 15:09:52.104 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=73.7214 nll=73.2703 kld=154.5002 beta=0.0031 lr=7.30e-04 time=12.3s

Эпохи:  40%|████      | 8/20 [01:38<02:28, 12.38s/epoch, beta=0.004, kld=149.397, loss=73.259, lr=6.58e-04, nll=72.756]

2026-05-10 15:10:04.703 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=73.2592 nll=72.7559 kld=149.3971 beta=0.0036 lr=6.58e-04 time=12.6s

Эпохи:  45%|████▌     | 9/20 [01:51<02:15, 12.36s/epoch, beta=0.004, kld=146.071, loss=72.889, lr=5.82e-04, nll=72.331]

2026-05-10 15:10:17.015 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=72.8894 nll=72.3315 kld=146.0710 beta=0.0040 lr=5.82e-04 time=12.3s

Эпохи:  50%|█████     | 10/20 [02:03<02:04, 12.41s/epoch, beta=0.004, kld=142.531, loss=72.525, lr=5.05e-04, nll=71.917]

2026-05-10 15:10:29.529 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=72.5251 nll=71.9167 kld=142.5306 beta=0.0045 lr=5.05e-04 time=12.5s

Эпохи:  55%|█████▌    | 11/20 [02:16<01:51, 12.44s/epoch, beta=0.005, kld=139.672, loss=72.197, lr=4.28e-04, nll=71.538]

2026-05-10 15:10:42.032 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 11: loss=72.1973 nll=71.5382 kld=139.6716 beta=0.0049 lr=4.28e-04 time=12.5s

Эпохи:  60%|██████    | 12/20 [02:28<01:39, 12.40s/epoch, beta=0.005, kld=137.637, loss=71.863, lr=3.52e-04, nll=71.151]

2026-05-10 15:10:54.357 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 12: loss=71.8627 nll=71.1514 kld=137.6365 beta=0.0054 lr=3.52e-04 time=12.3s

Эпохи:  65%|██████▌   | 13/20 [02:40<01:26, 12.40s/epoch, beta=0.006, kld=135.520, loss=71.658, lr=2.80e-04, nll=70.897]

2026-05-10 15:11:06.747 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 13: loss=71.6582 nll=70.8970 kld=135.5203 beta=0.0058 lr=2.80e-04 time=12.4s

Эпохи:  70%|███████   | 14/20 [02:53<01:14, 12.38s/epoch, beta=0.006, kld=133.024, loss=71.400, lr=2.14e-04, nll=70.593]

2026-05-10 15:11:19.077 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 14: loss=71.3996 nll=70.5927 kld=133.0241 beta=0.0063 lr=2.14e-04 time=12.3s

Эпохи:  75%|███████▌  | 15/20 [03:05<01:01, 12.35s/epoch, beta=0.007, kld=131.256, loss=71.245, lr=1.55e-04, nll=70.389]

2026-05-10 15:11:31.365 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 15: loss=71.2445 nll=70.3893 kld=131.2560 beta=0.0067 lr=1.55e-04 time=12.3s

Эпохи:  80%|████████  | 16/20 [03:17<00:49, 12.33s/epoch, beta=0.007, kld=129.540, loss=71.097, lr=1.05e-04, nll=70.194]

2026-05-10 15:11:43.655 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 16: loss=71.0966 nll=70.1943 kld=129.5400 beta=0.0072 lr=1.05e-04 time=12.3s

Эпохи:  85%|████████▌ | 17/20 [03:30<00:37, 12.38s/epoch, beta=0.008, kld=127.347, loss=71.071, lr=6.40e-05, nll=70.127]

2026-05-10 15:11:56.131 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 17: loss=71.0714 nll=70.1272 kld=127.3466 beta=0.0076 lr=6.40e-05 time=12.5s

Эпохи:  90%|█████████ | 18/20 [03:42<00:24, 12.39s/epoch, beta=0.008, kld=125.886, loss=70.988, lr=3.42e-05, nll=69.998]

2026-05-10 15:12:08.560 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 18: loss=70.9876 nll=69.9976 kld=125.8862 beta=0.0081 lr=3.42e-05 time=12.4s

Эпохи:  95%|█████████▌| 19/20 [03:55<00:12, 12.39s/epoch, beta=0.009, kld=124.704, loss=70.931, lr=1.61e-05, nll=69.894]

2026-05-10 15:12:20.940 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 19: loss=70.9306 nll=69.8938 kld=124.7036 beta=0.0085 lr=1.61e-05 time=12.4s

Эпохи: 100%|██████████| 20/20 [04:07<00:00, 12.39s/epoch, beta=0.009, kld=123.760, loss=71.003, lr=1.00e-05, nll=69.919]

2026-05-10 15:12:33.534 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 20: loss=71.0033 nll=69.9188 kld=123.7598 beta=0.0090 lr=1.00e-05 time=12.6s
2026-05-10 15:12:33.662 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_qj1q1ytj\artifacts\model.pt
2026-05-10 15:12:34.438 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_qj1q1ytj\artifacts
2026-05-10 15:12:34.634 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12148, dims=[600, 64], device=cuda
2026-05-10 15:12:34.643 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_qj1q1ytj\artifacts\model.pt
  Trial 19: target=log_target, dims=[600,64], dropout=0.6, beta=0.068, epochs=20, binary=False → NDCG@15=0.208878

Лучший trial #14:
  NDCG@15 = 0.210775
  target_col = log_target
  latent_dim = 64
  hidden_dim = 600
  dropout = 0.7
  beta = 0.10359660012799471
  epochs = 10
  binary = False

In [8]:
best = study.best_trial
print(f"\nЛучший trial #{best.number}:")
print(f"  NDCG@{TOP_K} = {best.value:.6f}")
for k, v in best.params.items():
    print(f"  {k} = {v}")

Лучший trial #14:
  NDCG@15 = 0.210775
  target_col = log_target
  latent_dim = 64
  hidden_dim = 600
  dropout = 0.7
  beta = 0.10359660012799471
  epochs = 10
  binary = False

In [12]:
best_params = {
    "target_col": "log_target",
    "latent_dim": 64,
    "hidden_dim": 600,
    "dropout": 0.7,
    "beta": 0.10359660012799471,
    "epochs": 10,
    "binary": False,
}

In [9]:
trials_df = pl.DataFrame([
    {
        "trial":      t.number,
        "ndcg":       t.value,
        "precision":  t.user_attrs.get("precision"),
        "recall":     t.user_attrs.get("recall"),
        "target_col": t.params["target_col"],
        "latent_dim": t.params["latent_dim"],
        "hidden_dim": t.params["hidden_dim"],
        "dropout":    t.params["dropout"],
        "beta":       t.params["beta"],
        "epochs":     t.params["epochs"],
        "binary":     t.params["binary"],
    }
    for t in study.trials
    if t.state == optuna.trial.TrialState.COMPLETE
]).sort("ndcg", descending=True)

trials_df

shape: (20, 11)
┌───────┬──────────┬───────────┬──────────┬───┬─────────┬──────────┬────────┬────────┐
│ trial ┆ ndcg     ┆ precision ┆ recall   ┆ … ┆ dropout ┆ beta     ┆ epochs ┆ binary │
│ ---   ┆ ---      ┆ ---       ┆ ---      ┆   ┆ ---     ┆ ---      ┆ ---    ┆ ---    │
│ i64   ┆ f64      ┆ f64       ┆ f64      ┆   ┆ f64     ┆ f64      ┆ i64    ┆ bool   │
╞═══════╪══════════╪═══════════╪══════════╪═══╪═════════╪══════════╪════════╪════════╡
│ 14    ┆ 0.210775 ┆ 0.057536  ┆ 0.041814 ┆ … ┆ 0.7     ┆ 0.103597 ┆ 10     ┆ false  │
│ 11    ┆ 0.210711 ┆ 0.057509  ┆ 0.041778 ┆ … ┆ 0.7     ┆ 0.113721 ┆ 10     ┆ false  │
│ 10    ┆ 0.21069  ┆ 0.057508  ┆ 0.041774 ┆ … ┆ 0.7     ┆ 0.117938 ┆ 10     ┆ false  │
│ 17    ┆ 0.210578 ┆ 0.055666  ┆ 0.040249 ┆ … ┆ 0.5     ┆ 0.099063 ┆ 15     ┆ false  │
│ 15    ┆ 0.209448 ┆ 0.055892  ┆ 0.040399 ┆ … ┆ 0.6     ┆ 0.081171 ┆ 15     ┆ false  │
│ …     ┆ …        ┆ …         ┆ …        ┆ … ┆ …       ┆ …        ┆ …      ┆ …      │
│ 6     ┆ 0.204295 ┆ 0.05303   ┆ 0.037863 ┆ … ┆ 0.5     ┆ 0.295078 ┆ 20     ┆ true   │
│ 4     ┆ 0.203279 ┆ 0.052967  ┆ 0.038299 ┆ … ┆ 0.5     ┆ 0.069166 ┆ 30     ┆ false  │
│ 0     ┆ 0.202504 ┆ 0.053189  ┆ 0.038063 ┆ … ┆ 0.6     ┆ 0.052427 ┆ 30     ┆ true   │
│ 2     ┆ 0.201925 ┆ 0.05213   ┆ 0.03762  ┆ … ┆ 0.2     ┆ 0.241659 ┆ 20     ┆ false  │
│ 5     ┆ 0.201903 ┆ 0.050865  ┆ 0.036853 ┆ … ┆ 0.2     ┆ 0.364816 ┆ 25     ┆ true   │
└───────┴──────────┴───────────┴──────────┴───┴─────────┴──────────┴────────┴────────┘

## Финальная оценка лучшего Mult-VAE на полном датасете

Переобучаем модель с найденными гиперпараметрами на **полном** train/test split — для прямого сравнения с iALS и SVD.

In [13]:
# best_params = best.params
print("Лучшие гиперпараметры (из hyperopt на subset):")
for k, v in best_params.items():
    print(f"  {k}: {v}")

# Фильтруем train по тем же 40k item-ам и тому же 30-дневному окну [DAY-29, DAY],
# что и в Optuna — чтобы финальная модель была сравнима с гиперопт-триалами
train_full = train.filter(pl.col("item_id").is_in(all_items_ids))

print("\nОбучение на полном датасете (OOM)...")
_tmp_dir = Path(tempfile.mkdtemp(prefix="vae_final_"))
try:
    _history_path  = _tmp_dir / "history.pq"
    _artifacts_dir = _tmp_dir / "artifacts"

    _item_to_idx, _user_to_idx = build_history_from_events(
        train_full,
        target_col=best_params["target_col"],
        output_path=_history_path,
        binary=best_params["binary"],
        min_interactions=5,
        min_day=DAY - 29,
    )
    print(f"  {len(_user_to_idx):,} пользователей x {len(_item_to_idx):,} items")

    train_vae(
        history_path=_history_path,
        item_to_idx=_item_to_idx,
        user_to_idx=_user_to_idx,
        artifacts_dir=_artifacts_dir,
        encoder_dims=[best_params["hidden_dim"], best_params["latent_dim"]],
        dropout=best_params["dropout"],
        beta=best_params["beta"],
        epochs=best_params["epochs"],
        batch_size=512,
        total_anneal_steps=200_000,
        use_lr_scheduler=True,
        num_workers=0,
        seed=SEED,
    )

    _rec = MultiVAERecommender()
    _rec.load(_artifacts_dir / "model.pt")
    _rec.set_user_items(load_npz(_artifacts_dir / "user_items.npz"))

    _metrics = evaluate_ndcg(_rec, test, target_col=best_params["target_col"], top_k=TOP_K)
finally:
    shutil.rmtree(_tmp_dir, ignore_errors=True)

best_vae_result = {
    "target":       best_params["target_col"],
    "encoder_dims": [best_params["hidden_dim"], best_params["latent_dim"]],
    "dropout":      best_params["dropout"],
    "beta":         best_params["beta"],
    "epochs":       best_params["epochs"],
    "top_k":        TOP_K,
    "ndcg":         _metrics["ndcg"],
    "precision":    _metrics["precision"],
    "recall":       _metrics["recall"],
    "rmse":         None,
    "mae":          None,
}

print("\nРезультат лучшего Mult-VAE (full data):")
for metric in ("ndcg", "precision", "recall"):
    print(f"  {metric}: {best_vae_result[metric]:.6f}")

Лучшие гиперпараметры (из hyperopt на subset):
  target_col: log_target
  latent_dim: 64
  hidden_dim: 600
  dropout: 0.7
  beta: 0.10359660012799471
  epochs: 10
  binary: False

Обучение на полном датасете (OOM)...
  350,650 пользователей x 12,866 items
2026-05-10 18:51:44.940 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12866, dims=[600, 64], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-10 18:51:45.072 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 350650 пользователей, 12866 items, batches per epoch ≈ 685

Сборка user_items: 100%|██████████| 350650/350650 [00:08<00:00, 39475.84user/s]
Эпохи:  10%|█         | 1/10 [00:23<03:35, 23.91s/epoch, beta=0.000, kld=163.004, loss=106.890, lr=9.76e-04, nll=106.855]

2026-05-10 18:52:18.392 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=106.8904 nll=106.8547 kld=163.0041 beta=0.0004 lr=9.76e-04 time=23.9s

Эпохи:  20%|██        | 2/10 [01:02<04:20, 32.58s/epoch, beta=0.001, kld=239.115, loss=94.185, lr=9.05e-04, nll=94.058]

2026-05-10 18:52:57.035 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=94.1850 nll=94.0581 kld=239.1151 beta=0.0007 lr=9.05e-04 time=38.6s

Эпохи:  30%|███       | 3/10 [01:25<03:16, 28.09s/epoch, beta=0.001, kld=217.366, loss=91.705, lr=7.96e-04, nll=91.513]

2026-05-10 18:53:19.798 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=91.7049 nll=91.5126 kld=217.3663 beta=0.0011 lr=7.96e-04 time=22.8s

Эпохи:  40%|████      | 4/10 [01:49<02:40, 26.69s/epoch, beta=0.001, kld=201.371, loss=90.353, lr=6.58e-04, nll=90.103]

2026-05-10 18:53:44.328 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=90.3530 nll=90.1033 kld=201.3710 beta=0.0014 lr=6.58e-04 time=24.5s

Эпохи:  50%|█████     | 5/10 [02:28<02:35, 31.12s/epoch, beta=0.002, kld=191.639, loss=89.394, lr=5.05e-04, nll=89.088]

2026-05-10 18:54:23.316 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=89.3937 nll=89.0879 kld=191.6393 beta=0.0018 lr=5.05e-04 time=39.0s

Эпохи:  60%|██████    | 6/10 [03:10<02:19, 34.81s/epoch, beta=0.002, kld=185.446, loss=88.762, lr=3.52e-04, nll=88.400]

2026-05-10 18:55:05.285 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=88.7617 nll=88.3999 kld=185.4458 beta=0.0021 lr=3.52e-04 time=42.0s

Эпохи:  70%|███████   | 7/10 [03:52<01:51, 37.19s/epoch, beta=0.002, kld=180.009, loss=88.209, lr=2.14e-04, nll=87.794]

2026-05-10 18:55:47.379 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=88.2092 nll=87.7941 kld=180.0087 beta=0.0025 lr=2.14e-04 time=42.1s

Эпохи:  80%|████████  | 8/10 [04:34<01:17, 38.55s/epoch, beta=0.003, kld=175.983, loss=87.874, lr=1.05e-04, nll=87.406]

2026-05-10 18:56:28.822 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=87.8742 nll=87.4060 kld=175.9827 beta=0.0028 lr=1.05e-04 time=41.4s

Эпохи:  90%|█████████ | 9/10 [05:16<00:39, 39.71s/epoch, beta=0.003, kld=172.485, loss=87.676, lr=3.42e-05, nll=87.156]

2026-05-10 18:57:11.087 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=87.6757 nll=87.1555 kld=172.4847 beta=0.0032 lr=3.42e-05 time=42.3s

Эпохи: 100%|██████████| 10/10 [05:58<00:00, 35.86s/epoch, beta=0.004, kld=170.460, loss=87.613, lr=1.00e-05, nll=87.039]

2026-05-10 18:57:53.121 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=87.6133 nll=87.0387 kld=170.4597 beta=0.0035 lr=1.00e-05 time=42.0s
2026-05-10 18:57:53.437 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_final_l006mvtd\artifacts\model.pt
2026-05-10 18:57:56.250 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_final_l006mvtd\artifacts
2026-05-10 18:57:56.814 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=12866, dims=[600, 64], device=cuda
2026-05-10 18:57:56.827 | INFO     | src.modeling.vae:load:517 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_final_l006mvtd\artifacts\model.pt

Результат лучшего Mult-VAE (full data):
  ndcg: 0.217632
  precision: 0.060075
  recall: 0.040805

## Сравнение Mult-VAE / iALS / SVD

Условия одинаковые для всех:

- **Данные**: marketplace events, global temporal split 80/20
- **Метрика ранжирования**: NDCG@15, Precision@15, Recall@15
- **SVD**: лучший результат из `svd_experiments_unified.ipynb`
- **iALS**: лучший результат из `ials_research.ipynb`
- **Mult-VAE**: конфигурация, найденная Optuna на 40%-подмножестве

In [14]:
svd_best = {
    "model":     "SVD (best)",
    "target":    "log_target",
    "top_k":     15,
    "ndcg":      0.135736,
    "precision": 0.026741,
    "recall":    0.026168,
    "rmse":      3.111453,
    "mae":       0.994588,
    "hyperopt":  "grid (ручной)",
}

ials_best = {
    "model":     "iALS (best, Optuna)",
    "target":    "log_target",
    "top_k":     15,
    "ndcg":      0.144,         # подставить актуальное из ials_research
    "precision": 0.027,         # подставить актуальное из ials_research
    "recall":    0.030,         # подставить актуальное из ials_research
    "rmse":      None,
    "mae":       None,
    "hyperopt":  "Optuna TPE, 25 trials, 40% subset",
}

vae_best = {
    "model":     "Mult-VAE (best, Optuna)",
    "target":    best_vae_result["target"],
    "top_k":     best_vae_result["top_k"],
    "ndcg":      best_vae_result["ndcg"],
    "precision": best_vae_result["precision"],
    "recall":    best_vae_result["recall"],
    "rmse":      best_vae_result["rmse"],
    "mae":       best_vae_result["mae"],
    "hyperopt":  f"Optuna TPE, {OPTUNA_TRIALS} trials, {SUBSET_FRACTION*100:.0f}% subset",
}

final_comparison = pl.DataFrame([svd_best, ials_best, vae_best])

ndcg_delta_vs_svd  = vae_best["ndcg"] - svd_best["ndcg"]
ndcg_delta_vs_ials = vae_best["ndcg"] - ials_best["ndcg"]
print(f"NDCG@15: SVD={svd_best['ndcg']:.4f}  iALS={ials_best['ndcg']:.4f}  Mult-VAE={vae_best['ndcg']:.4f}")
print(f"  Δ vs SVD:  {ndcg_delta_vs_svd:+.4f} ({ndcg_delta_vs_svd/svd_best['ndcg']*100:+.1f}%)")
print(f"  Δ vs iALS: {ndcg_delta_vs_ials:+.4f} ({ndcg_delta_vs_ials/ials_best['ndcg']*100:+.1f}%)")

final_comparison

NDCG@15: SVD=0.1357  iALS=0.1440  Mult-VAE=0.2176
  Δ vs SVD:  +0.0819 (+60.3%)
  Δ vs iALS: +0.0736 (+51.1%)

shape: (3, 9)
┌──────────────┬────────────┬───────┬──────────┬───┬──────────┬──────────┬──────────┬──────────────┐
│ model        ┆ target     ┆ top_k ┆ ndcg     ┆ … ┆ recall   ┆ rmse     ┆ mae      ┆ hyperopt     │
│ ---          ┆ ---        ┆ ---   ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---          │
│ str          ┆ str        ┆ i64   ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ str          │
╞══════════════╪════════════╪═══════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════════╡
│ SVD (best)   ┆ log_target ┆ 15    ┆ 0.135736 ┆ … ┆ 0.026168 ┆ 3.111453 ┆ 0.994588 ┆ grid         │
│              ┆            ┆       ┆          ┆   ┆          ┆          ┆          ┆ (ручной)     │
│ iALS (best,  ┆ log_target ┆ 15    ┆ 0.144    ┆ … ┆ 0.03     ┆ null     ┆ null     ┆ Optuna TPE,  │
│ Optuna)      ┆            ┆       ┆          ┆   ┆          ┆          ┆          ┆ 25 trials,   │
│              ┆            ┆       ┆          ┆   ┆          ┆          ┆          ┆ 40% sub…     │
│ Mult-VAE     ┆ log_target ┆ 15    ┆ 0.217632 ┆ … ┆ 0.040805 ┆ null     ┆ null     ┆ Optuna TPE,  │
│ (best,       ┆            ┆       ┆          ┆   ┆          ┆          ┆          ┆ 20 trials,   │
│ Optuna)      ┆            ┆       ┆          ┆   ┆          ┆          ┆          ┆ 40% sub…     │
└──────────────┴────────────┴───────┴──────────┴───┴──────────┴──────────┴──────────┴──────────────┘

## Выводы

- Mult-VAE учит нелинейное представление user-history и работает не на скалярном произведении, а на мультикатегориальном-распределении по items — это даёт ему преимущество на длинном хвосте.
- KL-annealing ($\beta$ от 0 до целевого) важен — без него VAE быстро коллапсирует в обычный AE.
- Логарифмированный таргет все еще лучше всего показывает себя в контексте качества модели. Также на текущий момент на MultVAE показывает наилучшие результаты по целевой метрике - ndcg@15.