In [1]:
import os
import pyarrow as pa     # импорт необходим, чтобы не крашился ноутбук на Windows
import numpy as np
import polars as pl
import torch

import src.dataset as dts
from src.modeling.vae import run_vae_experiment
from src.modeling.train_vae import build_user_history_dataset, train_vae
from src.config import VAE_DIR

import shutil
import tempfile
from pathlib import Path
from scipy.sparse import load_npz

from src.modeling.vae import MultiVAERecommender
from src.dataset import ndcg_at_k, precision_recall_at_k
print("torch:", torch.__version__)

2026-06-03 23:33:05.224 | INFO     | src.config:<module>:12 - PROJ_ROOT path is: D:\HSE_repos\dreamteam-recsys

torch: 2.12.0+cu130

In [2]:
EVENTS_DIR = "../data/raw/dataset/small/marketplace/events"

events_df = pl.scan_parquet(f"{EVENTS_DIR}/*.pq", include_file_paths="path").sort("day")

In [3]:
# Inverse-frequency target — тот же, что в SVD/iALS-ноутбуках для конформности.
actions_count = (
    events_df.group_by("action_type")
    .agg(pl.len())
    .collect(engine="streaming")
    .with_columns(
        (pl.col("len").sum() / pl.col("len")).alias("target"),
        (pl.col("len").sum() / pl.col("len")).log1p().alias("log_target"),
        (pl.col("len").sum() / pl.col("len")).sqrt().alias("sqrt_target"),
    )
    .drop("len")
)
events_df = events_df.join(actions_count.lazy(), on="action_type")
actions_count

shape: (4, 4)
┌─────────────┬─────────────┬────────────┬─────────────┐
│ action_type ┆ target      ┆ log_target ┆ sqrt_target │
│ ---         ┆ ---         ┆ ---        ┆ ---         │
│ str         ┆ f64         ┆ f64        ┆ f64         │
╞═════════════╪═════════════╪════════════╪═════════════╡
│ view        ┆ 1.034082    ┆ 0.710044   ┆ 1.016898    │
│ like        ┆ 3121.341812 ┆ 8.046339   ┆ 55.86897    │
│ click       ┆ 34.582149   ┆ 3.571844   ┆ 5.880659    │
│ clickout    ┆ 268.714913  ┆ 5.597366   ┆ 16.392526   │
└─────────────┴─────────────┴────────────┴─────────────┘

In [4]:
train, test = dts.global_temporal_split(events_df, 0.1)
print(f"Train schema: {train.collect_schema()}")
print(f"Test schema:  {test.collect_schema()}")

Train schema: Schema({'timestamp': Duration(time_unit='us'), 'user_id': UInt64, 'item_id': String, 'subdomain': String, 'action_type': String, 'os': String, 'day': Int32, 'path': String, 'target': Float64, 'log_target': Float64, 'sqrt_target': Float64})
Test schema:  Schema({'timestamp': Duration(time_unit='us'), 'user_id': UInt64, 'item_id': String, 'subdomain': String, 'action_type': String, 'os': String, 'day': Int32, 'path': String, 'target': Float64, 'log_target': Float64, 'sqrt_target': Float64})

In [5]:
best_params = {
    "target_col": "log_target",
    "latent_dim": 64,
    "hidden_dim": 800,
    "dropout": 0.7,
    "beta": 0.215,
    "epochs": 25,
    "binary": False,
    "batch_size": 360
}

In [6]:
def build_history_from_events(
    train_lf: pl.LazyFrame,
    target_col: str,
    output_path: Path,
    binary: bool = True,
    min_interactions: int = 3,
    min_day: int | None = None,
) -> tuple[dict[str, int], dict[int, int]]:
    """Строит sparse user-history parquet из LazyFrame событий.

    Выходная схема: (user_idx: u32, user_id: u64, item_idx: list[u32], weight: list[f32]).
    train_lf должен уже быть отфильтрован по нужным item_id.

    Parameters
    ----------
    min_day : int or None
        Если задан, используются только события с ``day >= min_day``.
        Позволяет ограничить историю конкретным временным окном,
        аналогично снимку ``build_user_history_dataset(day=DAY)``.
    """
    if min_day is not None:
        train_lf = train_lf.filter(pl.col("day") >= min_day)

    df = (
        train_lf
        .select("user_id", "item_id", target_col)
        .collect(engine="streaming")
        .group_by("user_id", "item_id")
        .agg(pl.col(target_col).sum())
    )

    valid_users = (
        df.group_by("user_id").agg(pl.len().alias("cnt"))
        .filter(pl.col("cnt") >= min_interactions).select("user_id")
    )
    valid_items = (
        df.group_by("item_id").agg(pl.len().alias("cnt"))
        .filter(pl.col("cnt") >= min_interactions).select("item_id")
    )
    df = df.join(valid_users, on="user_id").join(valid_items, on="item_id")

    item_ids_sorted = df.select("item_id").unique().sort("item_id")["item_id"].to_list()
    item_to_idx: dict[str, int] = {iid: idx for idx, iid in enumerate(item_ids_sorted)}
    items_meta = pl.DataFrame(
        {"item_id": item_ids_sorted, "item_idx": list(range(len(item_ids_sorted)))},
        schema={"item_id": pl.String, "item_idx": pl.UInt32},
    )

    if binary:
        df = df.with_columns(weight=pl.lit(1.0, dtype=pl.Float32))
    else:
        df = df.with_columns(weight=pl.col(target_col).cast(pl.Float32))

    df = df.join(items_meta, on="item_id")

    user_df = (
        df.group_by("user_id")
        .agg(pl.col("item_idx"), pl.col("weight"))
        .sort("user_id")
        .with_row_index("user_idx")
        .with_columns(pl.col("user_idx").cast(pl.UInt32))
    )
    user_to_idx: dict[int, int] = dict(
        zip(user_df["user_id"].to_list(), user_df["user_idx"].to_list())
    )

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    user_df.select("user_idx", "user_id", "item_idx", "weight").write_parquet(output_path)
    return item_to_idx, user_to_idx


def evaluate_ndcg(
    rec: MultiVAERecommender,
    test_lf: pl.LazyFrame,
    target_col: str,
    top_k: int = 15,
) -> dict:
    """Считает NDCG/Precision/Recall на тестовой выборке."""
    test_df = test_lf.select("user_id", "item_id", target_col).collect(engine="streaming")
    known_users = set(rec.user_to_idx.keys())
    test_filtered = test_df.filter(pl.col("user_id").is_in(known_users))

    user_test_truth = test_filtered.group_by("user_id").agg(
        pl.col("item_id").alias("true_items"),
        pl.col(target_col).alias("relevancy"),
    )
    test_user_ids = user_test_truth["user_id"].to_numpy()
    test_user_idxs = np.array([rec.user_to_idx[uid] for uid in test_user_ids])

    BATCH = 1024
    item_idx_chunks, score_chunks = [], []
    for start in range(0, len(test_user_idxs), BATCH):
        chunk = test_user_idxs[start : start + BATCH]
        ids, scores = rec.recommend_batch(chunk, top_k=top_k)
        item_idx_chunks.append(ids)
        score_chunks.append(scores)

    item_idx_matrix = np.concatenate(item_idx_chunks, axis=0)
    score_matrix    = np.concatenate(score_chunks,    axis=0)

    predicted_items_list  = [[rec.idx_to_item[i] for i in row] for row in item_idx_matrix]
    predicted_scores_list = [row.tolist() for row in score_matrix]

    prediction_df  = pl.DataFrame({
        "user_id":          test_user_ids,
        "predicted_items":  predicted_items_list,
        "predicted_scores": predicted_scores_list,
    })
    evaluation_df = user_test_truth.join(prediction_df, on="user_id")

    ndcg_results = ndcg_at_k(
        evaluation_df,
        relevancy_col="relevancy",
        true_items_col="true_items",
        predicted_items_col="predicted_items",
        predicted_score_col="predicted_scores",
        top_k=top_k,
    )
    mean_ndcg = float(ndcg_results["ndcg"].mean())
    precision, recall = precision_recall_at_k(
        evaluation_df,
        predicted_items_col="predicted_items",
        true_items_col="true_items",
        top_k=top_k,
    )
    return {"ndcg": mean_ndcg, "precision": precision, "recall": recall}

In [7]:
DAY = 1276
SEED = 42
TOP_K= 15

In [8]:
from dotenv import load_dotenv
import mlflow
import mlflow.exceptions

load_dotenv("../.env") 

# Переопределяю адрес, так как у меня заняты порты на локальной машине
# os.environ["MLFLOW_S3_ENDPOINT_URL"] = "http://localhost:19000"
# ====== S3 / MinIO конфиг ======
os.environ["AWS_ACCESS_KEY_ID"] = os.getenv("MINIO_ROOT_USER")
os.environ["AWS_SECRET_ACCESS_KEY"] = os.getenv("MINIO_ROOT_PASSWORD")

# важно: чтобы MLflow понимал, что это MinIO, а не AWS
os.environ["MLFLOW_S3_ENDPOINT_URL"] = "http://localhost:9000"

mlflow.set_tracking_uri("http://localhost:5050")
experiment_name = "MultVAE"

try:
    exp_id = mlflow.create_experiment(
        name=experiment_name,
        artifact_location=f"s3://{os.getenv("DEFAULT_BUCKET_NAME")}"
    )
except mlflow.exceptions.MlflowException:
    exp_id = mlflow.get_experiment_by_name(experiment_name).experiment_id

mlflow.set_experiment(experiment_name)

print(f"Подключено к MLflow. Эксперимент: {experiment_name}")
print(f"Tracking URI: {mlflow.get_tracking_uri()}")

Подключено к MLflow. Эксперимент: MultVAE
Tracking URI: http://localhost:5050

In [9]:
ITEMS_TO_TAKE = 20_000

all_items_ids = (
    train.group_by("item_id").agg(count=pl.len()).sort("count", descending=True).head(ITEMS_TO_TAKE).collect(engine="streaming")["item_id"].to_list()
)

In [10]:
import json


with mlflow.start_run(run_name="multvae_full_data", tags={"stage": "PRD"}) as run:

    # Фильтруем train по тем же 40k item-ам и тому же 30-дневному окну [DAY-29, DAY],
    # что и в Optuna — чтобы финальная модель была сравнима с гиперопт-триалами
    train_full = train.filter(pl.col("item_id").is_in(all_items_ids))

    print("\nОбучение на полном датасете (OOM)...")
    _tmp_dir = Path(tempfile.mkdtemp(prefix="vae_final_"))
    try:
        _history_path = _tmp_dir / "history.pq"
        _artifacts_dir = _tmp_dir / "artifacts"

        _item_to_idx, _user_to_idx = build_history_from_events(
            train_full,
            target_col=best_params["target_col"],
            output_path=_history_path,
            binary=best_params["binary"],
            min_interactions=5,
            min_day=DAY - 29,
        )
        print(f"  {len(_user_to_idx):,} пользователей x {len(_item_to_idx):,} items")

        mlflow.log_params(best_params)
        train_vae(
            history_path=_history_path,
            item_to_idx=_item_to_idx,
            user_to_idx=_user_to_idx,
            artifacts_dir=_artifacts_dir,
            encoder_dims=[best_params["hidden_dim"], best_params["latent_dim"]],
            dropout=best_params["dropout"],
            beta=best_params["beta"],
            epochs=best_params["epochs"],
            batch_size=best_params["batch_size"],
            total_anneal_steps=200_000,
            use_lr_scheduler=True,
            num_workers=12,
            seed=SEED,
        )

        _rec = MultiVAERecommender()
        _rec.load(_artifacts_dir / "model.pt")
        _rec.set_user_items(load_npz(_artifacts_dir / "user_items.npz"))

        _metrics_train = evaluate_ndcg(
            _rec, train, target_col=best_params["target_col"], top_k=TOP_K
        )
        _metrics_train = {f"train_{k}": v for k, v in _metrics_train.items()}
        _metrics_test = evaluate_ndcg(_rec, test, target_col=best_params["target_col"], top_k=TOP_K)
        _metrics_test = {f"test_{k}": v for k, v in _metrics_test.items()}
        
        mlflow.log_metrics({**_metrics_train, **_metrics_test})

        _rec.save(_artifacts_dir / "model")
        
        with open(_artifacts_dir / "items_ids.json", "w") as f:
            json.dump(all_items_ids, f)
        mlflow.log_artifact(str(_artifacts_dir / "model"))
        mlflow.log_artifact(str(_artifacts_dir / "items_ids.json"))
        mlflow.log_artifact(str(_artifacts_dir / "user_items.npz"))
        # mlflow.log_artifact(str(_artifacts_dir))
        print("Run ID:", run.info.run_id)
    finally:
        shutil.rmtree(_tmp_dir, ignore_errors=True)

Обучение на полном датасете (OOM)...
  628,315 пользователей x 14,522 items
2026-06-03 23:33:19.600 | INFO     | src.modeling.vae:build_model:385 - MultiVAE собрана: num_items=14522, dims=[800, 64], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-06-03 23:33:20.081 | INFO     | src.modeling.train_vae:train_vae:370 - Стартую обучение: 628315 пользователей, 14522 items, batches per epoch ≈ 1746

Сборка user_items: 100%|██████████| 628315/628315 [00:23<00:00, 26407.78user/s]
Эпохи:   4%|▍         | 1/25 [00:40<16:08, 40.36s/epoch, beta=0.002, kld=196.997, loss=156.929, lr=9.96e-04, nll=156.728]

2026-06-03 23:34:27.472 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 01: loss=156.9289 nll=156.7283 kld=196.9974 beta=0.0019 lr=9.96e-04 time=40.4s

Эпохи:   8%|▊         | 2/25 [01:19<15:13, 39.70s/epoch, beta=0.004, kld=181.905, loss=145.715, lr=9.84e-04, nll=145.208]

2026-06-03 23:35:06.720 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 02: loss=145.7149 nll=145.2076 kld=181.9052 beta=0.0038 lr=9.84e-04 time=39.2s

Эпохи:  12%|█▏        | 3/25 [01:54<13:45, 37.52s/epoch, beta=0.006, kld=160.644, loss=143.690, lr=9.65e-04, nll=142.939]

2026-06-03 23:35:41.633 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 03: loss=143.6904 nll=142.9387 kld=160.6443 beta=0.0056 lr=9.65e-04 time=34.9s

Эпохи:  16%|█▌        | 4/25 [02:34<13:29, 38.55s/epoch, beta=0.008, kld=149.268, loss=142.722, lr=9.39e-04, nll=141.743]

2026-06-03 23:36:21.779 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 04: loss=142.7221 nll=141.7430 kld=149.2684 beta=0.0075 lr=9.39e-04 time=40.1s

Эпохи:  20%|██        | 5/25 [03:12<12:48, 38.45s/epoch, beta=0.009, kld=140.244, loss=142.132, lr=9.05e-04, nll=140.949]

2026-06-03 23:37:00.041 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 05: loss=142.1322 nll=140.9489 kld=140.2437 beta=0.0094 lr=9.05e-04 time=38.3s

Эпохи:  24%|██▍       | 6/25 [03:53<12:21, 39.03s/epoch, beta=0.011, kld=133.371, loss=141.717, lr=8.66e-04, nll=140.341]

2026-06-03 23:37:40.191 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 06: loss=141.7169 nll=140.3412 kld=133.3706 beta=0.0113 lr=8.66e-04 time=40.1s

Эпохи:  28%|██▊       | 7/25 [04:33<11:49, 39.41s/epoch, beta=0.013, kld=126.545, loss=141.418, lr=8.21e-04, nll=139.875]

2026-06-03 23:38:20.373 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 07: loss=141.4184 nll=139.8755 kld=126.5453 beta=0.0131 lr=8.21e-04 time=40.2s

Эпохи:  32%|███▏      | 8/25 [05:06<10:34, 37.34s/epoch, beta=0.015, kld=120.751, loss=141.100, lr=7.70e-04, nll=139.401]

2026-06-03 23:38:53.287 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 08: loss=141.0996 nll=139.4008 kld=120.7509 beta=0.0150 lr=7.70e-04 time=32.9s

Эпохи:  36%|███▌      | 9/25 [05:40<09:41, 36.32s/epoch, beta=0.017, kld=115.334, loss=140.878, lr=7.16e-04, nll=139.039]

2026-06-03 23:39:27.362 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 09: loss=140.8783 nll=139.0390 kld=115.3345 beta=0.0169 lr=7.16e-04 time=34.1s

Эпохи:  40%|████      | 10/25 [06:20<09:22, 37.49s/epoch, beta=0.019, kld=110.659, loss=140.605, lr=6.58e-04, nll=138.633]

2026-06-03 23:40:07.476 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 10: loss=140.6055 nll=138.6330 kld=110.6593 beta=0.0188 lr=6.58e-04 time=40.1s

Эпохи:  44%|████▍     | 11/25 [07:01<09:01, 38.70s/epoch, beta=0.021, kld=106.209, loss=140.433, lr=5.98e-04, nll=138.341]

2026-06-03 23:40:48.928 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 11: loss=140.4332 nll=138.3407 kld=106.2089 beta=0.0206 lr=5.98e-04 time=41.5s

Эпохи:  48%|████▊     | 12/25 [07:43<08:33, 39.49s/epoch, beta=0.023, kld=102.276, loss=140.257, lr=5.36e-04, nll=138.050]

2026-06-03 23:41:30.207 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 12: loss=140.2571 nll=138.0501 kld=102.2760 beta=0.0225 lr=5.36e-04 time=41.3s

Эпохи:  52%|█████▏    | 13/25 [08:24<08:01, 40.12s/epoch, beta=0.024, kld=98.652, loss=140.010, lr=4.74e-04, nll=137.696]

2026-06-03 23:42:11.780 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 13: loss=140.0102 nll=137.6961 kld=98.6525 beta=0.0244 lr=4.74e-04 time=41.6s

Эпохи:  56%|█████▌    | 14/25 [09:03<07:17, 39.77s/epoch, beta=0.026, kld=95.407, loss=139.876, lr=4.12e-04, nll=137.459]

2026-06-03 23:42:50.731 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 14: loss=139.8759 nll=137.4589 kld=95.4074 beta=0.0263 lr=4.12e-04 time=38.9s

Эпохи:  60%|██████    | 15/25 [09:43<06:38, 39.90s/epoch, beta=0.028, kld=92.567, loss=139.712, lr=3.52e-04, nll=137.193]

2026-06-03 23:43:30.935 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 15: loss=139.7117 nll=137.1928 kld=92.5669 beta=0.0282 lr=3.52e-04 time=40.2s

Эпохи:  64%|██████▍   | 16/25 [10:24<06:01, 40.17s/epoch, beta=0.030, kld=89.763, loss=139.615, lr=2.94e-04, nll=137.004]

2026-06-03 23:44:11.725 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 16: loss=139.6146 nll=137.0036 kld=89.7632 beta=0.0300 lr=2.94e-04 time=40.8s

Эпохи:  68%|██████▊   | 17/25 [11:03<05:18, 39.76s/epoch, beta=0.032, kld=87.159, loss=139.464, lr=2.40e-04, nll=136.765]

2026-06-03 23:44:50.553 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 17: loss=139.4637 nll=136.7647 kld=87.1593 beta=0.0319 lr=2.40e-04 time=38.8s

Эпохи:  72%|███████▏  | 18/25 [11:45<04:43, 40.53s/epoch, beta=0.034, kld=84.817, loss=139.350, lr=1.89e-04, nll=136.564]

2026-06-03 23:45:32.852 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 18: loss=139.3497 nll=136.5641 kld=84.8173 beta=0.0338 lr=1.89e-04 time=42.3s

Эпохи:  76%|███████▌  | 19/25 [12:26<04:04, 40.68s/epoch, beta=0.036, kld=82.769, loss=139.303, lr=1.44e-04, nll=136.429]

2026-06-03 23:46:13.906 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 19: loss=139.3027 nll=136.4288 kld=82.7693 beta=0.0357 lr=1.44e-04 time=41.1s

Эпохи:  80%|████████  | 20/25 [13:05<03:20, 40.00s/epoch, beta=0.038, kld=80.817, loss=139.265, lr=1.05e-04, nll=136.307]

2026-06-03 23:46:52.320 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 20: loss=139.2649 nll=136.3072 kld=80.8173 beta=0.0375 lr=1.05e-04 time=38.4s

Эпохи:  84%|████████▍ | 21/25 [13:46<02:41, 40.38s/epoch, beta=0.039, kld=79.156, loss=139.275, lr=7.12e-05, nll=136.230]

2026-06-03 23:47:33.568 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 21: loss=139.2752 nll=136.2297 kld=79.1559 beta=0.0394 lr=7.12e-05 time=41.2s

Эпохи:  88%|████████▊ | 22/25 [14:25<01:59, 39.83s/epoch, beta=0.041, kld=77.629, loss=139.313, lr=4.48e-05, nll=136.181]

2026-06-03 23:48:12.133 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 22: loss=139.3134 nll=136.1810 kld=77.6290 beta=0.0413 lr=4.48e-05 time=38.6s

Эпохи:  92%|█████████▏| 23/25 [15:06<01:20, 40.22s/epoch, beta=0.043, kld=76.094, loss=139.357, lr=2.56e-05, nll=136.143]

2026-06-03 23:48:53.240 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 23: loss=139.3565 nll=136.1432 kld=76.0936 beta=0.0432 lr=2.56e-05 time=41.1s

Эпохи:  96%|█████████▌| 24/25 [15:46<00:40, 40.41s/epoch, beta=0.045, kld=74.873, loss=139.401, lr=1.39e-05, nll=136.099]

2026-06-03 23:49:34.091 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 24: loss=139.4008 nll=136.0985 kld=74.8729 beta=0.0450 lr=1.39e-05 time=40.8s

Эпохи: 100%|██████████| 25/25 [16:27<00:00, 39.50s/epoch, beta=0.047, kld=73.629, loss=139.524, lr=1.00e-05, nll=136.138]

2026-06-03 23:50:14.638 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 25: loss=139.5237 nll=136.1380 kld=73.6288 beta=0.0469 lr=1.00e-05 time=40.5s
2026-06-03 23:50:15.098 | INFO     | src.modeling.vae:save:477 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_final_f5is07j5\artifacts\model.pt
2026-06-03 23:50:22.760 | INFO     | src.modeling.train_vae:train_vae:490 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_final_f5is07j5\artifacts
2026-06-03 23:50:23.744 | INFO     | src.modeling.vae:build_model:385 - MultiVAE собрана: num_items=14522, dims=[800, 64], device=cuda
2026-06-03 23:50:23.762 | INFO     | src.modeling.vae:load:497 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_final_f5is07j5\artifacts\model.pt
2026-06-03 23:54:55.293 | INFO     | src.modeling.vae:save:477 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_final_f5is07j5\artifacts\model
Run ID: 57a7576a36394e87829afd763ca77a02
🏃 View run multvae_full_data at: http://localhost:5050/#/experiments/2/runs/57a7576a36394e87829afd763ca77a02
🧪 View experiment at: http://localhost:5050/#/experiments/2

## Проверяем устойчивость

In [ ]:
import numpy as np
from mlflow.artifacts import download_artifacts
from scipy.sparse import load_npz

TOP_K = 10
N_USERS = 1000
REMOVE_ITEMS = 1


def jaccard(a, b):
    a = set(a)
    b = set(b)

    if not (a or b):
        return 1.0

    return len(a & b) / len(a | b)


def stability(a, b):
    a = set(a)
    b = set(b)

    return len(a & b) / len(a)


def load_model_from_mlflow(run_id):

    model_file = download_artifacts(
        artifact_uri=f"runs:/{run_id}/model"
    )

    rec = MultiVAERecommender()
    rec.load(model_file)

    return rec

def load_npz_from_mlflow(run_id):
    user_items_path = download_artifacts(
        artifact_uri=f"runs:/{run_id}/user_items.npz"
    )

    return load_npz(user_items_path)


def robustness_test(
    rec,
    user_items,
    top_k=10,
    n_users=1000,
    remove_items=1,
):

    rec.set_user_items(user_items)

    all_users = np.arange(user_items.shape[0])

    if len(all_users) > n_users:
        all_users = np.random.choice(
            all_users,
            size=n_users,
            replace=False,
        )

    stabilities = []
    jaccards = []
    changed_positions = []

    for user_idx in all_users:

        history = user_items[user_idx].copy()

        interacted = history.indices

        if len(interacted) <= remove_items:
            continue

        original_items, _ = rec.recommend_batch(
            np.array([user_idx]),
            top_k=top_k,
        )

        original_rec = original_items[0]

        perturbed_history = history.copy()

        removed = np.random.choice(
            interacted,
            size=remove_items,
            replace=False,
        )

        for item in removed:
            perturbed_history[0, item] = 0

        original_user_history = rec.user_items[user_idx]
        rec.user_items[user_idx] = perturbed_history

        perturbed_items, _ = rec.recommend_batch(
            np.array([user_idx]),
            top_k=top_k,
        )

        perturbed_rec = perturbed_items[0]

        rec.user_items[user_idx] = original_user_history

        stabilities.append(
            stability(original_rec, perturbed_rec)
        )

        jaccards.append(
            jaccard(original_rec, perturbed_rec)
        )

        changed_positions.append(
            np.sum(original_rec != perturbed_rec)
        )

    return {
        "robustness_topk_stability_mean": float(np.mean(stabilities)),
        "robustness_topk_stability_std": float(np.std(stabilities)),
        "robustness_jaccard_mean": float(np.mean(jaccards)),
        "robustness_jaccard_std": float(np.std(jaccards)),
        "robustness_changed_items_mean": float(np.mean(changed_positions)),
        "robustness_users_count": int(len(stabilities)),
    }

In [13]:
RUN_ID = "57a7576a36394e87829afd763ca77a02"


rec = load_model_from_mlflow(RUN_ID)

user_items = load_npz_from_mlflow(RUN_ID)


for top_k in [10, 20, 30]:
    for remove_items in [1, 2, 3]:

        with mlflow.start_run(run_name="multvae_robustness_test"):

            mlflow.log_param("source_run_id", RUN_ID)
            mlflow.log_param("top_k", top_k)
            mlflow.log_param("remove_items", remove_items)

            metrics = robustness_test(
                rec,
                user_items,
                top_k=top_k,
                n_users=1000,
                remove_items=remove_items,
            )

            mlflow.log_metrics(metrics)

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-03 23:57:09.980 | INFO     | src.modeling.vae:build_model:385 - MultiVAE собрана: num_items=14522, dims=[800, 64], device=cuda
2026-06-03 23:57:09.991 | INFO     | src.modeling.vae:load:497 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\tmpk3ot8tts\model

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

🏃 View run multvae_robustness_test at: http://localhost:5050/#/experiments/2/runs/0bc2e131dfc7468dad3b30da868c2381
🧪 View experiment at: http://localhost:5050/#/experiments/2
🏃 View run multvae_robustness_test at: http://localhost:5050/#/experiments/2/runs/962bf63d0e454bd0986b4b4812bc65bf
🧪 View experiment at: http://localhost:5050/#/experiments/2
🏃 View run multvae_robustness_test at: http://localhost:5050/#/experiments/2/runs/be71d2e39cfc40d896112f854d1bf6bc
🧪 View experiment at: http://localhost:5050/#/experiments/2
🏃 View run multvae_robustness_test at: http://localhost:5050/#/experiments/2/runs/7ac6691ef88d4507bdbadc02ae5d2e37
🧪 View experiment at: http://localhost:5050/#/experiments/2
🏃 View run multvae_robustness_test at: http://localhost:5050/#/experiments/2/runs/96e941a1136f4c818c450465a77195ff
🧪 View experiment at: http://localhost:5050/#/experiments/2
🏃 View run multvae_robustness_test at: http://localhost:5050/#/experiments/2/runs/295ac58eeb2141afa4f134b51c573cb3
🧪 View experiment at: http://localhost:5050/#/experiments/2
🏃 View run multvae_robustness_test at: http://localhost:5050/#/experiments/2/runs/0261c1be48694b6280b443a0316a2454
🧪 View experiment at: http://localhost:5050/#/experiments/2
🏃 View run multvae_robustness_test at: http://localhost:5050/#/experiments/2/runs/95b83fa6b9674506956c603ba3a21f1a
🧪 View experiment at: http://localhost:5050/#/experiments/2
🏃 View run multvae_robustness_test at: http://localhost:5050/#/experiments/2/runs/c98efa998152474cb9fc228ffa4f7fcb
🧪 View experiment at: http://localhost:5050/#/experiments/2

## Загружаем продовую модель

In [ ]:

exp = mlflow.get_experiment_by_name("MultVAE")

runs = mlflow.search_runs(
    experiment_ids=[exp.experiment_id],
    filter_string="tags.stage = 'PRD'",
    order_by=["start_time DESC"],
    max_results=1
)

latest_run_id = runs.iloc[0]["run_id"]

57a7576a36394e87829afd763ca77a02

In [16]:
model = load_model_from_mlflow(latest_run_id)

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-04 00:04:48.199 | INFO     | src.modeling.vae:build_model:385 - MultiVAE собрана: num_items=14522, dims=[800, 64], device=cuda
2026-06-04 00:04:48.215 | INFO     | src.modeling.vae:load:497 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\tmpafzwjx04\model

In [ ]:
model.set_user_items(load_npz_from_mlflow(latest_run_id))

In [51]:
test_users = (
    test.select("user_id")
    .filter(pl.col("user_id").is_in(model.user_to_idx.keys()))
    .head(20)
    .collect()["user_id"]
    .to_list()
)

In [61]:
test_users

[50145974,
 14042715,
 69416985,
 8116339,
 44852811,
 77485130,
 14443163,
 59670886,
 80598643,
 84508206,
 54083133,
 26229418,
 88831493,
 20428132,
 46443338,
 60195175,
 4463183,
 36260945,
 4169312,
 85219578]

In [52]:
test_users_idx = np.array(
    list(
        x
        for x in (
            map(
                model.user_to_idx.get,
                test_users,
            )
        )
        if x is not None
    )
)

In [56]:
recs = model.recommend_batch(test_users_idx, top_k=10)[0]

In [58]:
recs.shape

(20, 10)

In [59]:
recommendations = np.vectorize(model.idx_to_item.get)(recs)
recommendations_df = pl.DataFrame({"user_id": test_users,"recommendations": list(x for x in recommendations)})

In [60]:
recommendations_df

shape: (20, 2)
┌──────────┬─────────────────────────────────┐
│ user_id  ┆ recommendations                 │
│ ---      ┆ ---                             │
│ i64      ┆ array[str, 10]                  │
╞══════════╪═════════════════════════════════╡
│ 50145974 ┆ ["nfmcg_20564139", "nfmcg_2217… │
│ 14042715 ┆ ["nfmcg_18106422", "nfmcg_1438… │
│ 69416985 ┆ ["nfmcg_7537528", "nfmcg_89614… │
│ 8116339  ┆ ["nfmcg_716576", "nfmcg_129771… │
│ 44852811 ┆ ["nfmcg_23226394", "nfmcg_7997… │
│ …        ┆ …                               │
│ 60195175 ┆ ["nfmcg_2501643", "nfmcg_18954… │
│ 4463183  ┆ ["nfmcg_27366316", "nfmcg_7165… │
│ 36260945 ┆ ["nfmcg_7763862", "nfmcg_22204… │
│ 4169312  ┆ ["nfmcg_19353812", "nfmcg_2736… │
│ 85219578 ┆ ["nfmcg_9041331", "nfmcg_77638… │
└──────────┴─────────────────────────────────┘