# Mult-VAE: исследование на marketplace-домене

Аналог `ials_research.ipynb` для **Multinomial Variational AutoEncoder**
(Liang et al. 2018). Структура повторяет IALS-ноутбук, чтобы сравнение с
SVD/iALS было воспроизводимым:

1. Загрузка событий, inverse-frequency target.
2. Temporal split 80/20.
3. Базовый прогон с типовыми гиперпараметрами.
4. Optuna на 40%-подмножестве пользователей.
5. Финальная оценка лучшей конфигурации на полных данных.
6. Сравнение Mult-VAE / iALS / SVD.

In [1]:
import os
import pyarrow as pa     # импорт необходим, чтобы не крашился ноутбук на Windows
import numpy as np
import polars as pl
import torch

import src.dataset as dts
from src.modeling.vae import run_vae_experiment
from src.modeling.train_vae import build_user_history_dataset, train_vae
from src.config import VAE_DIR

import shutil
import tempfile
from pathlib import Path
from scipy.sparse import load_npz

from src.modeling.vae import MultiVAERecommender
from src.dataset import ndcg_at_k, precision_recall_at_k
print("torch:", torch.__version__)

2026-06-01 22:34:12.106 | INFO     | src.config:<module>:12 - PROJ_ROOT path is: D:\HSE_repos\dreamteam-recsys

torch: 2.12.0+cu130

In [2]:
EVENTS_DIR = "../data/raw/dataset/small/marketplace/events"

events_df = pl.scan_parquet(f"{EVENTS_DIR}/*.pq", include_file_paths="path").sort("day")

In [3]:
# Inverse-frequency target — тот же, что в SVD/iALS-ноутбуках для конформности.
actions_count = (
    events_df.group_by("action_type")
    .agg(pl.len())
    .collect(engine="streaming")
    .with_columns(
        (pl.col("len").sum() / pl.col("len")).alias("target"),
        (pl.col("len").sum() / pl.col("len")).log1p().alias("log_target"),
        (pl.col("len").sum() / pl.col("len")).sqrt().alias("sqrt_target"),
    )
    .drop("len")
)
events_df = events_df.join(actions_count.lazy(), on="action_type")
actions_count

shape: (4, 4)
┌─────────────┬─────────────┬────────────┬─────────────┐
│ action_type ┆ target      ┆ log_target ┆ sqrt_target │
│ ---         ┆ ---         ┆ ---        ┆ ---         │
│ str         ┆ f64         ┆ f64        ┆ f64         │
╞═════════════╪═════════════╪════════════╪═════════════╡
│ like        ┆ 3121.341812 ┆ 8.046339   ┆ 55.86897    │
│ view        ┆ 1.034082    ┆ 0.710044   ┆ 1.016898    │
│ click       ┆ 34.582149   ┆ 3.571844   ┆ 5.880659    │
│ clickout    ┆ 268.714913  ┆ 5.597366   ┆ 16.392526   │
└─────────────┴─────────────┴────────────┴─────────────┘

In [4]:
train, test = dts.global_temporal_split(events_df, 0.2)
print(f"Train schema: {train.collect_schema()}")
print(f"Test schema:  {test.collect_schema()}")

Train schema: Schema({'timestamp': Duration(time_unit='us'), 'user_id': UInt64, 'item_id': String, 'subdomain': String, 'action_type': String, 'os': String, 'day': Int32, 'path': String, 'target': Float64, 'log_target': Float64, 'sqrt_target': Float64})
Test schema:  Schema({'timestamp': Duration(time_unit='us'), 'user_id': UInt64, 'item_id': String, 'subdomain': String, 'action_type': String, 'os': String, 'day': Int32, 'path': String, 'target': Float64, 'log_target': Float64, 'sqrt_target': Float64})

## Базовый прогон (OOM, GPU)

Архитектура `[600, 200]` — конфиг из оригинальной статьи Mult-VAE.
Бинаризованная история (`binary=True`) — стандартный режим для CF-VAE.

**Почему не `run_vae_experiment`?** На полном marketplace-сплите
(1.2M users × 498k items, 65M пар) `run_vae_experiment` строит
in-memory CSR + decoder ~498k → KILL'ом по VRAM на любой потребительской
карте. Поэтому baseline учим тем же OOM-стеком, что и CLI
(`python -m src.modeling.train_vae train`):

* feature-снимок `data/processed/datamart/features/events/user_id-item_id/{day}.pq`
  уже агрегирует 30-дневное окно → **20 000 selected items** и
  **~184 000 активных пользователей** (по `selected_items.pq` /
  `selected_users.pq`);
* sparse user-history стримится через `polars.sink_parquet`, дальше
  материализуется лениво HuggingFace `datasets` (Apache Arrow,
  memory-mapped);
* dense батч `(B, num_items)` собирается в коллатере **только** на текущий
  step и сразу освобождается.

**Параметры зеркалят успешный CLI-прогон**: `day=1305, epochs=30,
batch_size=256` (этот же набор стабильно работал на RTX 2080 SUPER 8GB).

> Target-leak: feature-снимок дня `D` агрегирует окно `[D-29, D]`,
> поэтому если соберётесь добавлять метрики поверх `test`, оценивать
> можно только события за дни `> D`.

In [5]:
import shutil
import tempfile
from pathlib import Path

DAY                = 1305          # снимок 30-дневного окна [1276, 1305]
EPOCHS             = 30
BATCH_SIZE         = 256
ENCODER_DIMS       = [600, 200]
DROPOUT            = 0.5
BETA               = 0.2
TOTAL_ANNEAL_STEPS = 200_000
KL_SCHEDULE        = "linear"
LR                 = 1e-3
WEIGHT_DECAY       = 0.0
BINARY             = True
MIN_USER_ITEMS     = 5
SEED               = 42

# Создаем временную папку для хранения истории
tmp_dir = Path(tempfile.mkdtemp(prefix="vae_history_"))
history_path = tmp_dir / "history.pq"
try:
    history_path, item_to_idx, user_to_idx = build_user_history_dataset(
        day=DAY,
        output_path=history_path,
        binary=BINARY,
        min_user_items=MIN_USER_ITEMS,
    )
    print(
        f"Снимок дня {DAY}: "
        f"{len(user_to_idx):,} активных users x {len(item_to_idx):,} items"
    )

    checkpoint_path = train_vae(
        history_path=history_path,
        item_to_idx=item_to_idx,
        user_to_idx=user_to_idx,
        artifacts_dir=VAE_DIR,
        encoder_dims=ENCODER_DIMS,
        dropout=DROPOUT,
        beta=BETA,
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        lr=LR,
        weight_decay=WEIGHT_DECAY,
        total_anneal_steps=TOTAL_ANNEAL_STEPS,
        kl_schedule=KL_SCHEDULE,
        use_lr_scheduler=True,
        num_workers=0,            # Windows: иначе DataLoader крашится
        seed=SEED,
    )
    print(f"Чекпоинт сохранён: {checkpoint_path}")
finally:
    shutil.rmtree(tmp_dir, ignore_errors=True)

2026-05-09 23:39:17.841 | INFO     | src.modeling.train_vae:build_user_history_dataset:142 - Сбор маппингов item/user...
2026-05-09 23:39:17.853 | INFO     | src.modeling.train_vae:build_user_history_dataset:154 - Каталог айтемов: 20000 штук
2026-05-09 23:39:17.856 | INFO     | src.modeling.train_vae:build_user_history_dataset:214 - Сохранение sparse user-history в C:\Users\Sasha\AppData\Local\Temp\vae_history_gy5h91dg\history.pq (streaming sink)...
2026-05-09 23:39:18.389 | INFO     | src.modeling.train_vae:build_user_history_dataset:223 - Активных пользователей: 184239
Снимок дня 1305: 184,239 активных users x 20,000 items
2026-05-09 23:39:18.693 | INFO     | src.modeling.vae:build_model:403 - MultiVAE собрана: num_items=20000, dims=[600, 200], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-05-09 23:39:19.194 | INFO     | src.modeling.train_vae:train_vae:424 - Стартую обучение: 184239 пользователей, 20000 items, batches per epoch ≈ 720

Сборка user_items: 100%|██████████| 184239/184239 [00:05<00:00, 32127.84user/s]
Эпохи:   3%|▎         | 1/30 [00:17<08:34, 17.74s/epoch, beta=0.001, kld=295.267, loss=164.633, lr=9.97e-04, nll=164.499]

2026-05-09 23:39:49.342 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 01: loss=164.6326 nll=164.4987 kld=295.2670 beta=0.0007 lr=9.97e-04 time=17.7s

Эпохи:   7%|▋         | 2/30 [00:35<08:10, 17.51s/epoch, beta=0.001, kld=394.871, loss=143.773, lr=9.89e-04, nll=143.350]

2026-05-09 23:40:06.689 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 02: loss=143.7730 nll=143.3502 kld=394.8713 beta=0.0014 lr=9.89e-04 time=17.3s

Эпохи:  10%|█         | 3/30 [00:52<07:53, 17.53s/epoch, beta=0.002, kld=350.537, loss=138.812, lr=9.76e-04, nll=138.183]

2026-05-09 23:40:24.240 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 03: loss=138.8118 nll=138.1828 kld=350.5367 beta=0.0022 lr=9.76e-04 time=17.5s

Эпохи:  13%|█▎        | 4/30 [01:10<07:34, 17.48s/epoch, beta=0.003, kld=326.428, loss=136.245, lr=9.57e-04, nll=135.423]

2026-05-09 23:40:41.640 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 04: loss=136.2447 nll=135.4233 kld=326.4275 beta=0.0029 lr=9.57e-04 time=17.4s

Эпохи:  17%|█▋        | 5/30 [01:27<07:19, 17.58s/epoch, beta=0.004, kld=308.598, loss=134.591, lr=9.34e-04, nll=133.592]

2026-05-09 23:40:59.404 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 05: loss=134.5911 nll=133.5921 kld=308.5977 beta=0.0036 lr=9.34e-04 time=17.8s

Эпохи:  20%|██        | 6/30 [01:45<07:00, 17.51s/epoch, beta=0.004, kld=293.725, loss=133.397, lr=9.05e-04, nll=132.234]

2026-05-09 23:41:16.767 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 06: loss=133.3969 nll=132.2345 kld=293.7251 beta=0.0043 lr=9.05e-04 time=17.4s

Эпохи:  23%|██▎       | 7/30 [02:02<06:42, 17.49s/epoch, beta=0.005, kld=280.832, loss=132.432, lr=8.73e-04, nll=131.119]

2026-05-09 23:41:34.216 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 07: loss=132.4324 nll=131.1187 kld=280.8321 beta=0.0050 lr=8.73e-04 time=17.4s

Эпохи:  27%|██▋       | 8/30 [02:20<06:25, 17.52s/epoch, beta=0.006, kld=270.032, loss=131.752, lr=8.36e-04, nll=130.294]

2026-05-09 23:41:51.796 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 08: loss=131.7517 nll=130.2941 kld=270.0322 beta=0.0058 lr=8.36e-04 time=17.6s

Эпохи:  30%|███       | 9/30 [02:37<06:06, 17.47s/epoch, beta=0.006, kld=260.116, loss=131.148, lr=7.96e-04, nll=129.556]

2026-05-09 23:42:09.174 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 09: loss=131.1476 nll=129.5561 kld=260.1159 beta=0.0065 lr=7.96e-04 time=17.4s

Эпохи:  33%|███▎      | 10/30 [02:55<05:52, 17.62s/epoch, beta=0.007, kld=250.992, loss=130.555, lr=7.52e-04, nll=128.838]

2026-05-09 23:42:27.125 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 10: loss=130.5546 nll=128.8383 kld=250.9920 beta=0.0072 lr=7.52e-04 time=17.9s

Эпохи:  37%|███▋      | 11/30 [03:22<06:29, 20.49s/epoch, beta=0.008, kld=242.936, loss=130.060, lr=7.06e-04, nll=128.224]

2026-05-09 23:42:54.117 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 11: loss=130.0602 nll=128.2241 kld=242.9364 beta=0.0079 lr=7.06e-04 time=27.0s

Эпохи:  40%|████      | 12/30 [03:43<06:09, 20.51s/epoch, beta=0.009, kld=235.128, loss=129.659, lr=6.58e-04, nll=127.713]

2026-05-09 23:43:14.668 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 12: loss=129.6592 nll=127.7127 kld=235.1284 beta=0.0086 lr=6.58e-04 time=20.5s

Эпохи:  43%|████▎     | 13/30 [04:00<05:32, 19.53s/epoch, beta=0.009, kld=228.969, loss=129.252, lr=6.08e-04, nll=127.192]

2026-05-09 23:43:31.951 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 13: loss=129.2520 nll=127.1916 kld=228.9687 beta=0.0094 lr=6.08e-04 time=17.3s

Эпохи:  47%|████▋     | 14/30 [04:26<05:44, 21.51s/epoch, beta=0.010, kld=222.801, loss=128.875, lr=5.57e-04, nll=126.710]

2026-05-09 23:43:58.028 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 14: loss=128.8750 nll=126.7097 kld=222.8007 beta=0.0101 lr=5.57e-04 time=26.1s

Эпохи:  50%|█████     | 15/30 [04:54<05:50, 23.38s/epoch, beta=0.011, kld=216.958, loss=128.569, lr=5.05e-04, nll=126.304]

2026-05-09 23:44:25.740 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 15: loss=128.5691 nll=126.3044 kld=216.9578 beta=0.0108 lr=5.05e-04 time=27.7s

Эпохи:  53%|█████▎    | 16/30 [05:21<05:44, 24.62s/epoch, beta=0.012, kld=211.817, loss=128.260, lr=4.53e-04, nll=125.897]

2026-05-09 23:44:53.244 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 16: loss=128.2603 nll=125.8967 kld=211.8168 beta=0.0115 lr=4.53e-04 time=27.5s

Эпохи:  57%|█████▋    | 17/30 [05:44<05:15, 24.24s/epoch, beta=0.012, kld=206.824, loss=127.984, lr=4.02e-04, nll=125.527]

2026-05-09 23:45:16.596 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 17: loss=127.9838 nll=125.5271 kld=206.8242 beta=0.0122 lr=4.02e-04 time=23.3s

Эпохи:  60%|██████    | 18/30 [06:02<04:26, 22.23s/epoch, beta=0.013, kld=202.096, loss=127.753, lr=3.52e-04, nll=125.207]

2026-05-09 23:45:34.137 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 18: loss=127.7530 nll=125.2069 kld=202.0956 beta=0.0130 lr=3.52e-04 time=17.5s

Эпохи:  63%|██████▎   | 19/30 [06:29<04:20, 23.72s/epoch, beta=0.014, kld=198.118, loss=127.571, lr=3.04e-04, nll=124.932]

2026-05-09 23:46:01.334 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 19: loss=127.5713 nll=124.9325 kld=198.1177 beta=0.0137 lr=3.04e-04 time=27.2s

Эпохи:  67%|██████▋   | 20/30 [06:56<04:07, 24.71s/epoch, beta=0.014, kld=194.110, loss=127.400, lr=2.57e-04, nll=124.675]

2026-05-09 23:46:28.351 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 20: loss=127.3999 nll=124.6746 kld=194.1103 beta=0.0144 lr=2.57e-04 time=27.0s

Эпохи:  70%|███████   | 21/30 [07:18<03:34, 23.88s/epoch, beta=0.015, kld=190.362, loss=127.213, lr=2.14e-04, nll=124.403]

2026-05-09 23:46:50.311 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 21: loss=127.2127 nll=124.4031 kld=190.3617 beta=0.0151 lr=2.14e-04 time=22.0s

Эпохи:  73%|███████▎  | 22/30 [07:46<03:19, 24.97s/epoch, beta=0.016, kld=187.069, loss=127.119, lr=1.74e-04, nll=124.223]

2026-05-09 23:47:17.825 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 22: loss=127.1189 nll=124.2232 kld=187.0686 beta=0.0158 lr=1.74e-04 time=27.5s

Эпохи:  77%|███████▋  | 23/30 [08:14<03:00, 25.85s/epoch, beta=0.017, kld=183.379, loss=127.053, lr=1.37e-04, nll=124.082]

2026-05-09 23:47:45.720 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 23: loss=127.0526 nll=124.0820 kld=183.3791 beta=0.0166 lr=1.37e-04 time=27.9s

Эпохи:  80%|████████  | 24/30 [08:42<02:38, 26.49s/epoch, beta=0.017, kld=180.304, loss=127.001, lr=1.05e-04, nll=123.951]

2026-05-09 23:48:13.715 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 24: loss=127.0014 nll=123.9508 kld=180.3040 beta=0.0173 lr=1.05e-04 time=28.0s

Эпохи:  83%|████████▎ | 25/30 [09:10<02:14, 26.98s/epoch, beta=0.018, kld=177.391, loss=126.944, lr=7.63e-05, nll=123.815]

2026-05-09 23:48:41.820 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 25: loss=126.9441 nll=123.8150 kld=177.3913 beta=0.0180 lr=7.63e-05 time=28.1s

Эпохи:  87%|████████▋ | 26/30 [09:37<01:48, 27.05s/epoch, beta=0.019, kld=174.694, loss=126.971, lr=5.28e-05, nll=123.763]

2026-05-09 23:49:09.033 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 26: loss=126.9707 nll=123.7633 kld=174.6940 beta=0.0187 lr=5.28e-05 time=27.2s

Эпохи:  90%|█████████ | 27/30 [10:05<01:21, 27.29s/epoch, beta=0.019, kld=172.300, loss=126.990, lr=3.42e-05, nll=123.702]

2026-05-09 23:49:36.890 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 27: loss=126.9896 nll=123.7022 kld=172.2998 beta=0.0194 lr=3.42e-05 time=27.9s

Эпохи:  93%|█████████▎| 28/30 [10:33<00:55, 27.57s/epoch, beta=0.020, kld=170.116, loss=127.082, lr=2.08e-05, nll=123.714]

2026-05-09 23:50:05.097 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 28: loss=127.0821 nll=123.7139 kld=170.1155 beta=0.0202 lr=2.08e-05 time=28.2s

Эпохи:  97%|█████████▋| 29/30 [11:01<00:27, 27.72s/epoch, beta=0.021, kld=167.921, loss=127.134, lr=1.27e-05, nll=123.688]

2026-05-09 23:50:33.170 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 29: loss=127.1342 nll=123.6885 kld=167.9211 beta=0.0209 lr=1.27e-05 time=28.1s

Эпохи: 100%|██████████| 30/30 [11:29<00:00, 22.99s/epoch, beta=0.022, kld=166.140, loss=127.241, lr=1.00e-05, nll=123.712]

2026-05-09 23:51:01.359 | INFO     | src.modeling.train_vae:train_vae:527 - Epoch 30: loss=127.2409 nll=123.7121 kld=166.1397 beta=0.0216 lr=1.00e-05 time=28.2s
2026-05-09 23:51:01.599 | INFO     | src.modeling.vae:save:497 - MultiVAE сохранена в D:\HSE_repos\dreamteam-recsys\models\vae_artifacts\model.pt
2026-05-09 23:51:03.798 | INFO     | src.modeling.train_vae:train_vae:549 - user_items.npz сохранена в D:\HSE_repos\dreamteam-recsys\models\vae_artifacts
Чекпоинт сохранён: D:\HSE_repos\dreamteam-recsys\models\vae_artifacts\model.pt

## Гипероптимизация (Optuna)

Для сокращения затрат на ресурсы:
1. Берем **40% пользователей** случайной выборкой.
2. На подмножестве пользователей запускаем гипероптимизацию, целевая метрика — **NDCG@15**.
3. Лучшую конфигурацию переобучаем на полном датасете.

In [5]:
import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

SUBSET_FRACTION = 0.4
OPTUNA_TRIALS = 20
TOP_K = 15
RANDOM_SEED = 42

all_user_ids = (
    events_df.select("user_id").unique().collect(engine="streaming")["user_id"].to_list()
)
rng = np.random.default_rng(RANDOM_SEED)
subset_users = set(
    rng.choice(all_user_ids, size=int(len(all_user_ids) * SUBSET_FRACTION), replace=False).tolist()
)
print(f"Всего пользователей: {len(all_user_ids):,}")
print(f"Пользователей в подмножестве ({SUBSET_FRACTION*100:.0f}%): {len(subset_users):,}")

events_sub = events_df.filter(pl.col("user_id").is_in(subset_users))
train_sub, test_sub = dts.global_temporal_split(events_sub, 0.2)
print("Подмножество готово")

Всего пользователей: 1,616,763
Пользователей в подмножестве (40%): 646,705
Подмножество готово

In [6]:
events_df.head().collect()

shape: (5, 11)
┌────────────┬──────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ timestamp  ┆ user_id  ┆ item_id   ┆ subdomain ┆ … ┆ path      ┆ target   ┆ log_targe ┆ sqrt_targ │
│ ---        ┆ ---      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---      ┆ t         ┆ et        │
│ duration[μ ┆ u64      ┆ str       ┆ str       ┆   ┆ str       ┆ f64      ┆ ---       ┆ ---       │
│ s]         ┆          ┆           ┆           ┆   ┆           ┆          ┆ f64       ┆ f64       │
╞════════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 1082d      ┆ 59328774 ┆ nfmcg_147 ┆ u2i       ┆ … ┆ ..\data\r ┆ 1.034082 ┆ 0.710044  ┆ 1.016898  │
│ 89901µs    ┆          ┆ 77696     ┆           ┆   ┆ aw\datase ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ t\small\m ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ ark…      ┆          ┆           ┆           │
│ 1082d      ┆ 66295302 ┆ nfmcg_260 ┆ catalog   ┆ … ┆ ..\data\r ┆ 1.034082 ┆ 0.710044  ┆ 1.016898  │
│ 163483µs   ┆          ┆ 98539     ┆           ┆   ┆ aw\datase ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ t\small\m ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ ark…      ┆          ┆           ┆           │
│ 1082d      ┆ 37542104 ┆ nfmcg_108 ┆ u2i       ┆ … ┆ ..\data\r ┆ 1.034082 ┆ 0.710044  ┆ 1.016898  │
│ 864625µs   ┆          ┆ 40247     ┆           ┆   ┆ aw\datase ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ t\small\m ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ ark…      ┆          ┆           ┆           │
│ 1082d      ┆ 35193548 ┆ nfmcg_804 ┆ catalog   ┆ … ┆ ..\data\r ┆ 1.034082 ┆ 0.710044  ┆ 1.016898  │
│ 889192µs   ┆          ┆ 0572      ┆           ┆   ┆ aw\datase ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ t\small\m ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ ark…      ┆          ┆           ┆           │
│ 1082d      ┆ 27256137 ┆ nfmcg_677 ┆ catalog   ┆ … ┆ ..\data\r ┆ 1.034082 ┆ 0.710044  ┆ 1.016898  │
│ 936008µs   ┆          ┆ 0239      ┆           ┆   ┆ aw\datase ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ t\small\m ┆          ┆           ┆           │
│            ┆          ┆           ┆           ┆   ┆ ark…      ┆          ┆           ┆           │
└────────────┴──────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [6]:
ITEMS_TO_TAKE = 20_000

all_items_ids = (
    train_sub.group_by("item_id").agg(count=pl.len()).sort("count", descending=True).head(ITEMS_TO_TAKE).collect(engine="streaming")["item_id"].to_list()
)

In [7]:
train_sub = train_sub.filter(pl.col("item_id").is_in(all_items_ids))

Берем подмножество товаров для обучения:

In [8]:
def build_history_from_events(
    train_lf: pl.LazyFrame,
    target_col: str,
    output_path: Path,
    binary: bool = True,
    min_interactions: int = 3,
    min_day: int | None = None,
) -> tuple[dict[str, int], dict[int, int]]:
    """Строит sparse user-history parquet из LazyFrame событий.

    Выходная схема: (user_idx: u32, user_id: u64, item_idx: list[u32], weight: list[f32]).
    train_lf должен уже быть отфильтрован по нужным item_id.

    Parameters
    ----------
    min_day : int or None
        Если задан, используются только события с ``day >= min_day``.
        Позволяет ограничить историю конкретным временным окном,
        аналогично снимку ``build_user_history_dataset(day=DAY)``.
    """
    if min_day is not None:
        train_lf = train_lf.filter(pl.col("day") >= min_day)

    df = (
        train_lf
        .select("user_id", "item_id", target_col)
        .collect(engine="streaming")
        .group_by("user_id", "item_id")
        .agg(pl.col(target_col).sum())
    )

    valid_users = (
        df.group_by("user_id").agg(pl.len().alias("cnt"))
        .filter(pl.col("cnt") >= min_interactions).select("user_id")
    )
    valid_items = (
        df.group_by("item_id").agg(pl.len().alias("cnt"))
        .filter(pl.col("cnt") >= min_interactions).select("item_id")
    )
    df = df.join(valid_users, on="user_id").join(valid_items, on="item_id")

    item_ids_sorted = df.select("item_id").unique().sort("item_id")["item_id"].to_list()
    item_to_idx: dict[str, int] = {iid: idx for idx, iid in enumerate(item_ids_sorted)}
    items_meta = pl.DataFrame(
        {"item_id": item_ids_sorted, "item_idx": list(range(len(item_ids_sorted)))},
        schema={"item_id": pl.String, "item_idx": pl.UInt32},
    )

    if binary:
        df = df.with_columns(weight=pl.lit(1.0, dtype=pl.Float32))
    else:
        df = df.with_columns(weight=pl.col(target_col).cast(pl.Float32))

    df = df.join(items_meta, on="item_id")

    user_df = (
        df.group_by("user_id")
        .agg(pl.col("item_idx"), pl.col("weight"))
        .sort("user_id")
        .with_row_index("user_idx")
        .with_columns(pl.col("user_idx").cast(pl.UInt32))
    )
    user_to_idx: dict[int, int] = dict(
        zip(user_df["user_id"].to_list(), user_df["user_idx"].to_list())
    )

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    user_df.select("user_idx", "user_id", "item_idx", "weight").write_parquet(output_path)
    return item_to_idx, user_to_idx


def evaluate_ndcg(
    rec: MultiVAERecommender,
    test_lf: pl.LazyFrame,
    target_col: str,
    top_k: int = 15,
) -> dict:
    """Считает NDCG/Precision/Recall на тестовой выборке."""
    test_df = test_lf.select("user_id", "item_id", target_col).collect(engine="streaming")
    known_users = set(rec.user_to_idx.keys())
    test_filtered = test_df.filter(pl.col("user_id").is_in(known_users))

    user_test_truth = test_filtered.group_by("user_id").agg(
        pl.col("item_id").alias("true_items"),
        pl.col(target_col).alias("relevancy"),
    )
    test_user_ids = user_test_truth["user_id"].to_numpy()
    test_user_idxs = np.array([rec.user_to_idx[uid] for uid in test_user_ids])

    BATCH = 1024
    item_idx_chunks, score_chunks = [], []
    for start in range(0, len(test_user_idxs), BATCH):
        chunk = test_user_idxs[start : start + BATCH]
        ids, scores = rec.recommend_batch(chunk, top_k=top_k)
        item_idx_chunks.append(ids)
        score_chunks.append(scores)

    item_idx_matrix = np.concatenate(item_idx_chunks, axis=0)
    score_matrix    = np.concatenate(score_chunks,    axis=0)

    predicted_items_list  = [[rec.idx_to_item[i] for i in row] for row in item_idx_matrix]
    predicted_scores_list = [row.tolist() for row in score_matrix]

    prediction_df  = pl.DataFrame({
        "user_id":          test_user_ids,
        "predicted_items":  predicted_items_list,
        "predicted_scores": predicted_scores_list,
    })
    evaluation_df = user_test_truth.join(prediction_df, on="user_id")

    ndcg_results = ndcg_at_k(
        evaluation_df,
        relevancy_col="relevancy",
        true_items_col="true_items",
        predicted_items_col="predicted_items",
        predicted_score_col="predicted_scores",
        top_k=top_k,
    )
    mean_ndcg = float(ndcg_results["ndcg"].mean())
    precision, recall = precision_recall_at_k(
        evaluation_df,
        predicted_items_col="predicted_items",
        true_items_col="true_items",
        top_k=top_k,
    )
    return {"ndcg": mean_ndcg, "precision": precision, "recall": recall}

In [9]:
DAY                = 1276          # снимок 30-дневного окна [1276, 1305]
EPOCHS             = 30
BATCH_SIZE         = 256
ENCODER_DIMS       = [600, 200]
DROPOUT            = 0.5
BETA               = 0.2
TOTAL_ANNEAL_STEPS = 200_000
KL_SCHEDULE        = "linear"
LR                 = 1e-3
WEIGHT_DECAY       = 0.0
BINARY             = True
MIN_USER_ITEMS     = 5
SEED               = 42

In [15]:


def optuna_objective(trial: optuna.Trial) -> float:
    target_col = trial.suggest_categorical("target_col", ["log_target", "sqrt_target"])
    latent_dim = trial.suggest_categorical("latent_dim", [64, 128, 200, 256])
    hidden_dim = trial.suggest_categorical("hidden_dim", [400, 600, 800])
    dropout    = trial.suggest_float("dropout", 0.2, 0.7, step=0.1)
    beta       = trial.suggest_float("beta", 0.05, 0.5, log=True)
    epochs     = trial.suggest_int("epochs", 10, 40, step=5)
    binary     = trial.suggest_categorical("binary", [True, False])
    batch_size = trial.suggest_int("batch_size", 32, 512, step=16)

    tmp_dir = Path(tempfile.mkdtemp(prefix="vae_optuna_"))
    try:
        history_path  = tmp_dir / "history.pq"
        artifacts_dir = tmp_dir / "artifacts"

        # Шаг 1 — OOM-совместимый history parquet из train_sub
        # DAY — конец 30-дневного окна [DAY-29, DAY], как в снимке OOM baseline
        item_to_idx, user_to_idx = build_history_from_events(
            train_sub,
            target_col=target_col,
            output_path=history_path,
            binary=binary,
            min_interactions=3,
            min_day=DAY - 29,
        )

        # Шаг 2 — OOM-обучение (HuggingFace Arrow, dense батч только на шаге)
        train_vae(
            history_path=history_path,
            item_to_idx=item_to_idx,
            user_to_idx=user_to_idx,
            artifacts_dir=artifacts_dir,
            encoder_dims=[hidden_dim, latent_dim],
            dropout=dropout,
            beta=beta,
            epochs=epochs,
            batch_size=batch_size,
            total_anneal_steps=100_000,
            use_lr_scheduler=True,
            num_workers=4,
            seed=RANDOM_SEED,
        )

        # Шаг 3 — загрузка и оценка на test_sub
        rec = MultiVAERecommender()
        rec.load(artifacts_dir / "model.pt")
        rec.set_user_items(load_npz(artifacts_dir / "user_items.npz"))

        metrics = evaluate_ndcg(rec, test_sub, target_col=target_col, top_k=TOP_K)
        ndcg = metrics["ndcg"]
        trial.set_user_attr("precision", metrics["precision"])
        trial.set_user_attr("recall",    metrics["recall"])
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)

    print(
        f"  Trial {trial.number}: target={target_col}, dims=[{hidden_dim},{latent_dim}], "
        f"dropout={dropout:.1f}, beta={beta:.3f}, epochs={epochs}, binary={binary} "
        f"→ NDCG@{TOP_K}={ndcg:.6f}"
    )
    return ndcg


sampler = optuna.samplers.TPESampler(seed=RANDOM_SEED)
study = optuna.create_study(direction="maximize", sampler=sampler)

print(f"Запуск Optuna: {OPTUNA_TRIALS} trials на {SUBSET_FRACTION*100:.0f}% датасета...")
study.optimize(optuna_objective, n_trials=OPTUNA_TRIALS, show_progress_bar=False)

best = study.best_trial
print(f"\nЛучший trial #{best.number}:")
print(f"  NDCG@{TOP_K} = {best.value:.6f}")
for k, v in best.params.items():
    print(f"  {k} = {v}")

Эпохи:  74%|███████▍  | 26/35 [04:08<01:22,  9.21s/epoch, beta=0.030, kld=77.165, loss=72.108, lr=1.63e-04, nll=69.874]

2026-06-02 00:39:15.454 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 26: loss=72.1084 nll=69.8745 kld=77.1654 beta=0.0295 lr=1.63e-04 time=9.9s

Эпохи:  77%|███████▋  | 27/35 [04:17<01:13,  9.13s/epoch, beta=0.031, kld=75.589, loss=72.043, lr=1.32e-04, nll=69.769]

2026-06-02 00:39:24.403 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 27: loss=72.0431 nll=69.7690 kld=75.5891 beta=0.0307 lr=1.32e-04 time=8.9s

Эпохи:  80%|████████  | 28/35 [04:26<01:02,  8.94s/epoch, beta=0.032, kld=74.650, loss=72.061, lr=1.05e-04, nll=69.730]

2026-06-02 00:39:32.879 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 28: loss=72.0608 nll=69.7303 kld=74.6497 beta=0.0318 lr=1.05e-04 time=8.5s

Эпохи:  83%|████████▎ | 29/35 [04:36<00:55,  9.32s/epoch, beta=0.033, kld=73.219, loss=72.063, lr=8.01e-05, nll=69.694]

2026-06-02 00:39:43.112 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 29: loss=72.0626 nll=69.6937 kld=73.2185 beta=0.0329 lr=8.01e-05 time=10.2s

Эпохи:  86%|████████▌ | 30/35 [04:46<00:47,  9.55s/epoch, beta=0.034, kld=71.988, loss=72.082, lr=5.90e-05, nll=69.671]

2026-06-02 00:39:53.193 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 30: loss=72.0823 nll=69.6713 kld=71.9882 beta=0.0341 lr=5.90e-05 time=10.1s

Эпохи:  89%|████████▊ | 31/35 [04:57<00:39,  9.92s/epoch, beta=0.035, kld=71.121, loss=72.073, lr=4.16e-05, nll=69.611]

2026-06-02 00:40:03.969 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 31: loss=72.0734 nll=69.6106 kld=71.1212 beta=0.0352 lr=4.16e-05 time=10.8s

Эпохи:  91%|█████████▏| 32/35 [05:08<00:30, 10.33s/epoch, beta=0.036, kld=70.137, loss=72.134, lr=2.78e-05, nll=69.626]

2026-06-02 00:40:15.261 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 32: loss=72.1342 nll=69.6260 kld=70.1367 beta=0.0363 lr=2.78e-05 time=11.3s

Эпохи:  94%|█████████▍| 33/35 [05:18<00:20, 10.35s/epoch, beta=0.037, kld=69.597, loss=72.285, lr=1.80e-05, nll=69.717]

2026-06-02 00:40:25.653 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 33: loss=72.2851 nll=69.7171 kld=69.5966 beta=0.0375 lr=1.80e-05 time=10.4s

Эпохи:  97%|█████████▋| 34/35 [05:29<00:10, 10.47s/epoch, beta=0.039, kld=68.544, loss=72.302, lr=1.20e-05, nll=69.695]

2026-06-02 00:40:36.416 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 34: loss=72.3017 nll=69.6947 kld=68.5438 beta=0.0386 lr=1.20e-05 time=10.8s

Эпохи: 100%|██████████| 35/35 [05:39<00:00,  9.70s/epoch, beta=0.040, kld=67.874, loss=72.275, lr=1.00e-05, nll=69.616]

2026-06-02 00:40:46.517 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 35: loss=72.2747 nll=69.6162 kld=67.8742 beta=0.0397 lr=1.00e-05 time=10.1s
2026-06-02 00:40:46.636 | INFO     | src.modeling.vae:save:477 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_lnzugpnf\artifacts\model.pt
2026-06-02 00:40:47.930 | INFO     | src.modeling.train_vae:train_vae:490 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_optuna_lnzugpnf\artifacts
2026-06-02 00:40:48.337 | INFO     | src.modeling.vae:build_model:385 - MultiVAE собрана: num_items=11191, dims=[800, 128], device=cuda
2026-06-02 00:40:48.352 | INFO     | src.modeling.vae:load:497 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_optuna_lnzugpnf\artifacts\model.pt
  Trial 19: target=log_target, dims=[800,128], dropout=0.6, beta=0.300, epochs=35, binary=False → NDCG@15=0.054553

Лучший trial #11:
  NDCG@15 = 0.056392
  target_col = log_target
  latent_dim = 64
  hidden_dim = 800
  dropout = 0.7
  beta = 0.21496961476692295
  epochs = 25
  binary = False
  batch_size = 368

In [16]:
best = study.best_trial
print(f"\nЛучший trial #{best.number}:")
print(f"  NDCG@{TOP_K} = {best.value:.6f}")
for k, v in best.params.items():
    print(f"  {k} = {v}")

Лучший trial #11:
  NDCG@15 = 0.056392
  target_col = log_target
  latent_dim = 64
  hidden_dim = 800
  dropout = 0.7
  beta = 0.21496961476692295
  epochs = 25
  binary = False
  batch_size = 368

In [17]:
best_params = {
    "target_col": "log_target",
    "latent_dim": 64,
    "hidden_dim": 800,
    "dropout": 0.7,
    "beta": 0.215,
    "epochs": 25,
    "binary": False,
    "batch_size": 360
}

In [18]:
trials_df = pl.DataFrame([
    {
        "trial":      t.number,
        "ndcg":       t.value,
        "precision":  t.user_attrs.get("precision"),
        "recall":     t.user_attrs.get("recall"),
        "target_col": t.params["target_col"],
        "latent_dim": t.params["latent_dim"],
        "hidden_dim": t.params["hidden_dim"],
        "dropout":    t.params["dropout"],
        "beta":       t.params["beta"],
        "epochs":     t.params["epochs"],
        "binary":     t.params["binary"],
        "batch_size": t.params["batch_size"]
    }
    for t in study.trials
    if t.state == optuna.trial.TrialState.COMPLETE
]).sort("ndcg", descending=True)

trials_df

shape: (20, 12)
┌───────┬──────────┬───────────┬──────────┬───┬──────────┬────────┬────────┬────────────┐
│ trial ┆ ndcg     ┆ precision ┆ recall   ┆ … ┆ beta     ┆ epochs ┆ binary ┆ batch_size │
│ ---   ┆ ---      ┆ ---       ┆ ---      ┆   ┆ ---      ┆ ---    ┆ ---    ┆ ---        │
│ i64   ┆ f64      ┆ f64       ┆ f64      ┆   ┆ f64      ┆ i64    ┆ bool   ┆ i64        │
╞═══════╪══════════╪═══════════╪══════════╪═══╪══════════╪════════╪════════╪════════════╡
│ 11    ┆ 0.056392 ┆ 0.056397  ┆ 0.040653 ┆ … ┆ 0.21497  ┆ 25     ┆ false  ┆ 368        │
│ 17    ┆ 0.056293 ┆ 0.05574   ┆ 0.040252 ┆ … ┆ 0.263582 ┆ 30     ┆ false  ┆ 320        │
│ 16    ┆ 0.056237 ┆ 0.056119  ┆ 0.040737 ┆ … ┆ 0.234161 ┆ 25     ┆ false  ┆ 336        │
│ 12    ┆ 0.05612  ┆ 0.056009  ┆ 0.040568 ┆ … ┆ 0.203785 ┆ 20     ┆ false  ┆ 384        │
│ 14    ┆ 0.056108 ┆ 0.055724  ┆ 0.040211 ┆ … ┆ 0.158112 ┆ 20     ┆ false  ┆ 432        │
│ …     ┆ …        ┆ …         ┆ …        ┆ … ┆ …        ┆ …      ┆ …      ┆ …          │
│ 0     ┆ 0.053201 ┆ 0.052885  ┆ 0.037599 ┆ … ┆ 0.052427 ┆ 40     ┆ true   ┆ 112        │
│ 1     ┆ 0.052959 ┆ 0.052074  ┆ 0.037457 ┆ … ┆ 0.304892 ┆ 15     ┆ false  ┆ 48         │
│ 9     ┆ 0.052285 ┆ 0.050989  ┆ 0.03664  ┆ … ┆ 0.054432 ┆ 30     ┆ true   ┆ 160        │
│ 6     ┆ 0.051478 ┆ 0.051618  ┆ 0.037068 ┆ … ┆ 0.053753 ┆ 30     ┆ false  ┆ 480        │
│ 5     ┆ 0.051407 ┆ 0.051314  ┆ 0.037136 ┆ … ┆ 0.105719 ┆ 35     ┆ false  ┆ 256        │
└───────┴──────────┴───────────┴──────────┴───┴──────────┴────────┴────────┴────────────┘

## Финальная оценка лучшего Mult-VAE на полном датасете

Переобучаем модель с найденными гиперпараметрами на **полном** train/test split — для прямого сравнения с iALS и SVD.

In [19]:
# best_params = best.params
print("Лучшие гиперпараметры (из hyperopt на subset):")
for k, v in best_params.items():
    print(f"  {k}: {v}")

# Фильтруем train по тем же 40k item-ам и тому же 30-дневному окну [DAY-29, DAY],
# что и в Optuna — чтобы финальная модель была сравнима с гиперопт-триалами
train_full = train.filter(pl.col("item_id").is_in(all_items_ids))

print("\nОбучение на полном датасете (OOM)...")
_tmp_dir = Path(tempfile.mkdtemp(prefix="vae_final_"))
try:
    _history_path  = _tmp_dir / "history.pq"
    _artifacts_dir = _tmp_dir / "artifacts"

    _item_to_idx, _user_to_idx = build_history_from_events(
        train_full,
        target_col=best_params["target_col"],
        output_path=_history_path,
        binary=best_params["binary"],
        min_interactions=5,
        min_day=DAY - 29,
    )
    print(f"  {len(_user_to_idx):,} пользователей x {len(_item_to_idx):,} items")

    train_vae(
        history_path=_history_path,
        item_to_idx=_item_to_idx,
        user_to_idx=_user_to_idx,
        artifacts_dir=_artifacts_dir,
        encoder_dims=[best_params["hidden_dim"], best_params["latent_dim"]],
        dropout=best_params["dropout"],
        beta=best_params["beta"],
        epochs=best_params["epochs"],
        batch_size=best_params["batch_size"],
        total_anneal_steps=200_000,
        use_lr_scheduler=True,
        num_workers=4,
        seed=SEED,
    )

    _rec = MultiVAERecommender()
    _rec.load(_artifacts_dir / "model.pt")
    _rec.set_user_items(load_npz(_artifacts_dir / "user_items.npz"))

    _metrics = evaluate_ndcg(_rec, test, target_col=best_params["target_col"], top_k=TOP_K)
finally:
    shutil.rmtree(_tmp_dir, ignore_errors=True)

best_vae_result = {
    "target":       best_params["target_col"],
    "encoder_dims": [best_params["hidden_dim"], best_params["latent_dim"]],
    "dropout":      best_params["dropout"],
    "beta":         best_params["beta"],
    "epochs":       best_params["epochs"],
    "top_k":        TOP_K,
    "ndcg":         _metrics["ndcg"],
    "precision":    _metrics["precision"],
    "recall":       _metrics["recall"],
    "rmse":         None,
    "mae":          None,
}

print("\nРезультат лучшего Mult-VAE (full data):")
for metric in ("ndcg", "precision", "recall"):
    print(f"  {metric}: {best_vae_result[metric]:.6f}")

Лучшие гиперпараметры (из hyperopt на subset):
  target_col: log_target
  latent_dim: 64
  hidden_dim: 800
  dropout: 0.7
  beta: 0.215
  epochs: 25
  binary: False
  batch_size: 360

Обучение на полном датасете (OOM)...
  350,575 пользователей x 11,894 items
2026-06-02 00:49:22.067 | INFO     | src.modeling.vae:build_model:385 - MultiVAE собрана: num_items=11894, dims=[800, 64], device=cuda

Generating train split: 0 examples [00:00, ? examples/s]

2026-06-02 00:49:22.211 | INFO     | src.modeling.train_vae:train_vae:370 - Стартую обучение: 350575 пользователей, 11894 items, batches per epoch ≈ 974

Сборка user_items: 100%|██████████| 350575/350575 [00:13<00:00, 26725.19user/s]
Эпохи:   4%|▍         | 1/25 [00:20<08:23, 20.97s/epoch, beta=0.001, kld=166.952, loss=102.089, lr=9.96e-04, nll=101.987]

2026-06-02 00:49:57.276 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 01: loss=102.0886 nll=101.9866 kld=166.9518 beta=0.0010 lr=9.96e-04 time=21.0s

Эпохи:   8%|▊         | 2/25 [00:46<08:59, 23.44s/epoch, beta=0.002, kld=181.902, loss=92.440, lr=9.84e-04, nll=92.157]

2026-06-02 00:50:22.441 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 02: loss=92.4403 nll=92.1574 kld=181.9016 beta=0.0021 lr=9.84e-04 time=25.2s

Эпохи:  12%|█▏        | 3/25 [01:05<07:55, 21.60s/epoch, beta=0.003, kld=158.992, loss=90.726, lr=9.65e-04, nll=90.311]

2026-06-02 00:50:41.845 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 03: loss=90.7259 nll=90.3113 kld=158.9917 beta=0.0031 lr=9.65e-04 time=19.4s

Эпохи:  16%|█▌        | 4/25 [01:25<07:16, 20.80s/epoch, beta=0.004, kld=146.560, loss=89.850, lr=9.39e-04, nll=89.314]

2026-06-02 00:51:01.433 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 04: loss=89.8498 nll=89.3135 kld=146.5595 beta=0.0042 lr=9.39e-04 time=19.6s

Эпохи:  20%|██        | 5/25 [01:44<06:47, 20.38s/epoch, beta=0.005, kld=138.574, loss=89.328, lr=9.05e-04, nll=88.675]

2026-06-02 00:51:21.052 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 05: loss=89.3276 nll=88.6752 kld=138.5741 beta=0.0052 lr=9.05e-04 time=19.6s

Эпохи:  24%|██▍       | 6/25 [02:04<06:20, 20.02s/epoch, beta=0.006, kld=131.407, loss=88.959, lr=8.66e-04, nll=88.203]

2026-06-02 00:51:40.374 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 06: loss=88.9593 nll=88.2030 kld=131.4072 beta=0.0063 lr=8.66e-04 time=19.3s

Эпохи:  28%|██▊       | 7/25 [02:24<06:00, 20.02s/epoch, beta=0.007, kld=126.001, loss=88.599, lr=8.21e-04, nll=87.742]

2026-06-02 00:52:00.406 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 07: loss=88.5988 nll=87.7417 kld=126.0010 beta=0.0073 lr=8.21e-04 time=20.0s

Эпохи:  32%|███▏      | 8/25 [02:39<05:17, 18.66s/epoch, beta=0.008, kld=121.235, loss=88.403, lr=7.70e-04, nll=87.451]

2026-06-02 00:52:16.139 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 08: loss=88.4031 nll=87.4514 kld=121.2353 beta=0.0084 lr=7.70e-04 time=15.7s

Эпохи:  36%|███▌      | 9/25 [02:53<04:33, 17.07s/epoch, beta=0.009, kld=116.993, loss=88.193, lr=7.16e-04, nll=87.152]

2026-06-02 00:52:29.716 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 09: loss=88.1933 nll=87.1524 kld=116.9927 beta=0.0094 lr=7.16e-04 time=13.6s

Эпохи:  40%|████      | 10/25 [03:11<04:22, 17.47s/epoch, beta=0.010, kld=113.046, loss=88.016, lr=6.58e-04, nll=86.891]

2026-06-02 00:52:48.101 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 10: loss=88.0157 nll=86.8914 kld=113.0459 beta=0.0105 lr=6.58e-04 time=18.4s

Эпохи:  44%|████▍     | 11/25 [03:31<04:12, 18.01s/epoch, beta=0.012, kld=110.001, loss=87.844, lr=5.98e-04, nll=86.635]

2026-06-02 00:53:07.327 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 11: loss=87.8441 nll=86.6350 kld=110.0010 beta=0.0115 lr=5.98e-04 time=19.2s

Эпохи:  48%|████▊     | 12/25 [03:50<03:59, 18.41s/epoch, beta=0.013, kld=106.657, loss=87.721, lr=5.36e-04, nll=86.437]

2026-06-02 00:53:26.653 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 12: loss=87.7213 nll=86.4372 kld=106.6567 beta=0.0126 lr=5.36e-04 time=19.3s

Эпохи:  52%|█████▏    | 13/25 [04:09<03:43, 18.66s/epoch, beta=0.014, kld=104.034, loss=87.545, lr=4.74e-04, nll=86.184]

2026-06-02 00:53:45.881 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 13: loss=87.5451 nll=86.1836 kld=104.0344 beta=0.0136 lr=4.74e-04 time=19.2s

Эпохи:  56%|█████▌    | 14/25 [04:28<03:27, 18.87s/epoch, beta=0.015, kld=101.331, loss=87.426, lr=4.12e-04, nll=85.994]

2026-06-02 00:54:05.224 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 14: loss=87.4257 nll=85.9935 kld=101.3306 beta=0.0147 lr=4.12e-04 time=19.3s

Эпохи:  60%|██████    | 15/25 [04:48<03:09, 18.97s/epoch, beta=0.016, kld=98.754, loss=87.302, lr=3.52e-04, nll=85.803]

2026-06-02 00:54:24.432 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 15: loss=87.3021 nll=85.8030 kld=98.7538 beta=0.0157 lr=3.52e-04 time=19.2s

Эпохи:  64%|██████▍   | 16/25 [05:07<02:51, 19.09s/epoch, beta=0.017, kld=96.393, loss=87.193, lr=2.94e-04, nll=85.629]

2026-06-02 00:54:43.806 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 16: loss=87.1928 nll=85.6287 kld=96.3930 beta=0.0168 lr=2.94e-04 time=19.4s

Эпохи:  68%|██████▊   | 17/25 [05:26<02:33, 19.14s/epoch, beta=0.018, kld=94.012, loss=87.093, lr=2.40e-04, nll=85.470]

2026-06-02 00:55:03.055 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 17: loss=87.0935 nll=85.4695 kld=94.0117 beta=0.0178 lr=2.40e-04 time=19.2s

Эпохи:  72%|███████▏  | 18/25 [05:45<02:14, 19.16s/epoch, beta=0.019, kld=92.007, loss=87.001, lr=1.89e-04, nll=85.315]

2026-06-02 00:55:22.280 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 18: loss=87.0007 nll=85.3149 kld=92.0069 beta=0.0188 lr=1.89e-04 time=19.2s

Эпохи:  76%|███████▌  | 19/25 [06:05<01:54, 19.15s/epoch, beta=0.020, kld=90.186, loss=86.923, lr=1.44e-04, nll=85.176]

2026-06-02 00:55:41.380 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 19: loss=86.9232 nll=85.1763 kld=90.1864 beta=0.0199 lr=1.44e-04 time=19.1s

Эпохи:  80%|████████  | 20/25 [06:24<01:35, 19.16s/epoch, beta=0.021, kld=88.389, loss=86.943, lr=1.05e-04, nll=85.138]

2026-06-02 00:56:00.572 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 20: loss=86.9425 nll=85.1380 kld=88.3886 beta=0.0209 lr=1.05e-04 time=19.2s

Эпохи:  84%|████████▍ | 21/25 [06:43<01:16, 19.23s/epoch, beta=0.022, kld=86.496, loss=86.939, lr=7.12e-05, nll=85.083]

2026-06-02 00:56:19.958 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 21: loss=86.9393 nll=85.0828 kld=86.4958 beta=0.0220 lr=7.12e-05 time=19.4s

Эпохи:  88%|████████▊ | 22/25 [06:58<00:53, 17.90s/epoch, beta=0.023, kld=84.969, loss=86.929, lr=4.48e-05, nll=85.017]

2026-06-02 00:56:34.776 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 22: loss=86.9295 nll=85.0167 kld=84.9692 beta=0.0230 lr=4.48e-05 time=14.8s

Эпохи:  92%|█████████▏| 23/25 [07:12<00:33, 16.62s/epoch, beta=0.024, kld=83.840, loss=86.954, lr=2.56e-05, nll=84.979]

2026-06-02 00:56:48.394 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 23: loss=86.9542 nll=84.9791 kld=83.8405 beta=0.0241 lr=2.56e-05 time=13.6s

Эпохи:  96%|█████████▌| 24/25 [07:27<00:16, 16.33s/epoch, beta=0.025, kld=82.562, loss=86.985, lr=1.39e-05, nll=84.954]

2026-06-02 00:57:04.063 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 24: loss=86.9850 nll=84.9536 kld=82.5624 beta=0.0251 lr=1.39e-05 time=15.7s

Эпохи: 100%|██████████| 25/25 [07:47<00:00, 18.68s/epoch, beta=0.026, kld=81.477, loss=87.048, lr=1.00e-05, nll=84.958]

2026-06-02 00:57:23.410 | INFO     | src.modeling.train_vae:train_vae:468 - Epoch 25: loss=87.0482 nll=84.9581 kld=81.4769 beta=0.0262 lr=1.00e-05 time=19.3s
2026-06-02 00:57:23.814 | INFO     | src.modeling.vae:save:477 - MultiVAE сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_final_279v7urq\artifacts\model.pt
2026-06-02 00:57:27.694 | INFO     | src.modeling.train_vae:train_vae:490 - user_items.npz сохранена в C:\Users\Sasha\AppData\Local\Temp\vae_final_279v7urq\artifacts
2026-06-02 00:57:28.453 | INFO     | src.modeling.vae:build_model:385 - MultiVAE собрана: num_items=11894, dims=[800, 64], device=cuda
2026-06-02 00:57:28.469 | INFO     | src.modeling.vae:load:497 - MultiVAE загружена из C:\Users\Sasha\AppData\Local\Temp\vae_final_279v7urq\artifacts\model.pt

Результат лучшего Mult-VAE (full data):
  ndcg: 0.056951
  precision: 0.058116
  recall: 0.039284

## Сравнение Mult-VAE / iALS / SVD

Условия одинаковые для всех:

- **Данные**: marketplace events, global temporal split 80/20
- **Метрика ранжирования**: NDCG@15, Precision@15, Recall@15
- **SVD**: лучший результат из `svd_experiments_unified.ipynb`
- **iALS**: лучший результат из `ials_research.ipynb`
- **Mult-VAE**: конфигурация, найденная Optuna на 40%-подмножестве

In [24]:
# svd_best = {
#     "model":     "SVD (best)",
#     "target":    "log_target",
#     "top_k":     15,
#     "ndcg":      0.135736,
#     "precision": 0.026741,
#     "recall":    0.026168,
#     "rmse":      3.111453,
#     "mae":       0.994588,
#     "hyperopt":  "grid (ручной)",
# }

ials_best = {
    "model":     "iALS (best, Optuna)",
    "target":    "log_target",
    "top_k":     15,
    'ndcg': 0.0362688,
    'precision': 0.029939,
    'recall': 0.0294947,
    'rmse': 0.8906239,
    'mae': 0.6648848,
    "rmse":      None,
    "mae":       None,
    "hyperopt":  "Optuna TPE, 25 trials, 40% subset",
}

vae_best = {
    "model":     "Mult-VAE (best, Optuna)",
    "target":    best_vae_result["target"],
    "top_k":     best_vae_result["top_k"],
    "ndcg":      best_vae_result["ndcg"],
    "precision": best_vae_result["precision"],
    "recall":    best_vae_result["recall"],
    "rmse":      best_vae_result["rmse"],
    "mae":       best_vae_result["mae"],
    "hyperopt":  f"Optuna TPE, {OPTUNA_TRIALS} trials, {SUBSET_FRACTION*100:.0f}% subset",
}

final_comparison = pl.DataFrame([ials_best, vae_best])

# ndcg_delta_vs_svd  = vae_best["ndcg"] - svd_best["ndcg"]
ndcg_delta_vs_ials = vae_best["ndcg"] - ials_best["ndcg"]
# print(f"NDCG@15: SVD={svd_best['ndcg']:.4f}  iALS={ials_best['ndcg']:.4f}  Mult-VAE={vae_best['ndcg']:.4f}")
# print(f"  Δ vs SVD:  {ndcg_delta_vs_svd:+.4f} ({ndcg_delta_vs_svd/svd_best['ndcg']*100:+.1f}%)")
print(f"  Δ vs iALS: {ndcg_delta_vs_ials:+.4f} ({ndcg_delta_vs_ials/ials_best['ndcg']*100:+.1f}%)")

final_comparison

  Δ vs iALS: +0.0207 (+57.0%)

shape: (2, 9)
┌─────────────────┬────────────┬───────┬───────────┬───┬───────────┬──────┬──────┬─────────────────┐
│ model           ┆ target     ┆ top_k ┆ ndcg      ┆ … ┆ recall    ┆ rmse ┆ mae  ┆ hyperopt        │
│ ---             ┆ ---        ┆ ---   ┆ ---       ┆   ┆ ---       ┆ ---  ┆ ---  ┆ ---             │
│ str             ┆ str        ┆ i64   ┆ f64       ┆   ┆ f64       ┆ null ┆ null ┆ str             │
╞═════════════════╪════════════╪═══════╪═══════════╪═══╪═══════════╪══════╪══════╪═════════════════╡
│ iALS (best,     ┆ log_target ┆ 15    ┆ 0.0362688 ┆ … ┆ 0.0294947 ┆ null ┆ null ┆ Optuna TPE, 25  │
│ Optuna)         ┆            ┆       ┆           ┆   ┆           ┆      ┆      ┆ trials, 40%     │
│                 ┆            ┆       ┆           ┆   ┆           ┆      ┆      ┆ sub…            │
│ Mult-VAE (best, ┆ log_target ┆ 15    ┆ 0.056951  ┆ … ┆ 0.039284  ┆ null ┆ null ┆ Optuna TPE, 20  │
│ Optuna)         ┆            ┆       ┆           ┆   ┆           ┆      ┆      ┆ trials, 40%     │
│                 ┆            ┆       ┆           ┆   ┆           ┆      ┆      ┆ sub…            │
└─────────────────┴────────────┴───────┴───────────┴───┴───────────┴──────┴──────┴─────────────────┘

## Выводы

- Mult-VAE учит нелинейное представление user-history и работает не на скалярном произведении, а на мультикатегориальном-распределении по items — это даёт ему преимущество на длинном хвосте.
- KL-annealing ($\beta$ от 0 до целевого) важен — без него VAE быстро коллапсирует в обычный AE.
- Логарифмированный таргет все еще лучше всего показывает себя в контексте качества модели. Также на текущий момент на MultVAE показывает наилучшие результаты по целевой метрике - ndcg@15.